//!!NODE_ROOT <section>
include::../../includes.txt[]
:https---docs-aws-amazon-com-AWSJavaSDK-latest-javadoc-com-amazonaws-services-ec2-AmazonEC2Client-html-authorizeSecurityGroupEgress-com-amazonaws-services-ec2-model-AuthorizeSecurityGroupEgressRequest-: {v1javadocs}com/amazonaws/services/ec2/AmazonEC2Client.html#authorizeSecurityGroupEgress-com.amazonaws.services.ec2.model.AuthorizeSecurityGroupEgressRequest-
:https---docs-aws-amazon-com-AWSJavaSDK-latest-javadoc-com-amazonaws-services-ec2-AmazonEC2Client-html-authorizeSecurityGroupIngress-com-amazonaws-services-ec2-model-AuthorizeSecurityGroupIngressRequest-: {v1javadocs}com/amazonaws/services/ec2/AmazonEC2Client.html#authorizeSecurityGroupIngress-com.amazonaws.services.ec2.model.AuthorizeSecurityGroupIngressRequest-
:https---docs-aws-amazon-com-AWSJavaSDK-latest-javadoc-com-amazonaws-services-ec2-model-AuthorizeSecurityGroupEgressRequest-html-withIpPermissions-com-amazonaws-services-ec2-model-IpPermission----: {v1javadocs}com/amazonaws/services/ec2/model/AuthorizeSecurityGroupEgressRequest.html#withIpPermissions-com.amazonaws.services.ec2.model.IpPermission...-
:https---docs-aws-amazon-com-AWSJavaSDK-latest-javadoc-com-amazonaws-services-ec2-model-IpPermission-html-withToPort-java-lang-Integer-: {v1javadocs}com/amazonaws/services/ec2/model/IpPermission.html#withToPort-java.lang.Integer-
:https---docs-aws-amazon-com-AWSJavaSDK-latest-javadoc-com-amazonaws-services-ec2-model-IpPermission-html-withFromPort-java-lang-Integer-: {v1javadocs}com/amazonaws/services/ec2/model/IpPermission.html#withFromPort-java.lang.Integer-
:https---docs-aws-amazon-com-AWSJavaSDK-latest-javadoc-com-amazonaws-services-ec2-model-IpPermission-html-withIpProtocol-java-lang-String-: {v1javadocs}com/amazonaws/services/ec2/model/IpPermission.html#withIpProtocol-java.lang.String-
:https---docs-aws-amazon-com-AWSJavaSDK-latest-javadoc-com-amazonaws-services-ec2-model-IpPermission-html-withIpv4Ranges-java-util-Collection-: {v1javadocs}com/amazonaws/services/ec2/model/IpPermission.html#withIpv4Ranges-java.util.Collection-
:https---docs-aws-amazon-com-AWSJavaSDK-latest-javadoc-com-amazonaws-services-ec2-AmazonEC2-html-createSecurityGroup-com-amazonaws-services-ec2-model-CreateSecurityGroupRequest-: {v1javadocs}com/amazonaws/services/ec2/AmazonEC2.html#createSecurityGroup-com.amazonaws.services.ec2.model.CreateSecurityGroupRequest-
:https---docs-aws-amazon-com-AWSJavaSDK-latest-javadoc-com-amazonaws-services-ec2-model-CreateSecurityGroupRequest-html-withDescription-java-lang-String-: {v1javadocs}com/amazonaws/services/ec2/model/CreateSecurityGroupRequest.html#withDescription-java.lang.String-
:https---docs-aws-amazon-com-AWSJavaSDK-latest-javadoc-com-amazonaws-services-ec2-model-CreateSecurityGroupRequest-html-withGroupName-java-lang-String-: {v1javadocs}com/amazonaws/services/ec2/model/CreateSecurityGroupRequest.html#withGroupName-java.lang.String-

[."topic"]
[[create-security-group,create-security-group.title]]
= [[create-an-ec2-security-group, Create an EC2 Security Group]]Create an {EC2} Security Group
:info_doctype: section
:info_title: Create an {EC2} Security Group

Create a  __security group__, which acts as a virtual firewall that controls the network traffic for one or more EC2 instances. By default, {EC2} associates your instances with a security group that allows no inbound traffic. You can create a security group that allows your EC2 instances to accept certain traffic. For example, if you need to connect to a Linux instance, you must configure the security group to allow SSH traffic. You can create a security group using the {EC2} console or the {sdk-java}.

You create a security group for use in either EC2-Classic or EC2-VPC. For more information about EC2-Classic and EC2-VPC, see {url-ec2-user}ec2-supported-platforms.html[Supported Platforms] in the {guide-ec2-user}.

For more information about creating a security group using the {EC2} console, see {url-ec2-user}using-network-security.html[{EC2} Security Groups] in the {guide-ec2-user}.

. Create and initialize a link:sdk-for-java/v1/reference/com/amazonaws/services/ec2/model/CreateSecurityGroupRequest.html["CreateSecurityGroupRequest", type="documentation"] instance. Use the {https---docs-aws-amazon-com-AWSJavaSDK-latest-javadoc-com-amazonaws-services-ec2-model-CreateSecurityGroupRequest-html-withGroupName-java-lang-String-}[withGroupName] method to set the security group name, and the {https---docs-aws-amazon-com-AWSJavaSDK-latest-javadoc-com-amazonaws-services-ec2-model-CreateSecurityGroupRequest-html-withDescription-java-lang-String-}[withDescription] method to set the security group description, as follows:
+
[source,java]
----
CreateSecurityGroupRequest csgr = new CreateSecurityGroupRequest();
csgr.withGroupName("JavaSecurityGroup").withDescription("My security group");
----
+

The security group name must be unique within the {AWS} region in which you initialize your {EC2} client. You must use US-ASCII characters for the security group name and description.
. Pass the request object as a parameter to the {https---docs-aws-amazon-com-AWSJavaSDK-latest-javadoc-com-amazonaws-services-ec2-AmazonEC2-html-createSecurityGroup-com-amazonaws-services-ec2-model-CreateSecurityGroupRequest-}[createSecurityGroup] method. The method returns a link:sdk-for-java/v1/reference/com/amazonaws/services/ec2/model/CreateSecurityGroupResult.html["CreateSecurityGroupResult", type="documentation"] object, as follows:
+
[source,java]
----
CreateSecurityGroupResult createSecurityGroupResult =
    amazonEC2Client.createSecurityGroup(csgr);
----
+

If you attempt to create a security group with the same name as an existing security group,  `createSecurityGroup` throws an exception.

By default, a new security group does not allow any inbound traffic to your {EC2} instance. To allow inbound traffic, you must explicitly authorize security group ingress. You can authorize ingress for individual IP addresses, for a range of IP addresses, for a specific protocol, and for TCP/UDP ports.

. Create and initialize an link:sdk-for-java/v1/reference/com/amazonaws/services/ec2/model/IpPermission.html["IpPermission", type="documentation"] instance. Use the {https---docs-aws-amazon-com-AWSJavaSDK-latest-javadoc-com-amazonaws-services-ec2-model-IpPermission-html-withIpv4Ranges-java-util-Collection-}[withIpv4Ranges] method to set the range of IP addresses to authorize ingress for, and use the {https---docs-aws-amazon-com-AWSJavaSDK-latest-javadoc-com-amazonaws-services-ec2-model-IpPermission-html-withIpProtocol-java-lang-String-}[withIpProtocol] method to set the IP protocol. Use the {https---docs-aws-amazon-com-AWSJavaSDK-latest-javadoc-com-amazonaws-services-ec2-model-IpPermission-html-withFromPort-java-lang-Integer-}[withFromPort] and {https---docs-aws-amazon-com-AWSJavaSDK-latest-javadoc-com-amazonaws-services-ec2-model-IpPermission-html-withToPort-java-lang-Integer-}[withToPort] methods to specify range of ports to authorize ingress for, as follows:
+
[source,java]
----
IpPermission ipPermission =
    new IpPermission();

IpRange ipRange1 = new IpRange().withCidrIp("111.111.111.111/32");
IpRange ipRange2 = new IpRange().withCidrIp("150.150.150.150/32");

ipPermission.withIpv4Ranges(Arrays.asList(new IpRange[] {ipRange1, ipRange2}))
            .withIpProtocol("tcp")
            .withFromPort(22)
            .withToPort(22);
----
+

All the conditions that you specify in the  `IpPermission` object must be met in order for ingress to be allowed.
+

Specify the IP address using CIDR notation. If you specify the protocol as TCP/UDP, you must provide a source port and a destination port. You can authorize ports only if you specify TCP or UDP.
. Create and initialize an link:sdk-for-java/v1/reference/com/amazonaws/services/ec2/model/AuthorizeSecurityGroupEgressRequest.html["AuthorizeSecurityGroupIngressRequest", type="documentation"] instance. Use the `withGroupName` method to specify the security group name, and pass the `IpPermission` object you initialized earlier to the {https---docs-aws-amazon-com-AWSJavaSDK-latest-javadoc-com-amazonaws-services-ec2-model-AuthorizeSecurityGroupEgressRequest-html-withIpPermissions-com-amazonaws-services-ec2-model-IpPermission----}[withIpPermissions] method, as follows:
+
[source,java]
----
AuthorizeSecurityGroupIngressRequest authorizeSecurityGroupIngressRequest =
    new AuthorizeSecurityGroupIngressRequest();

authorizeSecurityGroupIngressRequest.withGroupName("JavaSecurityGroup")
                                    .withIpPermissions(ipPermission);
----
. Pass the request object into the {https---docs-aws-amazon-com-AWSJavaSDK-latest-javadoc-com-amazonaws-services-ec2-AmazonEC2Client-html-authorizeSecurityGroupIngress-com-amazonaws-services-ec2-model-AuthorizeSecurityGroupIngressRequest-}[authorizeSecurityGroupIngress] method, as follows:
+
[source,java]
----
amazonEC2Client.authorizeSecurityGroupIngress(authorizeSecurityGroupIngressRequest);
----
+

If you call  `authorizeSecurityGroupIngress` with IP addresses for which ingress is already authorized, the method throws an exception. Create and initialize a new `IpPermission` object to authorize ingress for different IPs, ports, and protocols before calling ``AuthorizeSecurityGroupIngress``.

Whenever you call the  {https---docs-aws-amazon-com-AWSJavaSDK-latest-javadoc-com-amazonaws-services-ec2-AmazonEC2Client-html-authorizeSecurityGroupIngress-com-amazonaws-services-ec2-model-AuthorizeSecurityGroupIngressRequest-}[authorizeSecurityGroupIngress] or {https---docs-aws-amazon-com-AWSJavaSDK-latest-javadoc-com-amazonaws-services-ec2-AmazonEC2Client-html-authorizeSecurityGroupEgress-com-amazonaws-services-ec2-model-AuthorizeSecurityGroupEgressRequest-}[authorizeSecurityGroupEgress] methods, a rule is added to your security group.