//!!NODE_ROOT <section>
include::../../includes.txt[]

[."topic"]
[[credentials,credentials.title]]
= [[working-with-aws-credentials, Working with Credentials]]Working with {AWS} Credentials
:info_doctype: section
:info_title: Working with {AWS} Credentials
:info_abstract: How to load credentials for {AWS} using the {sdk-java}.

[abstract]
--
How to load credentials for {AWS} using the {sdk-java}.
--

To make requests to {AWSlong}, you must supply {AWS} credentials to the {sdk-java}. You can do this in the following ways:



* Use the default credential provider chain __(recommended)__.
* Use a specific credential provider or provider chain (or create your own).
* Supply the credentials yourself. These can be root account credentials, IAM credentials, or temporary credentials retrieved from {STS}.


[IMPORTANT]
====

For security, we  _strongly recommend_ that you _use IAM users_ instead of the root account for {AWS} access. For more information, see link:IAM/latest/UserGuide/best-practices.html["IAM Best Practices", type="documentation"] in the {guide-iam-user}.

====

[[credentials-default,credentials-default.title]]
== Using the Default Credential Provider Chain

When you initialize a new service client without supplying any arguments, the {sdk-java} attempts to find {AWS} credentials by using the  _default credential provider chain_ implemented by the link:sdk-for-java/v1/reference/com/amazonaws/auth/DefaultAWSCredentialsProviderChain.html["DefaultAWSCredentialsProviderChain", type="documentation"] class. The default credential provider chain looks for credentials in this order:

. **Environment variables**-``AWS_ACCESS_KEY_ID`` and ``AWS_SECRET_ACCESS_KEY``. The {sdk-java} uses the link:sdk-for-java/v1/reference/com/amazonaws/auth/EnvironmentVariableCredentialsProvider.html["EnvironmentVariableCredentialsProvider", type="documentation"] class to load these credentials.
. **Java system properties**-``aws.accessKeyId`` and ``aws.secretKey``. The {sdk-java} uses the link:sdk-for-java/v1/reference/com/amazonaws/auth/SystemPropertiesCredentialsProvider.html["SystemPropertiesCredentialsProvider", type="documentation"] to load these credentials.
. *Web Identity Token credentials* from the environment or container.
. **The default credential profiles file**- typically located at [path]``~/.aws/credentials`` (location can vary per platform), and shared by many of the {AWS} SDKs and by the {CLI}. The {sdk-java} uses the  link:sdk-for-java/v1/reference/com/amazonaws/auth/profile/ProfileCredentialsProvider.html["ProfileCredentialsProvider", type="documentation"] to load these credentials.
+

You can create a credentials file by using the `aws configure` command provided by the {CLI}, or you can create it by editing the file with a text editor. For information about the credentials file format, see xref:credentials-file-format[{AWS} Credentials File Format,linkend=credentials-file-format].
. **Amazon ECS container credentials**- loaded from the Amazon ECS if the environment variable `AWS_CONTAINER_CREDENTIALS_RELATIVE_URI` is set. The {sdk-java} uses the link:sdk-for-java/v1/reference/com/amazonaws/auth/ContainerCredentialsProvider.html["ContainerCredentialsProvider", type="documentation"] to load these credentials. You can specify the IP address for this value.
. **Instance profile credentials**- used on EC2 instances, and delivered through the {EC2} metadata service. The {sdk-java} uses the link:sdk-for-java/v1/reference/com/amazonaws/auth/InstanceProfileCredentialsProvider.html["InstanceProfileCredentialsProvider", type="documentation"] to load these credentials. You can specify the IP address for this value.
+
NOTE: Instance profile credentials are used only if `AWS_CONTAINER_CREDENTIALS_RELATIVE_URI` is not set. See link:sdk-for-java/v1/reference/com/amazonaws/auth/EC2ContainerCredentialsProviderWrapper.html["EC2ContainerCredentialsProviderWrapper", type="documentation"] for more information.


[[setting-credentials,setting-credentials.title]]
=== Setting Credentials

To be able to use {AWS} credentials, they must be set in  _at least one_ of the preceding locations. For information about setting credentials, see the following topics:



* To specify credentials in the _environment_ or in the default __credential profiles file__, see xref:setup-credentials[Set up {AWS} Credentials and Region for Development,linkend=setup-credentials].
* To set Java __system properties__, see the http://docs.oracle.com/javase/tutorial/essential/environment/sysprop.html[System Properties] tutorial on the official _Java Tutorials_ website.
* To set up and use _instance profile credentials_ with your EC2 instances, see xref:java-dg-roles[Using IAM Roles to Grant Access to {AWS} Resources on {EC2},linkend=java-dg-roles].


[[setting-an-alternate-credentials-profile,setting-an-alternate-credentials-profile.title]]
=== Setting an Alternate Credentials Profile

The {sdk-java} uses the  _default_ profile by default, but there are ways to customize which profile is sourced from the credentials file.

You can use the {AWS} Profile environment variable to change the profile loaded by the SDK.

For example, on Linux, macOS, or Unix you would run the following command to change the profile to __myProfile__.

[source,sh]
----
export AWS_PROFILE="myProfile"
----

On Windows you would use the following.

[source,bat]
----
set AWS_PROFILE="myProfile"
----

Setting the `AWS_PROFILE` environment variable affects credential loading for all officially
supported {AWS} SDKs and Tools (including the {CLI} and the {TWPlong}). To change only the profile for a Java application, you can use the system property `aws.profile` instead.

[NOTE]
====

The environment variable takes precedence over the system property.

====

[[setting-an-alternate-credentials-file-location,setting-an-alternate-credentials-file-location.title]]
=== Setting an Alternate Credentials File Location

The {sdk-java} loads {AWS} credentials automatically from the default credentials file location. However, you can also specify the location by setting the `AWS_CREDENTIAL_PROFILES_FILE` environment variable with the full path to the credentials file.

You can use this feature to temporarily change the location where the {sdk-java} looks for your credentials file (for example, by setting this variable with the command line). Or you can set the environment variable in your user or system environment to change it for the user or systemwide.

[[w3aab9c15b9c11b7b1]]
==== To override the default credentials file location

* Set the `AWS_CREDENTIAL_PROFILES_FILE` environment variable to the location of your {AWS} credentials file.
+
** On Linux, macOS, or Unix, use **``**export**``**:
+
[source,sh]
----
export AWS_CREDENTIAL_PROFILES_FILE=path/to/credentials_file
----
** On Windows, use **``**set**``**:
+
[source,bat]
----
set AWS_CREDENTIAL_PROFILES_FILE=path/to/credentials_file
----


[[credentials-file-format,credentials-file-format.title]]
=== Credentials File Format

When you use the  `aws configure` command to create an {AWS} credentials file, the command creates a file with the following format.

[source,ini]
----
[default]
aws_access_key_id={YOUR_ACCESS_KEY_ID}
aws_secret_access_key={YOUR_SECRET_ACCESS_KEY}

[profile2]
aws_access_key_id={YOUR_ACCESS_KEY_ID}
aws_secret_access_key={YOUR_SECRET_ACCESS_KEY}
----

The profile name is specified in square brackets (for example,  ``[default]``), followed by the configurable fields in that profile as key-value pairs. You can have multiple profiles in your credentials file, which can be added or edited using `aws configure --profile __PROFILE_NAME__` to select the profile to configure.

You can specify additional fields, such as ``aws_session_token``, ``metadata_service_timeout``,
and ``metadata_service_num_attempts``. These are not configurable with the CLI--you must edit the
file by hand if you want to use them. For more information about the configuration file and its
available fields, see
{url-cli-ug}cli-chap-getting-started.html[Configuring the {CLIlong}] in the {guide-cli-ug}.

[[loading-credentials,loading-credentials.title]]
=== Loading Credentials

After you set credentials, you can load them by using the default credential provider chain.

To do this, you instantiate an {AWS-service} client without explicitly providing credentials to the builder, as follows.

[source,java]
----
AmazonS3 s3Client = AmazonS3ClientBuilder.standard()
                       .withRegion(Regions.US_WEST_2)
                       .build();
----


[[credentials-specify-provider,credentials-specify-provider.title]]
== Specifying a Credential Provider or Provider Chain

You can specify a credential provider that is different from the  _default_ credential provider chain by using the client builder.

You provide an instance of a credentials provider or provider chain to a client builder that takes an link:sdk-for-java/v1/reference/com/amazonaws/auth/AWSCredentialsProvider.html["AWSCredentialsProvider", type="documentation"] interface as input. The following example shows how to use _environment_ credentials specifically.

[source,java]
----
AmazonS3 s3Client = AmazonS3ClientBuilder.standard()
                       .withCredentials(new EnvironmentVariableCredentialsProvider())
                       .build();
----

For the full list of {sdk-java}-supplied credential providers and provider chains, see  *All Known Implementing Classes* in link:sdk-for-java/v1/reference/com/amazonaws/auth/AWSCredentialsProvider.html["AWSCredentialsProvider", type="documentation"].

[NOTE]
====

You can use this technique to supply credential providers or provider chains that you create by using your own credential provider that implements the `AWSCredentialsProvider` interface, or by subclassing the link:sdk-for-java/v1/reference/com/amazonaws/auth/AWSCredentialsProviderChain.html["AWSCredentialsProviderChain", type="documentation"] class.

====

[[credentials-explicit,credentials-explicit.title]]
== Explicitly Specifying Credentials

If the default credential chain or a specific or custom provider or provider chain doesn't work for your code, you can set credentials that you supply explicitly. If you've retrieved temporary credentials using {STS}, use this method to specify the credentials for {AWS} access.

. Instantiate a class that provides the link:sdk-for-java/v1/reference/com/amazonaws/auth/AWSCredentials.html["AWSCredentials", type="documentation"] interface, such as link:sdk-for-java/v1/reference/com/amazonaws/auth/BasicAWSCredentials.html["BasicAWSCredentials", type="documentation"], and supply it with the {AWS} access key and secret key you will use for the connection.
. Create an link:sdk-for-java/v1/reference/com/amazonaws/auth/AWSStaticCredentialsProvider.html["AWSStaticCredentialsProvider", type="documentation"] with the `AWSCredentials` object.
. Configure the client builder with the `AWSStaticCredentialsProvider` and build the client.

The following is an example.

[source,java]
----
BasicAWSCredentials awsCreds = new BasicAWSCredentials("access_key_id", "secret_key_id");
AmazonS3 s3Client = AmazonS3ClientBuilder.standard()
                        .withCredentials(new AWSStaticCredentialsProvider(awsCreds))
                        .build();
----

When using  xref:prog-services-sts[temporary credentials obtained from STS,linkend=prog-services-sts], create a link:sdk-for-java/v1/reference/com/amazonaws/auth/BasicSessionCredentials.html["BasicSessionCredentials", type="documentation"] object, passing it the STS-supplied credentials and session token.

[source,java]
----
BasicSessionCredentials sessionCredentials = new BasicSessionCredentials(
   session_creds.getAccessKeyId(),
   session_creds.getSecretAccessKey(),
   session_creds.getSessionToken());

AmazonS3 s3 = AmazonS3ClientBuilder.standard()
                        .withCredentials(new AWSStaticCredentialsProvider(sessionCredentials))
                        .build();
----


[[more-info,more-info.title]]
== More Info

* xref:signup-create-iam-user[Sign Up for {AWS} and Create an IAM User,linkend=signup-create-iam-user]
* xref:setup-credentials[Set up {AWS} Credentials and Region for Development,linkend=setup-credentials]
* xref:java-dg-roles[Using IAM Roles to Grant Access to {AWS} Resources on {EC2},linkend=java-dg-roles]
