//!!NODE_ROOT <section>
include::../../includes.txt[]
:https---docs-aws-amazon-com-AWSEC2-latest-APIReference-API-DeleteKeyPair-html: {url-doc-domain}AWSEC2/latest/APIReference/API_DeleteKeyPair.html
:https---docs-aws-amazon-com-AWSEC2-latest-APIReference-API-DescribeKeyPairs-html: {url-doc-domain}AWSEC2/latest/APIReference/API_DescribeKeyPairs.html
:https---docs-aws-amazon-com-AWSEC2-latest-APIReference-API-CreateKeyPair-html: {url-doc-domain}AWSEC2/latest/APIReference/API_CreateKeyPair.html
:https---github-com-awsdocs-aws-doc-sdk-examples-blob-master-java-example-code-ec2-src-main-java-aws-example-ec2-DeleteKeyPair-java: {url-awsdocs-github}aws-doc-sdk-examples/blob/master/java/example_code/ec2/src/main/java/aws/example/ec2/DeleteKeyPair.java
:https---github-com-awsdocs-aws-doc-sdk-examples-blob-master-java-example-code-ec2-src-main-java-aws-example-ec2-DescribeKeyPairs-java: {url-awsdocs-github}aws-doc-sdk-examples/blob/master/java/example_code/ec2/src/main/java/aws/example/ec2/DescribeKeyPairs.java
:https---github-com-awsdocs-aws-doc-sdk-examples-blob-master-java-example-code-ec2-src-main-java-aws-example-ec2-CreateKeyPair-java: {url-awsdocs-github}aws-doc-sdk-examples/blob/master/java/example_code/ec2/src/main/java/aws/example/ec2/CreateKeyPair.java

[."topic"]
[[examples-ec2-key-pairs,examples-ec2-key-pairs.title]]
= [[working-with-ec2-key-pairs, Working with EC2 Key Pairs]]Working with {EC2} Key Pairs
:info_doctype: section
:info_title: Working with {EC2} Key Pairs
:info_abstract: How to create, list and delete EC2 key pairs using the {sdk-java}.
:info_keywordset: sdk-javacodeexamplesEC2 key pairscreate key pairlist key pairsdelete key pair

[abstract]
--
How to create, list and delete EC2 key pairs using the {sdk-java}.
--

[[creating-a-key-pair,creating-a-key-pair.title]]
== Creating a Key Pair

To create a key pair, call the AmazonEC2Client's  `createKeyPair` method with a link:sdk-for-java/v1/reference/com/amazonaws/services/ec2/model/CreateKeyPairRequest.html["CreateKeyPairRequest", type="documentation"] that contains the key's name.

*Imports*

[source,java]
----
import com.amazonaws.services.ec2.AmazonEC2;
import com.amazonaws.services.ec2.AmazonEC2ClientBuilder;
import com.amazonaws.services.ec2.model.CreateKeyPairRequest;
import com.amazonaws.services.ec2.model.CreateKeyPairResult;
----

*Code*

[source,java]
----
final AmazonEC2 ec2 = AmazonEC2ClientBuilder.defaultClient();

CreateKeyPairRequest request = new CreateKeyPairRequest()
    .withKeyName(key_name);

CreateKeyPairResult response = ec2.createKeyPair(request);
----

See the  {https---github-com-awsdocs-aws-doc-sdk-examples-blob-master-java-example-code-ec2-src-main-java-aws-example-ec2-CreateKeyPair-java}[complete example].

[[describing-key-pairs,describing-key-pairs.title]]
== Describing Key Pairs

To list your key pairs or to get information about them, call the AmazonEC2Client's  `describeKeyPairs` method. It returns a link:sdk-for-java/v1/reference/com/amazonaws/services/ec2/model/DescribeKeyPairsResult.html["DescribeKeyPairsResult", type="documentation"] that you can use to access the list of key pairs by calling its `getKeyPairs` method, which returns a list of link:sdk-for-java/v1/reference/com/amazonaws/services/ec2/model/KeyPairInfo.html["KeyPairInfo", type="documentation"] objects.

*Imports*

[source,java]
----
import com.amazonaws.services.ec2.AmazonEC2;
import com.amazonaws.services.ec2.AmazonEC2ClientBuilder;
import com.amazonaws.services.ec2.model.DescribeKeyPairsResult;
import com.amazonaws.services.ec2.model.KeyPairInfo;
----

*Code*

[source,java]
----
final AmazonEC2 ec2 = AmazonEC2ClientBuilder.defaultClient();

DescribeKeyPairsResult response = ec2.describeKeyPairs();

for(KeyPairInfo key_pair : response.getKeyPairs()) {
    System.out.printf(
        "Found key pair with name %s " +
        "and fingerprint %s",
        key_pair.getKeyName(),
        key_pair.getKeyFingerprint());
}
----

See the  {https---github-com-awsdocs-aws-doc-sdk-examples-blob-master-java-example-code-ec2-src-main-java-aws-example-ec2-DescribeKeyPairs-java}[complete example].

[[deleting-a-key-pair,deleting-a-key-pair.title]]
== Deleting a Key Pair

To delete a key pair, call the AmazonEC2Client's  `deleteKeyPair` method, passing it a link:sdk-for-java/v1/reference/com/amazonaws/services/ec2/model/DeleteKeyPairRequest.html["DeleteKeyPairRequest", type="documentation"] that contains the name of the key pair to delete.

*Imports*

[source,java]
----
import com.amazonaws.services.ec2.AmazonEC2;
import com.amazonaws.services.ec2.AmazonEC2ClientBuilder;
import com.amazonaws.services.ec2.model.DeleteKeyPairRequest;
import com.amazonaws.services.ec2.model.DeleteKeyPairResult;
----

*Code*

[source,java]
----
final AmazonEC2 ec2 = AmazonEC2ClientBuilder.defaultClient();

DeleteKeyPairRequest request = new DeleteKeyPairRequest()
    .withKeyName(key_name);

DeleteKeyPairResult response = ec2.deleteKeyPair(request);
----

See the  {https---github-com-awsdocs-aws-doc-sdk-examples-blob-master-java-example-code-ec2-src-main-java-aws-example-ec2-DeleteKeyPair-java}[complete example].

[[more-information,more-information.title]]
== More Information

* {url-ec2-user}ec2-key-pairs.html[{EC2} Key Pairs] in the {guide-ec2-user}
* {https---docs-aws-amazon-com-AWSEC2-latest-APIReference-API-CreateKeyPair-html}[CreateKeyPair] in the {EC2} API Reference
* {https---docs-aws-amazon-com-AWSEC2-latest-APIReference-API-DescribeKeyPairs-html}[DescribeKeyPairs] in the {EC2} API Reference
* {https---docs-aws-amazon-com-AWSEC2-latest-APIReference-API-DeleteKeyPair-html}[DeleteKeyPair] in the {EC2} API Reference
