//!!NODE_ROOT <section>
include::../../includes.txt[]
:https---github-com-awsdocs-aws-doc-sdk-examples-blob-master-java-example-code-s3-src-main-java-aws-example-s3-DeleteBucketPolicy-java: {url-awsdocs-github}aws-doc-sdk-examples/blob/master/java/example_code/s3/src/main/java/aws/example/s3/DeleteBucketPolicy.java
:https---github-com-awsdocs-aws-doc-sdk-examples-blob-master-java-example-code-s3-src-main-java-aws-example-s3-GetBucketPolicy-java: {url-awsdocs-github}aws-doc-sdk-examples/blob/master/java/example_code/s3/src/main/java/aws/example/s3/GetBucketPolicy.java
:https---github-com-awsdocs-aws-doc-sdk-examples-blob-master-java-example-code-s3-src-main-java-aws-example-s3-SetBucketPolicy-java: {url-awsdocs-github}aws-doc-sdk-examples/blob/master/java/example_code/s3/src/main/java/aws/example/s3/SetBucketPolicy.java

[."topic"]
[[examples-s3-bucket-policies,examples-s3-bucket-policies.title]]
= [[managing-access-to-s3-buckets-using-bucket-policies, Managing Access to S3 Buckets Using Bucket Policies]]Managing Access to {S3} Buckets Using Bucket Policies
:info_doctype: section
:info_title: Managing Access to {S3} Buckets Using Bucket Policies
:info_abstract: How to set, get, and delete a policy for an {S3} bucket.
:info_keywordset: sdk-javacode examplesbucket policies

[abstract]
--
How to set, get, and delete a policy for an {S3} bucket.
--

You can set, get, or delete a  _bucket policy_ to manage access to your {S3} buckets.

[[set-s3-bucket-policy,set-s3-bucket-policy.title]]
== Set a Bucket Policy

You can set the bucket policy for a particular S3 bucket by:



* Calling the AmazonS3 client's `setBucketPolicy` and providing it with a link:sdk-for-java/v1/reference/com/amazonaws/services/s3/model/SetBucketPolicyRequest.html["SetBucketPolicyRequest", type="documentation"]
* Setting the policy directly by using the `setBucketPolicy` overload that takes a bucket name and policy text (in JSON format)

*Imports*

[source,java]
----
import com.amazonaws.AmazonServiceException;
import com.amazonaws.auth.policy.Policy;
import com.amazonaws.auth.policy.Principal;
----

*Code*

[source,java]
----
    s3.setBucketPolicy(bucket_name, policy_text);
} catch (AmazonServiceException e) {
    System.err.println(e.getErrorMessage());
    System.exit(1);
}
----


[[use-s3-bucket-policy-class,use-s3-bucket-policy-class.title]]
=== Use the Policy Class to Generate or Validate a Policy

When providing a bucket policy to  ``setBucketPolicy``, you can do the following:



* Specify the policy directly as a string of JSON-formatted text
* Build the policy using the link:sdk-for-java/v1/reference/com/amazonaws/auth/policy/Policy.html["Policy", type="documentation"] class

By using the  `Policy` class, you don't have to be concerned about correctly formatting your text string. To get the JSON policy text from the `Policy` class, use its `toJson` method.

*Imports*

[source,java]
----
import com.amazonaws.auth.policy.Resource;
import com.amazonaws.auth.policy.Statement;
import com.amazonaws.auth.policy.actions.S3Actions;
import com.amazonaws.regions.Regions;
import com.amazonaws.services.s3.AmazonS3;
import com.amazonaws.services.s3.AmazonS3ClientBuilder;
----

*Code*

[source,java]
----
        new Statement(Statement.Effect.Allow)
                .withPrincipals(Principal.AllUsers)
                .withActions(S3Actions.GetObject)
                .withResources(new Resource(
                        "{region-arn}s3:::" + bucket_name + "/*")));
return bucket_policy.toJson();
----

The  `Policy` class also provides a `fromJson` method that can attempt to build a policy using a passed-in JSON string. The method validates it to ensure that the text can be transformed into a valid policy structure, and will fail with an `IllegalArgumentException` if the policy text is invalid.

[source,java]
----
Policy bucket_policy = null;
try {
    bucket_policy = Policy.fromJson(file_text.toString());
} catch (IllegalArgumentException e) {
    System.out.format("Invalid policy text in file: \"%s\"",
            policy_file);
    System.out.println(e.getMessage());
}
----

You can use this technique to prevalidate a policy that you read in from a file or other means.

See the {https---github-com-awsdocs-aws-doc-sdk-examples-blob-master-java-example-code-s3-src-main-java-aws-example-s3-SetBucketPolicy-java}[complete example] on GitHub.

[[get-s3-bucket-policy,get-s3-bucket-policy.title]]
== Get a Bucket Policy

To retrieve the policy for an {S3} bucket, call the AmazonS3 client's  `getBucketPolicy` method, passing it the name of the bucket to get the policy from.

*Imports*

[source,java]
----
import com.amazonaws.AmazonServiceException;
import com.amazonaws.regions.Regions;
import com.amazonaws.services.s3.AmazonS3;
import com.amazonaws.services.s3.AmazonS3ClientBuilder;
----

*Code*

[source,java]
----
  try {
      BucketPolicy bucket_policy = s3.getBucketPolicy(bucket_name);
      policy_text = bucket_policy.getPolicyText();
  } catch (AmazonServiceException e) {
      System.err.println(e.getErrorMessage());
      System.exit(1);
  }
----

If the named bucket doesn't exist, if you don't have access to it, or if it has no bucket policy, an  `AmazonServiceException` is thrown.

See the {https---github-com-awsdocs-aws-doc-sdk-examples-blob-master-java-example-code-s3-src-main-java-aws-example-s3-GetBucketPolicy-java}[complete example] on GitHub.

[[delete-s3-bucket-policy,delete-s3-bucket-policy.title]]
== Delete a Bucket Policy

To delete a bucket policy, call the AmazonS3 client's  ``deleteBucketPolicy``, providing it with the bucket name.

*Imports*

[source,java]
----
import com.amazonaws.AmazonServiceException;
import com.amazonaws.regions.Regions;
import com.amazonaws.services.s3.AmazonS3;
----

*Code*

[source,java]
----
  try {
      s3.deleteBucketPolicy(bucket_name);
  } catch (AmazonServiceException e) {
      System.err.println(e.getErrorMessage());
      System.exit(1);
  }
----

This method succeeds even if the bucket doesn't already have a policy. If you specify a bucket name that doesn't exist or if you don't have access to the bucket, an  `AmazonServiceException` is thrown.

See the {https---github-com-awsdocs-aws-doc-sdk-examples-blob-master-java-example-code-s3-src-main-java-aws-example-s3-DeleteBucketPolicy-java}[complete example] on GitHub.

[[more-info,more-info.title]]
== More Info

* {url-s3-dev}access-policy-language-overview.html[Access Policy Language Overview] in the {guide-s3-dev}
* {url-s3-dev}example-bucket-policies.html[Bucket Policy Examples] in the {guide-s3-dev}
