//!!NODE_ROOT <section>
include::../../includes.txt[]
:https---docs-aws-amazon-com-AWSSimpleQueueService-latest-APIReference-API-SetQueueAttributes-html: {url-doc-domain}AWSSimpleQueueService/latest/APIReference/API_SetQueueAttributes.html
:https---github-com-awsdocs-aws-doc-sdk-examples-blob-master-java-example-code-sqs-src-main-java-aws-example-sqs-DeadLetterQueues-java: {url-awsdocs-github}aws-doc-sdk-examples/blob/master/java/example_code/sqs/src/main/java/aws/example/sqs/DeadLetterQueues.java

[."topic"]
[[examples-sqs-dead-letter-queues,examples-sqs-dead-letter-queues.title]]
= [[using-dead-letter-queues-in-sqs, Using Dead Letter Queues in {SQS}]]Using Dead Letter Queues in {SQS}
:info_doctype: section
:info_title: Using Dead Letter Queues in {SQS}
:info_abstract: How to enable long polling for {SQS} message queues.
:info_keywordset: sdk-javacode examplesSQSlong pollingqueue management

[abstract]
--
How to enable long polling for {SQS} message queues.
--

{SQS} provides support for  __dead letter queues__. A dead letter queue is a queue that other (source) queues can target for messages that can't be processed successfully. You can set aside and isolate these messages in the dead letter queue to determine why their processing did not succeed.

[[sqs-dead-letter-queue-create-dl-queue,sqs-dead-letter-queue-create-dl-queue.title]]
== Creating a Dead Letter Queue

A dead letter queue is created the same way as a regular queue, but it has the following restrictions:



* A dead letter queue must be the same type of queue (FIFO or standard) as the source queue.
* A dead letter queue must be created using the same {AWS-account} and region as the source queue.

Here we create two identical {SQS} queues, one of which will serve as the dead letter queue:

*Imports*

[source,java]
----
import com.amazonaws.services.sqs.AmazonSQS;
import com.amazonaws.services.sqs.AmazonSQSClientBuilder;
import com.amazonaws.services.sqs.model.AmazonSQSException;
----

*Code*

[source,java]
----
final AmazonSQS sqs = AmazonSQSClientBuilder.defaultClient();

// Create source queue
try {
    sqs.createQueue(src_queue_name);
} catch (AmazonSQSException e) {
    if (!e.getErrorCode().equals("QueueAlreadyExists")) {
        throw e;
    }
}

// Create dead-letter queue
try {
    sqs.createQueue(dl_queue_name);
} catch (AmazonSQSException e) {
    if (!e.getErrorCode().equals("QueueAlreadyExists")) {
        throw e;
    }
}
----

See the  {https---github-com-awsdocs-aws-doc-sdk-examples-blob-master-java-example-code-sqs-src-main-java-aws-example-sqs-DeadLetterQueues-java}[complete example] on GitHub.

[[sqs-dead-letter-queue-set-redrive-policy,sqs-dead-letter-queue-set-redrive-policy.title]]
== Designating a Dead Letter Queue for a Source Queue

To designate a dead letter queue, you must first create a  __redrive policy__, and then set the policy in the queue's attributes. A redrive policy is specified in JSON, and specifies the ARN of the dead letter queue and the maximum number of times the message can be received and not processed before it's sent to the dead letter queue.

To set the redrive policy for your source queue, call the AmazonSQS class' `setQueueAttributes` method with a link:sdk-for-java/v1/reference/com/amazonaws/services/sqs/model/SetQueueAttributesRequest.html["SetQueueAttributesRequest", type="documentation"] object for which you've set the `RedrivePolicy` attribute with your JSON redrive policy.

*Imports*

[source,java]
----
import com.amazonaws.services.sqs.model.GetQueueAttributesRequest;
import com.amazonaws.services.sqs.model.GetQueueAttributesResult;
import com.amazonaws.services.sqs.model.SetQueueAttributesRequest;
----

*Code*

[source,java]
----
String dl_queue_url = sqs.getQueueUrl(dl_queue_name)
                         .getQueueUrl();

GetQueueAttributesResult queue_attrs = sqs.getQueueAttributes(
        new GetQueueAttributesRequest(dl_queue_url)
            .withAttributeNames("QueueArn"));

String dl_queue_arn = queue_attrs.getAttributes().get("QueueArn");

// Set dead letter queue with redrive policy on source queue.
String src_queue_url = sqs.getQueueUrl(src_queue_name)
                          .getQueueUrl();

SetQueueAttributesRequest request = new SetQueueAttributesRequest()
        .withQueueUrl(src_queue_url)
        .addAttributesEntry("RedrivePolicy",
                "{\"maxReceiveCount\":\"5\", \"deadLetterTargetArn\":\""
                + dl_queue_arn + "\"}");

sqs.setQueueAttributes(request);
----

See the  {https---github-com-awsdocs-aws-doc-sdk-examples-blob-master-java-example-code-sqs-src-main-java-aws-example-sqs-DeadLetterQueues-java}[complete example] on GitHub.

[[more-info,more-info.title]]
== More Info

* link:AWSSimpleQueueService/latest/SQSDeveloperGuide/sqs-dead-letter-queues.html["Using pass:q[[.shared\]`SQS`] Dead Letter Queues", type="documentation"] in the {SQS} Developer Guide
* {https---docs-aws-amazon-com-AWSSimpleQueueService-latest-APIReference-API-SetQueueAttributes-html}[SetQueueAttributes] in the {SQS} API Reference
