//!!NODE_ROOT <section>
include::../../includes.txt[]
:https---docs-aws-amazon-com-AWSSimpleQueueService-latest-APIReference-API-DeleteMessage-html: {url-doc-domain}AWSSimpleQueueService/latest/APIReference/API_DeleteMessage.html
:https---docs-aws-amazon-com-AWSSimpleQueueService-latest-APIReference-API-ReceiveMessage-html: {url-doc-domain}AWSSimpleQueueService/latest/APIReference/API_ReceiveMessage.html
:https---docs-aws-amazon-com-AWSSimpleQueueService-latest-APIReference-API-SendMessageBatch-html: {url-doc-domain}AWSSimpleQueueService/latest/APIReference/API_SendMessageBatch.html
:https---docs-aws-amazon-com-AWSSimpleQueueService-latest-APIReference-API-SendMessage-html: {url-doc-domain}AWSSimpleQueueService/latest/APIReference/API_SendMessage.html
:https---github-com-awsdocs-aws-doc-sdk-examples-blob-master-java-example-code-sqs-src-main-java-aws-example-sqs-SendReceiveMessages-java: {url-awsdocs-github}aws-doc-sdk-examples/blob/master/java/example_code/sqs/src/main/java/aws/example/sqs/SendReceiveMessages.java

[."topic"]
[[examples-sqs-messages,examples-sqs-messages.title]]
= [[sending-receiving-and-deleting-sqs-messages, Sending, Receiving, and Deleting {SQS} Messages]]Sending, Receiving, and Deleting {SQS} Messages
:info_doctype: section
:info_title: Sending, Receiving, and Deleting {SQS} Messages
:info_abstract: How to send, receive and delete {SQS} messages.
:info_keywordset: sdk-javacode examples{SQS}send messagereceive messagedelete message

[abstract]
--
How to send, receive and delete {SQS} messages.
--

This topic describes how to send, receive and delete {SQS} messages. Messages are always delivered using an  xref:examples-sqs-message-queues[SQS Queue,linkend=examples-sqs-message-queues].

[[sqs-message-send,sqs-message-send.title]]
== Send a Message

Add a single message to an {SQS} queue by calling the AmazonSQS client's  `sendMessage` method. Provide a link:sdk-for-java/v1/reference/com/amazonaws/services/sqs/model/SendMessageRequest.html["SendMessageRequest", type="documentation"] object that contains the queue's xref:sqs-get-queue-url[URL,linkend=sqs-get-queue-url], message body, and optional delay value (in seconds).

*Imports*

[source,java]
----
import com.amazonaws.services.sqs.AmazonSQS;
import com.amazonaws.services.sqs.AmazonSQSClientBuilder;
import com.amazonaws.services.sqs.model.SendMessageRequest;
----

*Code*

[source,java]
----
SendMessageRequest send_msg_request = new SendMessageRequest()
        .withQueueUrl(queueUrl)
        .withMessageBody("hello world")
        .withDelaySeconds(5);
sqs.sendMessage(send_msg_request);
----

See the  {https---github-com-awsdocs-aws-doc-sdk-examples-blob-master-java-example-code-sqs-src-main-java-aws-example-sqs-SendReceiveMessages-java}[complete example] on GitHub.

[[sqs-messages-send-multiple,sqs-messages-send-multiple.title]]
=== Send Multiple Messages at Once

You can send more than one message in a single request. To send multiple messages, use the AmazonSQS client's  `sendMessageBatch` method, which takes a link:sdk-for-java/v1/reference/com/amazonaws/services/sqs/model/SendMessageBatchRequest.html["SendMessageBatchRequest", type="documentation"] containing the queue URL and a list of messages (each one a link:sdk-for-java/v1/reference/com/amazonaws/services/sqs/model/SendMessageBatchRequestEntry.html["SendMessageBatchRequestEntry", type="documentation"]) to send. You can also set an optional delay value per message.

*Imports*

[source,java]
----
import com.amazonaws.services.sqs.model.SendMessageBatchRequest;
import com.amazonaws.services.sqs.model.SendMessageBatchRequestEntry;
----

*Code*

[source,java]
----
SendMessageBatchRequest send_batch_request = new SendMessageBatchRequest()
        .withQueueUrl(queueUrl)
        .withEntries(
                new SendMessageBatchRequestEntry(
                        "msg_1", "Hello from message 1"),
                new SendMessageBatchRequestEntry(
                        "msg_2", "Hello from message 2")
                        .withDelaySeconds(10));
sqs.sendMessageBatch(send_batch_request);
----

See the  {https---github-com-awsdocs-aws-doc-sdk-examples-blob-master-java-example-code-sqs-src-main-java-aws-example-sqs-SendReceiveMessages-java}[complete example] on GitHub.

[[sqs-messages-receive,sqs-messages-receive.title]]
== Receive Messages

Retrieve any messages that are currently in the queue by calling the AmazonSQS client's  `receiveMessage` method, passing it the queue's URL. Messages are returned as a list of link:sdk-for-java/v1/reference/com/amazonaws/services/sqs/model/Message.html["Message", type="documentation"] objects.

*Imports*

[source,java]
----
import com.amazonaws.services.sqs.AmazonSQSClientBuilder;
import com.amazonaws.services.sqs.model.AmazonSQSException;
import com.amazonaws.services.sqs.model.SendMessageBatchRequest;
----

*Code*

[source,java]
----
List<Message> messages = sqs.receiveMessage(queueUrl).getMessages();
----


[[sqs-messages-delete,sqs-messages-delete.title]]
== Delete Messages after Receipt

After receiving a message and processing its contents, delete the message from the queue by sending the message's receipt handle and queue URL to the AmazonSQS client's  `deleteMessage` method.

*Code*

[source,java]
----
for (Message m : messages) {
    sqs.deleteMessage(queueUrl, m.getReceiptHandle());
}
----

See the  {https---github-com-awsdocs-aws-doc-sdk-examples-blob-master-java-example-code-sqs-src-main-java-aws-example-sqs-SendReceiveMessages-java}[complete example] on GitHub.

[[more-info,more-info.title]]
== More Info

* link:AWSSimpleQueueService/latest/SQSDeveloperGuide/sqs-how-it-works.html["How pass:q[[.shared\]`SQS`] Queues Work", type="documentation"] in the {SQS} Developer Guide
* {https---docs-aws-amazon-com-AWSSimpleQueueService-latest-APIReference-API-SendMessage-html}[SendMessage] in the {SQS} API Reference
* {https---docs-aws-amazon-com-AWSSimpleQueueService-latest-APIReference-API-SendMessageBatch-html}[SendMessageBatch] in the {SQS} API Reference
* {https---docs-aws-amazon-com-AWSSimpleQueueService-latest-APIReference-API-ReceiveMessage-html}[ReceiveMessage] in the {SQS} API Reference
* {https---docs-aws-amazon-com-AWSSimpleQueueService-latest-APIReference-API-DeleteMessage-html}[DeleteMessage] in the {SQS} API Reference
