//!!NODE_ROOT <section>
include::../../includes.txt[]
:https---docs-aws-amazon-com-AmazonCloudWatchEvents-latest-APIReference-API-PutRule-html: {url-doc-domain}AmazonCloudWatchEvents/latest/APIReference/API_PutRule.html
:https---docs-aws-amazon-com-AmazonCloudWatchEvents-latest-APIReference-API-PutTargets-html: {url-doc-domain}AmazonCloudWatchEvents/latest/APIReference/API_PutTargets.html
:https---docs-aws-amazon-com-AmazonCloudWatchEvents-latest-APIReference-API-PutEvents-html: {url-doc-domain}AmazonCloudWatchEvents/latest/APIReference/API_PutEvents.html

[."topic"]
[[examples-cloudwatch-send-events,examples-cloudwatch-send-events.title]]
= [[sending-events-to-cw, Sending Events to CloudWatch]]Sending Events to {CW}
:info_doctype: section
:info_title: Sending Events to {CW}
:info_abstract: How to add events, rules and rule targets for {CWlong} using the {sdk-java}.
:info_keywordset: cloudwatch eventsadd ruleadd eventsadd targetscode examples

[abstract]
--
How to add events, rules and rule targets for {CWlong} using the {sdk-java}.
--

{CW} Events delivers a near real-time stream of system events that describe changes in {AWS}
resources to {EC2} instances, {LAM} functions, {AK} streams, {ECS} tasks, {SFN} state machines,
{SNS} topics, {SQS} queues, or built-in targets. You can match events and route them to one or
more target functions or streams by using simple rules.

[[add-events,add-events.title]]
== Add Events

To add custom {CW} events, call the AmazonCloudWatchEventsClient's  `putEvents` method with a
link:sdk-for-java/v1/reference/com/amazonaws/services/cloudwatchevents/model/PutEventsRequest.html["PutEventsRequest", type="documentation"]
object that contains one or more
link:sdk-for-java/v1/reference/com/amazonaws/services/cloudwatchevents/model/PutEventsRequestEntry.html["PutEventsRequestEntry", type="documentation"]
objects that provide details about each event. You can specify several parameters for the entry
such as the source and type of the event, resources associated with the event, and so on.

[NOTE]
====

You can specify a maximum of 10 events per call to ``putEvents``.

====

*Imports*

[source,java]
----
import com.amazonaws.services.cloudwatchevents.AmazonCloudWatchEvents;
import com.amazonaws.services.cloudwatchevents.AmazonCloudWatchEventsClientBuilder;
import com.amazonaws.services.cloudwatchevents.model.PutEventsRequest;
import com.amazonaws.services.cloudwatchevents.model.PutEventsRequestEntry;
import com.amazonaws.services.cloudwatchevents.model.PutEventsResult;
----

*Code*

[source,java]
----
final AmazonCloudWatchEvents cwe =
    AmazonCloudWatchEventsClientBuilder.defaultClient();

final String EVENT_DETAILS =
    "{ \"key1\": \"value1\", \"key2\": \"value2\" }";

PutEventsRequestEntry request_entry = new PutEventsRequestEntry()
    .withDetail(EVENT_DETAILS)
    .withDetailType("sampleSubmitted")
    .withResources(resource_arn)
    .withSource("aws-sdk-java-cloudwatch-example");

PutEventsRequest request = new PutEventsRequest()
    .withEntries(request_entry);

PutEventsResult response = cwe.putEvents(request);
----


[[add-rules,add-rules.title]]
== Add Rules

To create or update a rule, call the AmazonCloudWatchEventsClient's  `putRule` method with a
link:sdk-for-java/v1/reference/com/amazonaws/services/cloudwatchevents/model/PutRuleRequest.html["PutRuleRequest", type="documentation"]
with the name of the rule and optional parameters such as the
link:AmazonCloudWatch/latest/events/CloudWatchEventsandEventPatterns.html["event pattern", type="documentation"],
{IAM} role to associate with the rule, and a
link:AmazonCloudWatch/latest/events/ScheduledEvents.html["scheduling expression", type="documentation"]
that describes how often the rule is run.

*Imports*

[source,java]
----
import com.amazonaws.services.cloudwatchevents.AmazonCloudWatchEvents;
import com.amazonaws.services.cloudwatchevents.AmazonCloudWatchEventsClientBuilder;
import com.amazonaws.services.cloudwatchevents.model.PutRuleRequest;
import com.amazonaws.services.cloudwatchevents.model.PutRuleResult;
import com.amazonaws.services.cloudwatchevents.model.RuleState;
----

*Code*

[source,java]
----
final AmazonCloudWatchEvents cwe =
    AmazonCloudWatchEventsClientBuilder.defaultClient();

PutRuleRequest request = new PutRuleRequest()
    .withName(rule_name)
    .withRoleArn(role_arn)
    .withScheduleExpression("rate(5 minutes)")
    .withState(RuleState.ENABLED);

PutRuleResult response = cwe.putRule(request);
----


[[add-targets,add-targets.title]]
== Add Targets

Targets are the resources that are invoked when a rule is triggered. Example targets include
{EC2} instances, {LAM} functions, {AK} streams, {ECS} tasks, {SFN} state machines, and built-in
targets.

To add a target to a rule, call the AmazonCloudWatchEventsClient's `putTargets` method with a
link:sdk-for-java/v1/reference/com/amazonaws/services/cloudwatchevents/model/PutTargetsRequest.html["PutTargetsRequest", type="documentation"]
containing the rule to update and a list of targets to add to the rule.

*Imports*

[source,java]
----
import com.amazonaws.services.cloudwatchevents.AmazonCloudWatchEvents;
import com.amazonaws.services.cloudwatchevents.AmazonCloudWatchEventsClientBuilder;
import com.amazonaws.services.cloudwatchevents.model.PutTargetsRequest;
import com.amazonaws.services.cloudwatchevents.model.PutTargetsResult;
import com.amazonaws.services.cloudwatchevents.model.Target;
----

*Code*

[source,java]
----
final AmazonCloudWatchEvents cwe =
    AmazonCloudWatchEventsClientBuilder.defaultClient();

Target target = new Target()
    .withArn(function_arn)
    .withId(target_id);

PutTargetsRequest request = new PutTargetsRequest()
    .withTargets(target)
    .withRule(rule_name);

PutTargetsResult response = cwe.putTargets(request);
----


[[more-information,more-information.title]]
== More Information

* link:AmazonCloudWatch/latest/events/AddEventsPutEvents.html["Adding Events with PutEvents", type="documentation"] in the {guide-cwe-user}
* link:AmazonCloudWatch/latest/events/ScheduledEvents.html["Schedule Expressions for Rules", type="documentation"] in the {guide-cwe-user}
* link:AmazonCloudWatch/latest/events/EventTypes.html["Event Types for pass:q[[.shared\]`CW`] Events", type="documentation"] in the {guide-cwe-user}
* link:AmazonCloudWatch/latest/events/CloudWatchEventsandEventPatterns.html["Events and Event Patterns", type="documentation"] in the {guide-cwe-user}
* {https---docs-aws-amazon-com-AmazonCloudWatchEvents-latest-APIReference-API-PutEvents-html}[PutEvents] in the {guide-cwe-api}
* {https---docs-aws-amazon-com-AmazonCloudWatchEvents-latest-APIReference-API-PutTargets-html}[PutTargets] in the {guide-cwe-api}
* {https---docs-aws-amazon-com-AmazonCloudWatchEvents-latest-APIReference-API-PutRule-html}[PutRule] in the {guide-cwe-api}
