//!!NODE_ROOT <section>
include::../../includes.txt[]
:https---github-com-awsdocs-aws-doc-sdk-examples-blob-master-java-example-code-pinpoint-src-main-java-com-example-pinpoint-CreateApp-java: {url-awsdocs-github}aws-doc-sdk-examples/blob/master/java/example_code/pinpoint/src/main/java/com/example/pinpoint/CreateApp.java

[."topic"]
[[examples-pinpoint-create-campaign,examples-pinpoint-create-campaign.title]]
= [[creating-campaigns-in-pinlong, Creating Campaigns in {PINlong}]]Creating Campaigns in {PINlong}
:info_doctype: section
:info_title: Creating Campaigns in {PINlong}
:info_abstract: How to create a campaign in Amazon pinpoint.
:info_keywordset: sdk-javacode examplesamazon pinpoint campaign

[abstract]
--
How to create a campaign in Amazon pinpoint.
--

You can use campaigns to help increase engagement between your app and your users. You can create a campaign to reach out to a particular segment of your users with tailored messages or special promotions. This example demonstrates how to create a new standard campaign that sends a custom push notification to a specified segment.

[[create-a-campaign,create-a-campaign.title]]
== Create a Campaign

Before creating a new campaign, you must define a  link:sdk-for-java/v1/reference/com/amazonaws/services/pinpoint/model/Schedule.html["Schedule", type="documentation"] and a link:sdk-for-java/v1/reference/com/amazonaws/services/pinpoint/model/Message.html["Message", type="documentation"] and set these values in a link:sdk-for-java/v1/reference/com/amazonaws/services/pinpoint/model/WriteCampaignRequest.html["WriteCampaignRequest", type="documentation"] object.

*Imports*

[source,java]
----
import com.amazonaws.services.pinpoint.AmazonPinpoint;
import com.amazonaws.services.pinpoint.AmazonPinpointClientBuilder;
import com.amazonaws.services.pinpoint.model.CreateCampaignRequest;
import com.amazonaws.services.pinpoint.model.CreateCampaignResult;
import com.amazonaws.services.pinpoint.model.Action;
import com.amazonaws.services.pinpoint.model.CampaignResponse;
import com.amazonaws.services.pinpoint.model.Message;
import com.amazonaws.services.pinpoint.model.MessageConfiguration;
import com.amazonaws.services.pinpoint.model.Schedule;
import com.amazonaws.services.pinpoint.model.WriteCampaignRequest;
----

*Code*

[source,java]
----
Schedule schedule = new Schedule()
        .withStartTime("IMMEDIATE");

Message defaultMessage = new Message()
        .withAction(Action.OPEN_APP)
        .withBody("My message body.")
        .withTitle("My message title.");

MessageConfiguration messageConfiguration = new MessageConfiguration()
        .withDefaultMessage(defaultMessage);

WriteCampaignRequest request = new WriteCampaignRequest()
        .withDescription("My description.")
        .withSchedule(schedule)
        .withSegmentId(segmentId)
        .withName("MyCampaign")
        .withMessageConfiguration(messageConfiguration);
----

Then create a new campaign in {PINlong} by providing the  link:sdk-for-java/v1/reference/com/amazonaws/services/pinpoint/model/WriteCampaignRequest.html["WriteCampaignRequest", type="documentation"] with the campaign configuration to a link:sdk-for-java/v1/reference/com/amazonaws/CreateCampaignRequest.html["CreateCampaignRequest", type="documentation"] object. Finally, pass the CreateCampaignRequest object to the AmazonPinpointClient's `createCampaign` method.

*Code*

[source,java]
----
CreateCampaignRequest createCampaignRequest = new CreateCampaignRequest()
        .withApplicationId(appId).withWriteCampaignRequest(request);

CreateCampaignResult result = client.createCampaign(createCampaignRequest);
----

See the  {https---github-com-awsdocs-aws-doc-sdk-examples-blob-master-java-example-code-pinpoint-src-main-java-com-example-pinpoint-CreateApp-java}[complete example] on GitHub.

[[more-information,more-information.title]]
== More Information

* link:pinpoint/latest/userguide/campaigns.html["pass:q[[.shared\]`PINlong`] Campaigns", type="documentation"] in the {guide-pin-ug}
* {url-pin-dg}campaigns.html[Creating Campaigns] in the {guide-pin-dg}
* {url-pin-api}rest-api-campaigns.html[Campaigns] in the {guide-pin-api}
* {url-pin-api}rest-api-campaign.html[Campaign] in the {guide-pin-api}
* {url-pin-api}rest-api-campaign-activities.html[Campaign Activities] in the {guide-pin-api}
* {url-pin-api}rest-api-campaign-versions.html[Campaign Versions] in the {guide-pin-api}
* {url-pin-api}rest-api-campaign-version.html[Campaign Version] in the {guide-pin-api}
