//!!NODE_ROOT <section>
include::../../includes.txt[]
[."topic"]
[[examples-s3-transfermanager,examples-s3-transfermanager.title]]
= [[using-transfermanager-for-s3-operations, Using TransferManager for S3 Operations]]Using TransferManager for {S3} Operations
:info_doctype: section
:info_title: Using TransferManager for {S3} Operations
:info_abstract: How to use the {sdk-java}'s TransferManager class to upload, download, and copy files and directories using {S3}.
:info_keywordset: sdk-javacode examples TransferManager {S3} transfer operations

[abstract]
--
How to use the {sdk-java}'s TransferManager class to upload, download, and copy files and
directories using {S3}.
--

You can use the {sdk-java} TransferManager class to reliably transfer files from the local
environment to {S3} and to copy objects from one S3 location to another.  `TransferManager` can
get the progress of a transfer and pause or resume uploads and downloads.

[NOTE]
====

Best Practice

We recommend that you enable the
{url-s3-api}RESTBucketPUTlifecycle.html[AbortIncompleteMultipartUpload]
lifecycle rule on your {S3} buckets.

This rule directs {S3} to abort multipart uploads that don't complete within a specified number
of days after being initiated. When the set time limit is exceeded, {S3} aborts the upload and
then deletes the incomplete upload data.

For more information, see
{url-s3-ug}lifecycle-configuration-bucket-with-versioning.html[Lifecycle Configuration for a Bucket with Versioning]
in the {guide-s3-ug}.

====

[NOTE]
====

These code examples assume that you understand the material in
xref:basics[Using the {sdk-java},linkend=basics]
and have configured default {AWS} credentials using the information in
xref:setup-credentials[Set up {AWS} Credentials and Region for Development,linkend=setup-credentials].

====

[[transfermanager-uploading,transfermanager-uploading.title]]
== Upload Files and Directories

TransferManager can upload files, file lists, and directories to any {S3} buckets that you've
xref:create-bucket[previously created,linkend=create-bucket].

[.topiclist-abbrev]
[[Topic List]]


[[transfermanager-upload-file,transfermanager-upload-file.title]]
=== Upload a Single File

Call TransferManager's  `upload` method, providing an {S3} bucket name, a key (object) name, and
a standard Java {java-oracle-file}[File] object that represents the file to upload.

*Imports*

[source,java]
----

import com.amazonaws.AmazonServiceException;
import com.amazonaws.services.s3.transfer.MultipleFileUpload;
import com.amazonaws.services.s3.transfer.TransferManager;
import com.amazonaws.services.s3.transfer.TransferManagerBuilder;
import com.amazonaws.services.s3.transfer.Upload;

import java.io.File;
import java.util.ArrayList;
import java.util.Arrays;
----

*Code*

[source,java]
----
File f = new File(file_path);
TransferManager xfer_mgr = TransferManagerBuilder.standard().build();
try {
    Upload xfer = xfer_mgr.upload(bucket_name, key_name, f);
    // loop with Transfer.isDone()
    XferMgrProgress.showTransferProgress(xfer);
    //  or block with Transfer.waitForCompletion()
    XferMgrProgress.waitForCompletion(xfer);
} catch (AmazonServiceException e) {
    System.err.println(e.getErrorMessage());
    System.exit(1);
}
xfer_mgr.shutdownNow();
----

The  `upload` method returns __immediately__, providing an `Upload` object to use to check the
transfer state or to wait for it to complete.

See
xref:transfermanager-wait-for-completion[Wait for a Transfer to Complete,linkend=transfermanager-wait-for-completion]
for information about using `waitForCompletion` to successfully complete a transfer before
calling TransferManager's `shutdownNow` method. While waiting for the transfer to complete, you
can poll or listen for updates about its status and progress. See
xref:transfermanager-get-status-and-progress[Get Transfer Status and Progress,linkend=transfermanager-get-status-and-progress]
for more information.

See the
{url-awsdocs-github}aws-doc-sdk-examples/blob/master/java/example_code/s3/src/main/java/aws/example/s3/XferMgrUpload.java[complete example]
on GitHub.

[[transfermanager-upload-file-list,transfermanager-upload-file-list.title]]
=== Upload a List of Files

To upload multiple files in one operation, call the TransferManager``uploadFileList`` method,
providing the following:



* An {S3} bucket name
* A _key prefix_ to prepend to the names of the created objects (the path within the bucket in which to place the objects)
* A {java-oracle-file}[File] object that represents the relative directory from which to create file paths
* A {java-oracle-list}[List] object containing a set of {java-oracle-file}[File] objects to upload

*Imports*

[source,java]
----

import com.amazonaws.AmazonServiceException;
import com.amazonaws.services.s3.transfer.MultipleFileUpload;
import com.amazonaws.services.s3.transfer.TransferManager;
import com.amazonaws.services.s3.transfer.TransferManagerBuilder;
import com.amazonaws.services.s3.transfer.Upload;

import java.io.File;
import java.util.ArrayList;
import java.util.Arrays;
----

*Code*

[source,java]
----
ArrayList<File> files = new ArrayList<File>();
for (String path : file_paths) {
    files.add(new File(path));
}

TransferManager xfer_mgr = TransferManagerBuilder.standard().build();
try {
    MultipleFileUpload xfer = xfer_mgr.uploadFileList(bucket_name,
            key_prefix, new File("."), files);
    // loop with Transfer.isDone()
    XferMgrProgress.showTransferProgress(xfer);
    // or block with Transfer.waitForCompletion()
    XferMgrProgress.waitForCompletion(xfer);
} catch (AmazonServiceException e) {
    System.err.println(e.getErrorMessage());
    System.exit(1);
}
xfer_mgr.shutdownNow();
----

See
xref:transfermanager-wait-for-completion[Wait for a Transfer to Complete,linkend=transfermanager-wait-for-completion]
for information about using `waitForCompletion` to successfully complete a transfer before
calling TransferManager's `shutdownNow` method. While waiting for the transfer to complete, you
can poll or listen for updates about its status and progress. See
xref:transfermanager-get-status-and-progress[Get Transfer Status and Progress,linkend=transfermanager-get-status-and-progress]
for more information.

The
link:sdk-for-java/v1/reference/com/amazonaws/services/s3/transfer/MultipleFileUpload.html["MultipleFileUpload", type="documentation"]
object returned by `uploadFileList` can be used to query the transfer state or progress. See
xref:transfermanager-get-progress-polling[Poll the Current Progress of a Transfer,linkend=transfermanager-get-progress-polling]
and
xref:transfermanager-progress-listener[Get Transfer Progress with a ProgressListener,linkend=transfermanager-progress-listener]
for more information.

You can also use ``MultipleFileUpload``'s `getSubTransfers` method to get the individual
`Upload` objects for each file being transferred. For more information, see
xref:transfermanager-get-subtransfer-progress[Get the Progress of Subtransfers,linkend=transfermanager-get-subtransfer-progress].

See the
{url-awsdocs-github}aws-doc-sdk-examples/blob/master/java/example_code/s3/src/main/java/aws/example/s3/XferMgrUpload.java[complete example]
on GitHub.

[[transfermanager-upload-directory,transfermanager-upload-directory.title]]
=== Upload a Directory

You can use TransferManager's  `uploadDirectory` method to upload an entire directory of files,
with the option to copy files in subdirectories recursively. You provide an {S3} bucket name, an
S3 key prefix, a {java-oracle-file}[File] object representing the local directory to copy, and a
`boolean` value indicating whether you want to copy subdirectories recursively (__true__ or
__false__).

*Imports*

[source,java]
----

import com.amazonaws.AmazonServiceException;
import com.amazonaws.services.s3.transfer.MultipleFileUpload;
import com.amazonaws.services.s3.transfer.TransferManager;
import com.amazonaws.services.s3.transfer.TransferManagerBuilder;
import com.amazonaws.services.s3.transfer.Upload;

import java.io.File;
import java.util.ArrayList;
import java.util.Arrays;
----

*Code*

[source,java]
----
TransferManager xfer_mgr = TransferManagerBuilder.standard().build();
try {
    MultipleFileUpload xfer = xfer_mgr.uploadDirectory(bucket_name,
            key_prefix, new File(dir_path), recursive);
    // loop with Transfer.isDone()
    XferMgrProgress.showTransferProgress(xfer);
    // or block with Transfer.waitForCompletion()
    XferMgrProgress.waitForCompletion(xfer);
} catch (AmazonServiceException e) {
    System.err.println(e.getErrorMessage());
    System.exit(1);
}
xfer_mgr.shutdownNow();
----

See
xref:transfermanager-wait-for-completion[Wait for a Transfer to Complete,linkend=transfermanager-wait-for-completion]
for information about using `waitForCompletion` to successfully complete a transfer before
calling TransferManager's `shutdownNow` method. While waiting for the transfer to complete, you
can poll or listen for updates about its status and progress. See
xref:transfermanager-get-status-and-progress[Get Transfer Status and Progress,linkend=transfermanager-get-status-and-progress]
for more information.

The
link:sdk-for-java/v1/reference/com/amazonaws/services/s3/transfer/MultipleFileUpload.html["MultipleFileUpload", type="documentation"]
object returned by `uploadFileList` can be used to query the transfer state or progress. See
xref:transfermanager-get-progress-polling[Poll the Current Progress of a Transfer,linkend=transfermanager-get-progress-polling]
and
xref:transfermanager-progress-listener[Get Transfer Progress with a ProgressListener,linkend=transfermanager-progress-listener]
for more information.

You can also use ``MultipleFileUpload``'s `getSubTransfers` method to get the individual
`Upload` objects for each file being transferred. For more information, see
xref:transfermanager-get-subtransfer-progress[Get the Progress of Subtransfers,linkend=transfermanager-get-subtransfer-progress].

See the
{url-awsdocs-github}aws-doc-sdk-examples/blob/master/java/example_code/s3/src/main/java/aws/example/s3/XferMgrUpload.java[complete example]
on GitHub.

[[transfermanager-downloading,transfermanager-downloading.title]]
== Download Files or Directories

Use the TransferManager class to download either a single file ({S3} object) or a directory (an
{S3} bucket name followed by an object prefix) from {S3}.

[.topiclist-abbrev]
[[Topic List]]


[[transfermanager-download-file,transfermanager-download-file.title]]
=== Download a Single File

Use the TransferManager's  `download` method, providing the {S3} bucket name containing the
object you want to download, the key (object) name, and a
{java-oracle-file}[File]
object that represents the file to create on your local system.

*Imports*

[source,java]
----

import com.amazonaws.AmazonServiceException;
import com.amazonaws.services.s3.transfer.Download;
import com.amazonaws.services.s3.transfer.MultipleFileDownload;
import com.amazonaws.services.s3.transfer.TransferManager;
import com.amazonaws.services.s3.transfer.TransferManagerBuilder;

import java.io.File;
----

*Code*

[source,java]
----
File f = new File(file_path);
TransferManager xfer_mgr = TransferManagerBuilder.standard().build();
try {
    Download xfer = xfer_mgr.download(bucket_name, key_name, f);
    // loop with Transfer.isDone()
    XferMgrProgress.showTransferProgress(xfer);
    // or block with Transfer.waitForCompletion()
    XferMgrProgress.waitForCompletion(xfer);
} catch (AmazonServiceException e) {
    System.err.println(e.getErrorMessage());
    System.exit(1);
}
xfer_mgr.shutdownNow();
----

See
xref:transfermanager-wait-for-completion[Wait for a Transfer to Complete,linkend=transfermanager-wait-for-completion]
for information about using `waitForCompletion` to successfully complete a transfer before
calling TransferManager's `shutdownNow` method. While waiting for the transfer to complete, you
can poll or listen for updates about its status and progress. See
xref:transfermanager-get-status-and-progress[Get Transfer Status and Progress,linkend=transfermanager-get-status-and-progress]
for more information.

See the
{url-awsdocs-github}aws-doc-sdk-examples/blob/master/java/example_code/s3/src/main/java/aws/example/s3/XferMgrDownload.java[complete example]
on GitHub.

[[tranfermanager-download-directory,tranfermanager-download-directory.title]]
=== Download a Directory

To download a set of files that share a common key prefix (analogous to a directory on a file
system) from {S3}, use the TransferManager``downloadDirectory`` method. The method takes the {S3}
bucket name containing the objects you want to download, the object prefix shared by all of the
objects, and a
{java-oracle-file}[File]
object that represents the directory to download the files into on your local system. If the
named directory doesn't exist yet, it will be created.

*Imports*

[source,java]
----

import com.amazonaws.AmazonServiceException;
import com.amazonaws.services.s3.transfer.Download;
import com.amazonaws.services.s3.transfer.MultipleFileDownload;
import com.amazonaws.services.s3.transfer.TransferManager;
import com.amazonaws.services.s3.transfer.TransferManagerBuilder;

import java.io.File;
----

*Code*

[source,java]
----
TransferManager xfer_mgr = TransferManagerBuilder.standard().build();

try {
    MultipleFileDownload xfer = xfer_mgr.downloadDirectory(
            bucket_name, key_prefix, new File(dir_path));
    // loop with Transfer.isDone()
    XferMgrProgress.showTransferProgress(xfer);
    // or block with Transfer.waitForCompletion()
    XferMgrProgress.waitForCompletion(xfer);
} catch (AmazonServiceException e) {
    System.err.println(e.getErrorMessage());
    System.exit(1);
}
xfer_mgr.shutdownNow();
----

See
xref:transfermanager-wait-for-completion[Wait for a Transfer to Complete,linkend=transfermanager-wait-for-completion]
for information about using `waitForCompletion` to successfully complete a transfer before
calling TransferManager's `shutdownNow` method. While waiting for the transfer to complete, you
can poll or listen for updates about its status and progress. See
xref:transfermanager-get-status-and-progress[Get Transfer Status and Progress,linkend=transfermanager-get-status-and-progress]
for more information.

See the
{url-awsdocs-github}aws-doc-sdk-examples/blob/master/java/example_code/s3/src/main/java/aws/example/s3/XferMgrDownload.java[complete example]
on GitHub.

[[transfermanager-copy-object,transfermanager-copy-object.title]]
== Copy Objects

To copy an object from one S3 bucket to another, use the TransferManager``copy`` method.

*Imports*

[source,java]
----

import com.amazonaws.AmazonServiceException;
import com.amazonaws.services.s3.transfer.Copy;
import com.amazonaws.services.s3.transfer.TransferManager;
import com.amazonaws.services.s3.transfer.TransferManagerBuilder;
----

*Code*

[source,java]
----
System.out.println("Copying s3 object: " + from_key);
System.out.println("      from bucket: " + from_bucket);
System.out.println("     to s3 object: " + to_key);
System.out.println("        in bucket: " + to_bucket);

TransferManager xfer_mgr = TransferManagerBuilder.standard().build();
try {
    Copy xfer = xfer_mgr.copy(from_bucket, from_key, to_bucket, to_key);
    // loop with Transfer.isDone()
    XferMgrProgress.showTransferProgress(xfer);
    // or block with Transfer.waitForCompletion()
    XferMgrProgress.waitForCompletion(xfer);
} catch (AmazonServiceException e) {
    System.err.println(e.getErrorMessage());
    System.exit(1);
}
xfer_mgr.shutdownNow();
----

See the
{url-awsdocs-github}aws-doc-sdk-examples/blob/master/java/example_code/s3/src/main/java/aws/example/s3/XferMgrCopy.java[complete example]
on GitHub.

[[transfermanager-wait-for-completion,transfermanager-wait-for-completion.title]]
== Wait for a Transfer to Complete

If your application (or thread) can block until the transfer completes, you can use the
link:sdk-for-java/v1/reference/com/amazonaws/services/s3/transfer/Transfer.html["Transfer", type="documentation"]
interface's `waitForCompletion` method to block until the transfer is complete or an exception
occurs.

[source,java]
----
try {
    xfer.waitForCompletion();
} catch (AmazonServiceException e) {
    System.err.println("Amazon service error: " + e.getMessage());
    System.exit(1);
} catch (AmazonClientException e) {
    System.err.println("Amazon client error: " + e.getMessage());
    System.exit(1);
} catch (InterruptedException e) {
    System.err.println("Transfer interrupted: " + e.getMessage());
    System.exit(1);
}
----

You get progress of transfers if you poll for events  _before_ calling ``waitForCompletion``,
implement a polling mechanism on a separate thread, or receive progress updates asynchronously
using a
link:sdk-for-java/v1/reference/com/amazonaws/event/ProgressListener.html["ProgressListener", type="documentation"].

See the
{url-awsdocs-github}aws-doc-sdk-examples/blob/master/java/example_code/s3/src/main/java/aws/example/s3/XferMgrProgress.java[complete example]
on GitHub.

[[transfermanager-get-status-and-progress,transfermanager-get-status-and-progress.title]]
== Get Transfer Status and Progress

Each of the classes returned by the TransferManager``upload*``, ``download*``, and `copy` methods
returns an instance of one of the following classes, depending on whether it's a single-file or
multiple-file operation.

.{zwsp}
[cols="1,1", options="header"]
|===
| Class
| Returned by

|

link:sdk-for-java/v1/reference/com/amazonaws/services/s3/transfer/Copy.html["Copy", type="documentation"]
|

`copy`

|

link:sdk-for-java/v1/reference/com/amazonaws/services/s3/transfer/Download.html["Download", type="documentation"]
|

`download`

|

link:sdk-for-java/v1/reference/com/amazonaws/services/s3/transfer/MultipleFileDownload.html["MultipleFileDownload", type="documentation"]
|

`downloadDirectory`

|

link:sdk-for-java/v1/reference/com/amazonaws/services/s3/transfer/Upload.html["Upload", type="documentation"]
|

`upload`

|

link:sdk-for-java/v1/reference/com/amazonaws/services/s3/transfer/MultipleFileUpload.html["MultipleFileUpload", type="documentation"]
|

``uploadFileList``, `uploadDirectory`
|===

All of these classes implement the
link:sdk-for-java/v1/reference/com/amazonaws/services/s3/transfer/Transfer.html["Transfer", type="documentation"]
interface. `Transfer` provides useful methods to get the progress of a transfer, pause or resume
the transfer, and get the transfer's current or final status.

[.topiclist-abbrev]
[[Topic List]]


[[transfermanager-get-progress-polling,transfermanager-get-progress-polling.title]]
=== Poll the Current Progress of a Transfer

This loop prints the progress of a transfer, examines its current progress while running and,
when complete, prints its final state.

*Imports*

[source,java]
----

import com.amazonaws.AmazonClientException;
import com.amazonaws.AmazonServiceException;
import com.amazonaws.event.ProgressEvent;
import com.amazonaws.event.ProgressListener;
import com.amazonaws.services.s3.transfer.*;
import com.amazonaws.services.s3.transfer.Transfer.TransferState;

import java.io.File;
import java.util.ArrayList;
import java.util.Collection;
----

*Code*

[source,java]
----
// print the transfer's human-readable description
System.out.println(xfer.getDescription());
// print an empty progress bar...
printProgressBar(0.0);
// update the progress bar while the xfer is ongoing.
do {
    try {
        Thread.sleep(100);
    } catch (InterruptedException e) {
        return;
    }
    // Note: so_far and total aren't used, they're just for
    // documentation purposes.
    TransferProgress progress = xfer.getProgress();
    long so_far = progress.getBytesTransferred();
    long total = progress.getTotalBytesToTransfer();
    double pct = progress.getPercentTransferred();
    eraseProgressBar();
    printProgressBar(pct);
} while (xfer.isDone() == false);
// print the final state of the transfer.
TransferState xfer_state = xfer.getState();
System.out.println(": " + xfer_state);
----

See the
{url-awsdocs-github}aws-doc-sdk-examples/blob/master/java/example_code/s3/src/main/java/aws/example/s3/XferMgrProgress.java[complete example]
on GitHub.

[[transfermanager-progress-listener,transfermanager-progress-listener.title]]
=== Get Transfer Progress with a ProgressListener

You can attach a
link:sdk-for-java/v1/reference/com/amazonaws/event/ProgressListener.html["ProgressListener", type="documentation"]
to any transfer by using the
link:sdk-for-java/v1/reference/com/amazonaws/services/s3/transfer/Transfer.html["Transfer", type="documentation"]
interface's `addProgressListener` method.

A
link:sdk-for-java/v1/reference/com/amazonaws/event/ProgressListener.html["ProgressListener", type="documentation"]
requires only one method, ``progressChanged``, which takes a
link:sdk-for-java/v1/reference/com/amazonaws/event/ProgressEvent.html["ProgressEvent", type="documentation"]
object. You can use the object to get the total bytes of the operation by calling its `getBytes`
method, and the number of bytes transferred so far by calling ``getBytesTransferred``.

*Imports*

[source,java]
----

import com.amazonaws.AmazonClientException;
import com.amazonaws.AmazonServiceException;
import com.amazonaws.event.ProgressEvent;
import com.amazonaws.event.ProgressListener;
import com.amazonaws.services.s3.transfer.*;
import com.amazonaws.services.s3.transfer.Transfer.TransferState;

import java.io.File;
import java.util.ArrayList;
import java.util.Collection;
----

*Code*

[source,java]
----
File f = new File(file_path);
TransferManager xfer_mgr = TransferManagerBuilder.standard().build();
try {
    Upload u = xfer_mgr.upload(bucket_name, key_name, f);
    // print an empty progress bar...
    printProgressBar(0.0);
    u.addProgressListener(new ProgressListener() {
        public void progressChanged(ProgressEvent e) {
            double pct = e.getBytesTransferred() * 100.0 / e.getBytes();
            eraseProgressBar();
            printProgressBar(pct);
        }
    });
    // block with Transfer.waitForCompletion()
    XferMgrProgress.waitForCompletion(u);
    // print the final state of the transfer.
    TransferState xfer_state = u.getState();
    System.out.println(": " + xfer_state);
} catch (AmazonServiceException e) {
    System.err.println(e.getErrorMessage());
    System.exit(1);
}
xfer_mgr.shutdownNow();
----

See the
{url-awsdocs-github}aws-doc-sdk-examples/blob/master/java/example_code/s3/src/main/java/aws/example/s3/XferMgrProgress.java[complete example]
on GitHub.

[[transfermanager-get-subtransfer-progress,transfermanager-get-subtransfer-progress.title]]
=== Get the Progress of Subtransfers

The  link:sdk-for-java/v1/reference/com/amazonaws/services/s3/transfer/MultipleFileUpload.html["MultipleFileUpload", type="documentation"]
class can return information about its subtransfers by calling its `getSubTransfers` method. It
returns an unmodifiable {java-oracle-collection}[Collection] of
link:sdk-for-java/v1/reference/com/amazonaws/services/s3/transfer/Upload.html["Upload", type="documentation"]
objects that provide the individual transfer status and progress of each sub-transfer.

*Imports*

[source,java]
----

import com.amazonaws.AmazonClientException;
import com.amazonaws.AmazonServiceException;
import com.amazonaws.event.ProgressEvent;
import com.amazonaws.event.ProgressListener;
import com.amazonaws.services.s3.transfer.*;
import com.amazonaws.services.s3.transfer.Transfer.TransferState;

import java.io.File;
import java.util.ArrayList;
import java.util.Collection;
----

*Code*

[source,java]
----
Collection<? extends Upload> sub_xfers = new ArrayList<Upload>();
sub_xfers = multi_upload.getSubTransfers();

do {
    System.out.println("\nSubtransfer progress:\n");
    for (Upload u : sub_xfers) {
        System.out.println("  " + u.getDescription());
        if (u.isDone()) {
            TransferState xfer_state = u.getState();
            System.out.println("  " + xfer_state);
        } else {
            TransferProgress progress = u.getProgress();
            double pct = progress.getPercentTransferred();
            printProgressBar(pct);
            System.out.println();
        }
    }

    // wait a bit before the next update.
    try {
        Thread.sleep(200);
    } catch (InterruptedException e) {
        return;
    }
} while (multi_upload.isDone() == false);
// print the final state of the transfer.
TransferState xfer_state = multi_upload.getState();
System.out.println("\nMultipleFileUpload " + xfer_state);
----

See the
{url-awsdocs-github}aws-doc-sdk-examples/blob/master/java/example_code/s3/src/main/java/aws/example/s3/XferMgrProgress.java[complete example]
on GitHub.

[[transfermanager-see-also,transfermanager-see-also.title]]
== More Info

* {url-s3-dev}UsingMetadata.html[Object Keys] in the {guide-s3-dev}
