//!!NODE_ROOT <section>
include::../../includes.txt[]
[."topic"]
[[examples-iam,examples-iam.title]]
= [[iam-examples-using-the-sdk-java, IAM Examples Using the SDK for Java]]IAM Examples Using the {sdk-java}
:info_doctype: section
:info_title: IAM Examples Using the {sdk-java}
:info_titleabbrev: {IAMlong} (IAM) Examples
:info_abstract: Programming {IAMlong} using the {sdk-java}
:info_keywordset: sdk-javacode examplesIAM

[abstract]
--
Programming {IAMlong} using the {sdk-java}
--

This section provides examples of programming link:iam/["IAM", type="marketing"] by using the link:sdk-for-java/["pass:q[[.shared\]`Javalong`]", type="marketing"].

{IAMlong} (IAM) enables you to securely control access to {AWS-services} and resources for your
users. Using IAM, you can create and manage {AWS} users and groups, and use permissions to allow
and deny their access to {AWS} resources. For a complete guide to IAM, visit the {link-iam-user}.

[NOTE]
====

The examples include only the code needed to demonstrate each technique. The {url-awsdocs-github}aws-doc-sdk-examples/tree/master/java[complete example code is available on GitHub]. From there, you can download a single source file or clone the repository locally to get all the examples to build and run.

====

[.topiclist-abbrev]
[[Topic List]]


include::examples-iam-access-keys.adoc[leveloffset=+1]


include::examples-iam-users.adoc[leveloffset=+1]


include::examples-iam-account-aliases.adoc[leveloffset=+1]


include::examples-iam-policies.adoc[leveloffset=+1]


include::examples-iam-server-certificates.adoc[leveloffset=+1]
