//!!NODE_ROOT <section>
include::../../includes.txt[]
[."topic"]
[[examples-dynamodb-items,examples-dynamodb-items.title]]
= [[working-with-items-in-ddb, Working with Items in DynamoDB]]Working with Items in {DDB}
:info_doctype: section
:info_title: Working with Items in {DDB}
:info_abstract: How to retrieve (get), add, and update items in {DDBlong} tables.
:info_keywordset: sdk-javacode examples items from {DDB} tables

[abstract]
--
How to retrieve (get), add, and update items in {DDBlong} tables.
--

In {DDB}, an item is a collection of  __attributes__, each of which has a _name_ and a
__value__. An attribute value can be a scalar, set, or document type. For more information, see
{url-ddb-dev}HowItWorks.NamingRulesDataTypes.html[Naming Rules and Data Types] in the {guide-ddb-dev}.

[[dynamodb-get-item,dynamodb-get-item.title]]
== Retrieve (Get) an Item from a Table

Call the AmazonDynamoDB's  `getItem` method and pass it a
link:sdk-for-java/v1/reference/com/amazonaws/services/dynamodbv2/model/GetItemRequest.html["GetItemRequest", type="documentation"]
object with the table name and primary key value of the item you want. It returns a
link:sdk-for-java/v1/reference/com/amazonaws/services/dynamodbv2/model/GetItemResult.html["GetItemResult", type="documentation"] object.

You can use the returned `GetItemResult` object's `getItem()` method to retrieve a
{java-oracle-map}[Map] of key (String) and value
(link:sdk-for-java/v1/reference/com/amazonaws/services/dynamodbv2/model/AttributeValue.html["AttributeValue", type="documentation"]) pairs
that are associated with the item.

*Imports*

[source,java]
----
import com.amazonaws.AmazonServiceException;
import com.amazonaws.services.dynamodbv2.AmazonDynamoDB;
import com.amazonaws.services.dynamodbv2.AmazonDynamoDBClientBuilder;
import com.amazonaws.services.dynamodbv2.model.AttributeValue;
import com.amazonaws.services.dynamodbv2.model.GetItemRequest;
import java.util.HashMap;
import java.util.Map;
----

*Code*

[source,java]
----

HashMap<String,AttributeValue> key_to_get =
    new HashMap<String,AttributeValue>();

key_to_get.put("DATABASE_NAME", new AttributeValue(name));

GetItemRequest request = null;
if (projection_expression != null) {
    request = new GetItemRequest()
        .withKey(key_to_get)
        .withTableName(table_name)
        .withProjectionExpression(projection_expression);
} else {
    request = new GetItemRequest()
        .withKey(key_to_get)
        .withTableName(table_name);
}

final AmazonDynamoDB ddb = AmazonDynamoDBClientBuilder.defaultClient();

try {
    Map<String,AttributeValue> returned_item =
       ddb.getItem(request).getItem();
    if (returned_item != null) {
        Set<String> keys = returned_item.keySet();
        for (String key : keys) {
            System.out.format("%s: %s\n",
                    key, returned_item.get(key).toString());
        }
    } else {
        System.out.format("No item found with the key %s!\n", name);
    }
} catch (AmazonServiceException e) {
    System.err.println(e.getErrorMessage());
    System.exit(1);
----

See the
{url-awsdocs-github}aws-doc-sdk-examples/blob/master/java/example_code/dynamodb/src/main/java/aws/example/dynamodb/GetItem.java[complete example]
on GitHub.

[[dynamodb-add-item,dynamodb-add-item.title]]
== Add a New Item to a Table

Create a
{java-oracle-map}[Map] of key-value pairs that represent the item's attributes. These must
include values for the table's primary key fields. If the item identified by the primary key
already exists, its fields are _updated_ by the request.

[NOTE]
====

If the named table doesn't exist for your account and region, a
link:sdk-for-java/v1/reference/com/amazonaws/services/dynamodbv2/model/ResourceNotFoundException.html["ResourceNotFoundException", type="documentation"]
is thrown.

====

*Imports*

[source,java]
----
import com.amazonaws.AmazonServiceException;
import com.amazonaws.services.dynamodbv2.AmazonDynamoDB;
import com.amazonaws.services.dynamodbv2.AmazonDynamoDBClientBuilder;
import com.amazonaws.services.dynamodbv2.model.AttributeValue;
import com.amazonaws.services.dynamodbv2.model.ResourceNotFoundException;
import java.util.ArrayList;
----

*Code*

[source,java]
----

HashMap<String,AttributeValue> item_values =
    new HashMap<String,AttributeValue>();

item_values.put("Name", new AttributeValue(name));

for (String[] field : extra_fields) {
    item_values.put(field[0], new AttributeValue(field[1]));
}

final AmazonDynamoDB ddb = AmazonDynamoDBClientBuilder.defaultClient();

try {
    ddb.putItem(table_name, item_values);
} catch (ResourceNotFoundException e) {
    System.err.format("Error: The table \"%s\" can't be found.\n", table_name);
    System.err.println("Be sure that it exists and that you've typed its name correctly!");
    System.exit(1);
} catch (AmazonServiceException e) {
    System.err.println(e.getMessage());
    System.exit(1);
----

See the
{url-awsdocs-github}aws-doc-sdk-examples/blob/master/java/example_code/dynamodb/src/main/java/aws/example/dynamodb/PutItem.java[complete example]
on GitHub.

[[dynamodb-update-item,dynamodb-update-item.title]]
== Update an Existing Item in a Table

You can update an attribute for an item that already exists in a table by using the
AmazonDynamoDB's  `updateItem` method, providing a table name, primary key value, and a map of
fields to update.

[NOTE]
====

If the named table doesn't exist for your account and region, or if the item identified by the
primary key you passed in doesn't exist, a
link:sdk-for-java/v1/reference/com/amazonaws/services/dynamodbv2/model/ResourceNotFoundException.html["ResourceNotFoundException", type="documentation"]
is thrown.

====

*Imports*

[source,java]
----
import com.amazonaws.AmazonServiceException;
import com.amazonaws.services.dynamodbv2.AmazonDynamoDB;
import com.amazonaws.services.dynamodbv2.AmazonDynamoDBClientBuilder;
import com.amazonaws.services.dynamodbv2.model.AttributeAction;
import com.amazonaws.services.dynamodbv2.model.AttributeValue;
import com.amazonaws.services.dynamodbv2.model.AttributeValueUpdate;
import com.amazonaws.services.dynamodbv2.model.ResourceNotFoundException;
import java.util.ArrayList;
----

*Code*

[source,java]
----

HashMap<String,AttributeValue> item_key =
   new HashMap<String,AttributeValue>();

item_key.put("Name", new AttributeValue(name));

HashMap<String,AttributeValueUpdate> updated_values =
    new HashMap<String,AttributeValueUpdate>();

for (String[] field : extra_fields) {
    updated_values.put(field[0], new AttributeValueUpdate(
                new AttributeValue(field[1]), AttributeAction.PUT));
}

final AmazonDynamoDB ddb = AmazonDynamoDBClientBuilder.defaultClient();

try {
    ddb.updateItem(table_name, item_key, updated_values);
} catch (ResourceNotFoundException e) {
    System.err.println(e.getMessage());
    System.exit(1);
} catch (AmazonServiceException e) {
    System.err.println(e.getMessage());
    System.exit(1);
----

See the
{url-awsdocs-github}aws-doc-sdk-examples/blob/master/java/example_code/dynamodb/src/main/java/aws/example/dynamodb/UpdateItem.java[complete example]
on GitHub.

[[use-the-dynamodbmapper-class,use-the-dynamodbmapper-class.title]]
== Use the DynamoDBMapper class

The
link:sdk-for-java/["pass:q[[.shared\]`Javalong`]", type="marketing"]
provides a
link:sdk-for-java/v1/reference/com/amazonaws/services/dynamodbv2/datamodeling/DynamoDBMapper.html["DynamoDBMapper", type="documentation"]
class, allowing you to map your client-side classes to {DDBlong} tables. To use the
link:sdk-for-java/v1/reference/com/amazonaws/services/dynamodbv2/datamodeling/DynamoDBMapper.html["DynamoDBMapper", type="documentation"]
class, you define the relationship between items in a {DDB} table and their corresponding object
instances in your code by using annotations (as shown in the following code example). The
link:sdk-for-java/v1/reference/com/amazonaws/services/dynamodbv2/datamodeling/DynamoDBMapper.html["DynamoDBMapper", type="documentation"]
class enables you to access your tables; perform various create, read, update, and delete (CRUD)
operations; and execute queries.

[NOTE]
====

The
link:sdk-for-java/v1/reference/com/amazonaws/services/dynamodbv2/datamodeling/DynamoDBMapper.html["DynamoDBMapper", type="documentation"]
class does not allow you to create, update, or delete tables.

====

*Imports*

[source,java]
----
import com.amazonaws.services.dynamodbv2.AmazonDynamoDB;
import com.amazonaws.services.dynamodbv2.AmazonDynamoDBClientBuilder;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBMapper;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBRangeKey;
import com.amazonaws.services.dynamodbv2.model.AmazonDynamoDBException;
----

*Code*

The following Java code example shows you how to add content to the _Music_ table by using the
link:sdk-for-java/v1/reference/com/amazonaws/services/dynamodbv2/datamodeling/DynamoDBMapper.html["DynamoDBMapper", type="documentation"]
class. After the content is added to the table, notice that an item is loaded by using the
_Partition_ and _Sort_ keys. Then the _Awards_ item is updated. For information on creating the
_Music_ table, see {url-ddb-dev}getting-started-step-1.html[Create a Table] in the {guide-ddb-dev}.

[source,java]
----
       AmazonDynamoDB client = AmazonDynamoDBClientBuilder.standard().build();
       MusicItems items = new MusicItems();

       try{
           // Add new content to the Music table
           items.setArtist(artist);
           items.setSongTitle(songTitle);
           items.setAlbumTitle(albumTitle);
           items.setAwards(Integer.parseInt(awards)); //convert to an int

           // Save the item
           DynamoDBMapper mapper = new DynamoDBMapper(client);
           mapper.save(items);

           // Load an item based on the Partition Key and Sort Key
           // Both values need to be passed to the mapper.load method
           String artistName = artist;
           String songQueryTitle = songTitle;

           // Retrieve the item
           MusicItems itemRetrieved = mapper.load(MusicItems.class, artistName, songQueryTitle);
           System.out.println("Item retrieved:");
           System.out.println(itemRetrieved);

           // Modify the Award value
           itemRetrieved.setAwards(2);
           mapper.save(itemRetrieved);
           System.out.println("Item updated:");
           System.out.println(itemRetrieved);

           System.out.print("Done");
       } catch (AmazonDynamoDBException e) {
           e.getStackTrace();
       }
   }

   @DynamoDBTable(tableName="Music")
   public static class MusicItems {

       //Set up Data Members that correspond to columns in the Music table
       private String artist;
       private String songTitle;
       private String albumTitle;
       private int awards;

       @DynamoDBHashKey(attributeName="Artist")
       public String getArtist() {
           return this.artist;
       }

       public void setArtist(String artist) {
           this.artist = artist;
       }

       @DynamoDBRangeKey(attributeName="SongTitle")
       public String getSongTitle() {
           return this.songTitle;
       }

       public void setSongTitle(String title) {
           this.songTitle = title;
       }

       @DynamoDBAttribute(attributeName="AlbumTitle")
       public String getAlbumTitle() {
           return this.albumTitle;
       }

       public void setAlbumTitle(String title) {
           this.albumTitle = title;
       }

       @DynamoDBAttribute(attributeName="Awards")
       public int getAwards() {
           return this.awards;
       }

       public void setAwards(int awards) {
           this.awards = awards;
       }
   }
----

See the
{url-awsdocs-github}aws-doc-sdk-examples/blob/master/java/example_code/dynamodb/src/main/java/aws/example/dynamodb/UseDynamoMapping.java[complete example]
on GitHub.

[[more-info,more-info.title]]
== More Info

* {url-ddb-dev}GuidelinesForItems.html[Guidelines for Working with Items] in the {guide-ddb-dev}
* {url-ddb-dev}WorkingWithItems.html[Working with Items in {DDB}] in the {guide-ddb-dev}
