//!!NODE_ROOT <section>
include::../../includes.txt[]
:https---docs-aws-amazon-com-IAM-latest-APIReference-API-DeleteUser-html: {url-doc-domain}IAM/latest/APIReference/API_DeleteUser.html
:https---docs-aws-amazon-com-IAM-latest-APIReference-API-UpdateUser-html: {url-doc-domain}IAM/latest/APIReference/API_UpdateUser.html
:https---docs-aws-amazon-com-IAM-latest-APIReference-API-ListUsers-html: {url-doc-domain}IAM/latest/APIReference/API_ListUsers.html
:https---docs-aws-amazon-com-IAM-latest-APIReference-API-CreateUser-html: {url-doc-domain}IAM/latest/APIReference/API_CreateUser.html
:https---docs-aws-amazon-com-IAM-latest-UserGuide-id-users-manage-html: {url-doc-domain}IAM/latest/UserGuide/id_users_manage.html
:https---docs-aws-amazon-com-IAM-latest-UserGuide-id-users-html: {url-doc-domain}IAM/latest/UserGuide/id_users.html
:https---github-com-awsdocs-aws-doc-sdk-examples-blob-master-java-example-code-iam-src-main-java-aws-example-iam-DeleteUser-java: {url-awsdocs-github}aws-doc-sdk-examples/blob/master/java/example_code/iam/src/main/java/aws/example/iam/DeleteUser.java
:https---github-com-awsdocs-aws-doc-sdk-examples-blob-master-java-example-code-iam-src-main-java-aws-example-iam-UpdateUser-java: {url-awsdocs-github}aws-doc-sdk-examples/blob/master/java/example_code/iam/src/main/java/aws/example/iam/UpdateUser.java
:https---github-com-awsdocs-aws-doc-sdk-examples-blob-master-java-example-code-iam-src-main-java-aws-example-iam-ListUsers-java: {url-awsdocs-github}aws-doc-sdk-examples/blob/master/java/example_code/iam/src/main/java/aws/example/iam/ListUsers.java
:https---github-com-awsdocs-aws-doc-sdk-examples-blob-master-java-example-code-iam-src-main-java-aws-example-iam-CreateUser-java: {url-awsdocs-github}aws-doc-sdk-examples/blob/master/java/example_code/iam/src/main/java/aws/example/iam/CreateUser.java

[."topic"]
[[examples-iam-users,examples-iam-users.title]]
= [[managing-iam-users, Managing IAM Users]]Managing IAM Users
:info_doctype: section
:info_title: Managing IAM Users
:info_abstract: How to set, get, and delete a policy for an {S3} bucket.
:info_keywordset: sdk-javacode examplesbucket policies

[abstract]
--
How to set, get, and delete a policy for an {S3} bucket.
--

[[creating-a-user,creating-a-user.title]]
== Creating a User

Create a new IAM user by providing the user name to the AmazonIdentityManagementClient's  `createUser` method, either directly or using a link:sdk-for-java/v1/reference/com/amazonaws/services/identitymanagement/model/CreateUserRequest.html["CreateUserRequest", type="documentation"] object containing the user name.

*Imports*

[source,java]
----
import com.amazonaws.services.identitymanagement.AmazonIdentityManagement;
import com.amazonaws.services.identitymanagement.AmazonIdentityManagementClientBuilder;
import com.amazonaws.services.identitymanagement.model.CreateUserRequest;
import com.amazonaws.services.identitymanagement.model.CreateUserResult;
----

*Code*

[source,java]
----
final AmazonIdentityManagement iam =
    AmazonIdentityManagementClientBuilder.defaultClient();

CreateUserRequest request = new CreateUserRequest()
    .withUserName(username);

CreateUserResult response = iam.createUser(request);
----

See the  {https---github-com-awsdocs-aws-doc-sdk-examples-blob-master-java-example-code-iam-src-main-java-aws-example-iam-CreateUser-java}[complete example] on GitHub.

[[listing-users,listing-users.title]]
== Listing Users

To list the IAM users for your account, create a new  link:sdk-for-java/v1/reference/com/amazonaws/services/identitymanagement/model/ListUsersRequest.html["ListUsersRequest", type="documentation"] and pass it to the AmazonIdentityManagementClient's `listUsers` method. You can retrieve the list of users by calling `getUsers` on the returned link:sdk-for-java/v1/reference/com/amazonaws/services/identitymanagement/model/ListUsersResponse.html["ListUsersResponse", type="documentation"] object.

The list of users returned by `listUsers` is paged. You can check to see there are more results to retrieve by calling the response object's `getIsTruncated` method. If it returns ``true``, then call the request object's `setMarker()` method, passing it the return value of the response object's `getMarker()` method.

*Imports*

[source,java]
----
import com.amazonaws.services.identitymanagement.AmazonIdentityManagement;
import com.amazonaws.services.identitymanagement.AmazonIdentityManagementClientBuilder;
import com.amazonaws.services.identitymanagement.model.ListUsersRequest;
import com.amazonaws.services.identitymanagement.model.ListUsersResult;
import com.amazonaws.services.identitymanagement.model.User;
----

*Code*

[source,java]
----
final AmazonIdentityManagement iam =
    AmazonIdentityManagementClientBuilder.defaultClient();

boolean done = false;
ListUsersRequest request = new ListUsersRequest();

while(!done) {
    ListUsersResult response = iam.listUsers(request);

    for(User user : response.getUsers()) {
        System.out.format("Retrieved user %s", user.getUserName());
    }

    request.setMarker(response.getMarker());

    if(!response.getIsTruncated()) {
        done = true;
    }
}
----

See the  {https---github-com-awsdocs-aws-doc-sdk-examples-blob-master-java-example-code-iam-src-main-java-aws-example-iam-ListUsers-java}[complete example] on GitHub.

[[updating-a-user,updating-a-user.title]]
== Updating a User

To update a user, call the AmazonIdentityManagementClient object's  `updateUser` method, which takes a link:sdk-for-java/v1/reference/com/amazonaws/services/identitymanagement/model/UpdateUserRequest.html["UpdateUserRequest", type="documentation"] object that you can use to change the user's _name_ or __path__.

*Imports*

[source,java]
----
import com.amazonaws.services.identitymanagement.AmazonIdentityManagement;
import com.amazonaws.services.identitymanagement.AmazonIdentityManagementClientBuilder;
import com.amazonaws.services.identitymanagement.model.UpdateUserRequest;
import com.amazonaws.services.identitymanagement.model.UpdateUserResult;
----

*Code*

[source,java]
----
final AmazonIdentityManagement iam =
    AmazonIdentityManagementClientBuilder.defaultClient();

UpdateUserRequest request = new UpdateUserRequest()
    .withUserName(cur_name)
    .withNewUserName(new_name);

UpdateUserResult response = iam.updateUser(request);
----

See the  {https---github-com-awsdocs-aws-doc-sdk-examples-blob-master-java-example-code-iam-src-main-java-aws-example-iam-UpdateUser-java}[complete example] on GitHub.

[[deleting-a-user,deleting-a-user.title]]
== Deleting a User

To delete a user, call the AmazonIdentityManagementClient's  `deleteUser` request with a link:sdk-for-java/v1/reference/com/amazonaws/services/identitymanagement/model/UpdateUserRequest.html["UpdateUserRequest", type="documentation"] object set with the user name to delete.

*Imports*

[source,java]
----
import com.amazonaws.services.identitymanagement.AmazonIdentityManagement;
import com.amazonaws.services.identitymanagement.AmazonIdentityManagementClientBuilder;
import com.amazonaws.services.identitymanagement.model.DeleteConflictException;
import com.amazonaws.services.identitymanagement.model.DeleteUserRequest;
----

*Code*

[source,java]
----
final AmazonIdentityManagement iam =
    AmazonIdentityManagementClientBuilder.defaultClient();

DeleteUserRequest request = new DeleteUserRequest()
    .withUserName(username);

try {
    iam.deleteUser(request);
} catch (DeleteConflictException e) {
    System.out.println("Unable to delete user. Verify user is not" +
            " associated with any resources");
    throw e;
}
----

See the  {https---github-com-awsdocs-aws-doc-sdk-examples-blob-master-java-example-code-iam-src-main-java-aws-example-iam-DeleteUser-java}[complete example] on GitHub.

[[more-information,more-information.title]]
== More Information

* {https---docs-aws-amazon-com-IAM-latest-UserGuide-id-users-html}[IAM Users] in the {guide-iam-user}
* {https---docs-aws-amazon-com-IAM-latest-UserGuide-id-users-manage-html}[Managing IAM Users] in the {guide-iam-user}
* {https---docs-aws-amazon-com-IAM-latest-APIReference-API-CreateUser-html}[CreateUser] in the IAM API Reference
* {https---docs-aws-amazon-com-IAM-latest-APIReference-API-ListUsers-html}[ListUsers] in the IAM API Reference
* {https---docs-aws-amazon-com-IAM-latest-APIReference-API-UpdateUser-html}[UpdateUser] in the IAM API Reference
* {https---docs-aws-amazon-com-IAM-latest-APIReference-API-DeleteUser-html}[DeleteUser] in the IAM API Reference
