//!!NODE_ROOT <section>
include::../../includes.txt[]
:https---docs-aws-amazon-com-AWSEC2-latest-APIReference-API-ReleaseAddress-html: {url-doc-domain}AWSEC2/latest/APIReference/API_ReleaseAddress.html
:https---docs-aws-amazon-com-AWSEC2-latest-APIReference-API-DescribeAddresses-html: {url-doc-domain}AWSEC2/latest/APIReference/API_DescribeAddresses.html
:https---docs-aws-amazon-com-AWSEC2-latest-APIReference-API-AllocateAddress-html: {url-doc-domain}AWSEC2/latest/APIReference/API_AllocateAddress.html
:https---github-com-awsdocs-aws-doc-sdk-examples-blob-master-java-example-code-ec2-src-main-java-aws-example-ec2-ReleaseAddress-java: {url-awsdocs-github}aws-doc-sdk-examples/blob/master/java/example_code/ec2/src/main/java/aws/example/ec2/ReleaseAddress.java
:https---github-com-awsdocs-aws-doc-sdk-examples-blob-master-java-example-code-ec2-src-main-java-aws-example-ec2-DescribeAddresses-java: {url-awsdocs-github}aws-doc-sdk-examples/blob/master/java/example_code/ec2/src/main/java/aws/example/ec2/DescribeAddresses.java
:https---github-com-awsdocs-aws-doc-sdk-examples-blob-master-java-example-code-ec2-src-main-java-aws-example-ec2-AllocateAddress-java: {url-awsdocs-github}aws-doc-sdk-examples/blob/master/java/example_code/ec2/src/main/java/aws/example/ec2/AllocateAddress.java

[."topic"]
[[examples-ec2-elastic-ip,examples-ec2-elastic-ip.title]]
= [[using-elastic-ip-addresses-in-ec2, Using Elastic IP Addresses in EC2]]Using Elastic IP Addresses in {EC2}
:info_doctype: section
:info_title: Using Elastic IP Addresses in {EC2}
:info_abstract: How to allocate, use, list, and release Elastic IP addresses for EC2 instances with the {sdk-java}.
:info_keywordset: sdk-javacodeexamplesEC2Elastic IPallocate addressrelease addressassign addressassociate addresslist addresses

[abstract]
--
How to allocate, use, list, and release Elastic IP addresses for EC2 instances with the {sdk-java}.
--

[[allocating-an-elastic-ip-address,allocating-an-elastic-ip-address.title]]
== Allocating an Elastic IP Address

To use an Elastic IP address, you first allocate one to your account, and then associate it with your instance or a network interface.

To allocate an Elastic IP address, call the AmazonEC2Client's `allocateAddress` method with an link:sdk-for-java/v1/reference/com/amazonaws/services/ec2/model/AllocateAddressRequest.html["AllocateAddressRequest", type="documentation"] object containing the network type (classic EC2 or VPC).

The returned link:sdk-for-java/v1/reference/com/amazonaws/services/ec2/model/AllocateAddressResult.html["AllocateAddressResult", type="documentation"] contains an allocation ID that you can use to associate the address with an instance, by passing the allocation ID and instance ID in a link:sdk-for-java/v1/reference/com/amazonaws/services/ec2/model/AssociateAddressRequest.html["AssociateAddressRequest", type="documentation"] to the AmazonEC2Client's `associateAddress` method.

*Imports*

[source,java]
----
import com.amazonaws.services.ec2.AmazonEC2;
import com.amazonaws.services.ec2.AmazonEC2ClientBuilder;
import com.amazonaws.services.ec2.model.AllocateAddressRequest;
import com.amazonaws.services.ec2.model.AllocateAddressResult;
import com.amazonaws.services.ec2.model.AssociateAddressRequest;
import com.amazonaws.services.ec2.model.AssociateAddressResult;
import com.amazonaws.services.ec2.model.DomainType;
----

*Code*

[source,java]
----
final AmazonEC2 ec2 = AmazonEC2ClientBuilder.defaultClient();

AllocateAddressRequest allocate_request = new AllocateAddressRequest()
    .withDomain(DomainType.Vpc);

AllocateAddressResult allocate_response =
    ec2.allocateAddress(allocate_request);

String allocation_id = allocate_response.getAllocationId();

AssociateAddressRequest associate_request =
    new AssociateAddressRequest()
        .withInstanceId(instance_id)
        .withAllocationId(allocation_id);

AssociateAddressResult associate_response =
    ec2.associateAddress(associate_request);
----

See the  {https---github-com-awsdocs-aws-doc-sdk-examples-blob-master-java-example-code-ec2-src-main-java-aws-example-ec2-AllocateAddress-java}[complete example].

[[describing-elastic-ip-addresses,describing-elastic-ip-addresses.title]]
== Describing Elastic IP Addresses

To list the Elastic IP addresses assigned to your account, call the AmazonEC2Client's  `describeAddresses` method. It returns a link:sdk-for-java/v1/reference/com/amazonaws/services/ec2/model/DescribeAddressesResult.html["DescribeAddressesResult", type="documentation"] which you can use to get a list of link:sdk-for-java/v1/reference/com/amazonaws/services/ec2/model/Address.html["Address", type="documentation"] objects that represent the Elastic IP addresses on your account.

*Imports*

[source,java]
----
import com.amazonaws.services.ec2.AmazonEC2;
import com.amazonaws.services.ec2.AmazonEC2ClientBuilder;
import com.amazonaws.services.ec2.model.Address;
import com.amazonaws.services.ec2.model.DescribeAddressesResult;
----

*Code*

[source,java]
----
final AmazonEC2 ec2 = AmazonEC2ClientBuilder.defaultClient();

DescribeAddressesResult response = ec2.describeAddresses();

for(Address address : response.getAddresses()) {
    System.out.printf(
            "Found address with public IP %s, " +
            "domain %s, " +
            "allocation id %s " +
            "and NIC id %s",
            address.getPublicIp(),
            address.getDomain(),
            address.getAllocationId(),
            address.getNetworkInterfaceId());
}
----

See the  {https---github-com-awsdocs-aws-doc-sdk-examples-blob-master-java-example-code-ec2-src-main-java-aws-example-ec2-DescribeAddresses-java}[complete example].

[[releasing-an-elastic-ip-address,releasing-an-elastic-ip-address.title]]
== Releasing an Elastic IP Address

To release an Elastic IP address, call the AmazonEC2Client's  `releaseAddress` method, passing it a link:sdk-for-java/v1/reference/com/amazonaws/services/ec2/model/ReleaseAddressRequest.html["ReleaseAddressRequest", type="documentation"] containing the allocation ID of the Elastic IP address you want to release.

*Imports*

[source,java]
----
import com.amazonaws.services.ec2.AmazonEC2;
import com.amazonaws.services.ec2.AmazonEC2ClientBuilder;
import com.amazonaws.services.ec2.model.ReleaseAddressRequest;
import com.amazonaws.services.ec2.model.ReleaseAddressResult;
----

*Code*

[source,java]
----
final AmazonEC2 ec2 = AmazonEC2ClientBuilder.defaultClient();

ReleaseAddressRequest request = new ReleaseAddressRequest()
    .withAllocationId(alloc_id);

ReleaseAddressResult response = ec2.releaseAddress(request);
----

After you release an Elastic IP address, it is released to the {AWS} IP address pool and might be unavailable to you afterward. Be sure to update your DNS records and any servers or devices that communicate with the address. If you attempt to release an Elastic IP address that you already released, you'll get an  _AuthFailure_ error if the address is already allocated to another {AWS-account}.

If you are using _EC2-Classic_ or a __default VPC__, then releasing an Elastic IP address automatically disassociates it from any instance that it's associated with. To disassociate an Elastic IP address without releasing it, use the AmazonEC2Client's `disassociateAddress` method.

If you are using a non-default VPC, you _must_ use `disassociateAddress` to disassociate the Elastic IP address before you try to release it. Otherwise, {EC2} returns an error (__InvalidIPAddress.InUse__).

See the {https---github-com-awsdocs-aws-doc-sdk-examples-blob-master-java-example-code-ec2-src-main-java-aws-example-ec2-ReleaseAddress-java}[complete example].

[[more-information,more-information.title]]
== More Information

* {url-ec2-user}elastic-ip-addresses-eip.html[Elastic IP Addresses] in the {guide-ec2-user}
* {https---docs-aws-amazon-com-AWSEC2-latest-APIReference-API-AllocateAddress-html}[AllocateAddress] in the {EC2} API Reference
* {https---docs-aws-amazon-com-AWSEC2-latest-APIReference-API-DescribeAddresses-html}[DescribeAddresses] in the {EC2} API Reference
* {https---docs-aws-amazon-com-AWSEC2-latest-APIReference-API-ReleaseAddress-html}[ReleaseAddress] in the {EC2} API Reference
