//!!NODE_ROOT <section>
include::../../includes.txt[]
:https---docs-aws-amazon-com-AWSSimpleQueueService-latest-APIReference-API-ChangeMessageVisibilityBatch-html: {url-doc-domain}AWSSimpleQueueService/latest/APIReference/API_ChangeMessageVisibilityBatch.html
:https---docs-aws-amazon-com-AWSSimpleQueueService-latest-APIReference-API-ChangeMessageVisibility-html: {url-doc-domain}AWSSimpleQueueService/latest/APIReference/API_ChangeMessageVisibility.html
:https---docs-aws-amazon-com-AWSSimpleQueueService-latest-APIReference-API-ReceiveMessage-html: {url-doc-domain}AWSSimpleQueueService/latest/APIReference/API_ReceiveMessage.html
:https---docs-aws-amazon-com-AWSSimpleQueueService-latest-APIReference-API-GetQueueAttributes-html: {url-doc-domain}AWSSimpleQueueService/latest/APIReference/API_GetQueueAttributes.html
:https---docs-aws-amazon-com-AWSSimpleQueueService-latest-APIReference-API-SetQueueAttributes-html: {url-doc-domain}AWSSimpleQueueService/latest/APIReference/API_SetQueueAttributes.html
:https---github-com-awsdocs-aws-doc-sdk-examples-blob-master-java-example-code-sqs-src-main-java-aws-example-sqs-VisibilityTimeout-java: {url-awsdocs-github}aws-doc-sdk-examples/blob/master/java/example_code/sqs/src/main/java/aws/example/sqs/VisibilityTimeout.java

[."topic"]
[[examples-sqs-visibility-timeout,examples-sqs-visibility-timeout.title]]
= [[setting-visibility-timeout-in-sqs, Setting Visibility Timeout in {SQS}]]Setting Visibility Timeout in {SQS}
:info_doctype: section
:info_title: Setting Visibility Timeout in {SQS}
:info_abstract: How to set visibility timeout for {SQS} queues with the {sdk-java}.
:info_keywordset: sdk-javacode examples{SQS}visibility timeout

[abstract]
--
How to set visibility timeout for {SQS} queues with the {sdk-java}.
--

When a message is received in {SQS}, it remains on the queue until it's deleted in order to ensure receipt. A message that was received, but not deleted, will be available in subsequent requests after a given  _visibility timeout_ to help prevent the message from being received more than once before it can be processed and deleted.

[NOTE]
====

When using link:AWSSimpleQueueService/latest/SQSDeveloperGuide/standard-queues.html["standard queues", type="documentation"], visibility timeout isn't a guarantee against receiving a message twice. If you are using a standard queue, be sure that your code can handle the case where the same message has been delivered more than once.

====

[[sqs-visibility-timeout-receipt,sqs-visibility-timeout-receipt.title]]
== Setting the Message Visibility Timeout for a Single Message

When you have received a message, you can modify its visibility timeout by passing its receipt handle in a  link:sdk-for-java/v1/reference/com/amazonaws/services/sqs/model/ChangeMessageVisibilityRequest.html["ChangeMessageVisibilityRequest", type="documentation"] that you pass to the AmazonSQS class' `changeMessageVisibility` method.

*Imports*

[source,java]
----
import com.amazonaws.services.sqs.AmazonSQS;
import com.amazonaws.services.sqs.AmazonSQSClientBuilder;
----

*Code*

[source,java]
----
AmazonSQS sqs = AmazonSQSClientBuilder.defaultClient();

// Get the receipt handle for the first message in the queue.
String receipt = sqs.receiveMessage(queue_url)
                    .getMessages()
                    .get(0)
                    .getReceiptHandle();

sqs.changeMessageVisibility(queue_url, receipt, timeout);
----

See the  {https---github-com-awsdocs-aws-doc-sdk-examples-blob-master-java-example-code-sqs-src-main-java-aws-example-sqs-VisibilityTimeout-java}[complete example] on GitHub.

[[setting-the-message-visibility-timeout-for-multiple-messages-at-once,setting-the-message-visibility-timeout-for-multiple-messages-at-once.title]]
== Setting the Message Visibility Timeout for Multiple Messages at Once

To set the message visibility timeout for multiple messages at once, create a list of  link:sdk-for-java/v1/reference/com/amazonaws/services/sqs/model/ChangeMessageVisibilityBatchRequestEntry.html["ChangeMessageVisibilityBatchRequestEntry", type="documentation"] objects, each containing a unique ID string and a receipt handle. Then, pass the list to the {SQS} client class' `changeMessageVisibilityBatch` method.

*Imports*

[source,java]
----
import com.amazonaws.services.sqs.AmazonSQS;
import com.amazonaws.services.sqs.AmazonSQSClientBuilder;
import com.amazonaws.services.sqs.model.ChangeMessageVisibilityBatchRequestEntry;
import java.util.ArrayList;
import java.util.List;
----

*Code*

[source,java]
----
AmazonSQS sqs = AmazonSQSClientBuilder.defaultClient();

List<ChangeMessageVisibilityBatchRequestEntry> entries =
    new ArrayList<ChangeMessageVisibilityBatchRequestEntry>();

entries.add(new ChangeMessageVisibilityBatchRequestEntry(
            "unique_id_msg1",
            sqs.receiveMessage(queue_url)
               .getMessages()
               .get(0)
               .getReceiptHandle())
        .withVisibilityTimeout(timeout));

entries.add(new ChangeMessageVisibilityBatchRequestEntry(
            "unique_id_msg2",
            sqs.receiveMessage(queue_url)
               .getMessages()
               .get(0)
               .getReceiptHandle())
        .withVisibilityTimeout(timeout + 200));

sqs.changeMessageVisibilityBatch(queue_url, entries);
----

See the  {https---github-com-awsdocs-aws-doc-sdk-examples-blob-master-java-example-code-sqs-src-main-java-aws-example-sqs-VisibilityTimeout-java}[complete example] on GitHub.

[[more-info,more-info.title]]
== More Info

* link:AWSSimpleQueueService/latest/SQSDeveloperGuide/sqs-visibility-timeout.html["Visibility Timeout", type="documentation"] in the {SQS} Developer Guide
* {https---docs-aws-amazon-com-AWSSimpleQueueService-latest-APIReference-API-SetQueueAttributes-html}[SetQueueAttributes] in the {SQS} API Reference
* {https---docs-aws-amazon-com-AWSSimpleQueueService-latest-APIReference-API-GetQueueAttributes-html}[GetQueueAttributes] in the {SQS} API Reference
* {https---docs-aws-amazon-com-AWSSimpleQueueService-latest-APIReference-API-ReceiveMessage-html}[ReceiveMessage] in the {SQS} API Reference
* {https---docs-aws-amazon-com-AWSSimpleQueueService-latest-APIReference-API-ChangeMessageVisibility-html}[ChangeMessageVisibility] in the {SQS} API Reference
* {https---docs-aws-amazon-com-AWSSimpleQueueService-latest-APIReference-API-ChangeMessageVisibilityBatch-html}[ChangeMessageVisibilityBatch] in the {SQS} API Reference
