//!!NODE_ROOT <section>
include::../../includes.txt[]
:https---docs-aws-amazon-com-AWSEC2-latest-APIReference-API-UnmonitorInstances-html: {url-doc-domain}AWSEC2/latest/APIReference/API_UnmonitorInstances.html
:https---docs-aws-amazon-com-AWSEC2-latest-APIReference-API-MonitorInstances-html: {url-doc-domain}AWSEC2/latest/APIReference/API_MonitorInstances.html
:https---docs-aws-amazon-com-AWSEC2-latest-APIReference-API-RebootInstances-html: {url-doc-domain}AWSEC2/latest/APIReference/API_RebootInstances.html
:https---docs-aws-amazon-com-AWSEC2-latest-APIReference-API-StopInstances-html: {url-doc-domain}AWSEC2/latest/APIReference/API_StopInstances.html
:https---docs-aws-amazon-com-AWSEC2-latest-APIReference-API-StartInstances-html: {url-doc-domain}AWSEC2/latest/APIReference/API_StartInstances.html
:https---docs-aws-amazon-com-AWSEC2-latest-APIReference-API-DescribeInstances-html: {url-doc-domain}AWSEC2/latest/APIReference/API_DescribeInstances.html
:https---docs-aws-amazon-com-AWSEC2-latest-APIReference-API-RunInstances-html: {url-doc-domain}AWSEC2/latest/APIReference/API_RunInstances.html
:https---github-com-awsdocs-aws-doc-sdk-examples-blob-master-java-example-code-ec2-src-main-java-aws-example-ec2-MonitorInstance-java: {url-awsdocs-github}aws-doc-sdk-examples/blob/master/java/example_code/ec2/src/main/java/aws/example/ec2/MonitorInstance.java
:https---docs-aws-amazon-com-AWSEC2-latest-UserGuide-monitoring-ec2-html: {url-ec2-user}monitoring_ec2.html
:https---github-com-awsdocs-aws-doc-sdk-examples-blob-master-java-example-code-ec2-src-main-java-aws-example-ec2-DescribeInstances-java: {url-awsdocs-github}aws-doc-sdk-examples/blob/master/java/example_code/ec2/src/main/java/aws/example/ec2/DescribeInstances.java
:https---github-com-awsdocs-aws-doc-sdk-examples-blob-master-java-example-code-ec2-src-main-java-aws-example-ec2-RebootInstance-java: {url-awsdocs-github}aws-doc-sdk-examples/blob/master/java/example_code/ec2/src/main/java/aws/example/ec2/RebootInstance.java
:https---github-com-awsdocs-aws-doc-sdk-examples-blob-master-java-example-code-ec2-src-main-java-aws-example-ec2-StartStopInstance-java: {url-awsdocs-github}aws-doc-sdk-examples/blob/master/java/example_code/ec2/src/main/java/aws/example/ec2/StartStopInstance.java
:https---github-com-awsdocs-aws-doc-sdk-examples-blob-master-java-example-code-ec2-src-main-java-aws-example-ec2-CreateInstance-java: {url-awsdocs-github}aws-doc-sdk-examples/blob/master/java/example_code/ec2/src/main/java/aws/example/ec2/CreateInstance.java
[."topic"]
[[examples-ec2-instances,examples-ec2-instances.title]]
= [[managing-ec2-instances, Managing EC2 Instances]]Managing {EC2} Instances
:info_doctype: section
:info_title: Managing {EC2} Instances
:info_abstract: How to create, start, stop, reboot, list and monitor EC2 instances using the {sdk-java}.
:info_keywordset: sdk-javacodeexamplesEC2 instancescreate instancestart instancestop instancereboot instancemonitor instancelist instancesdescribe instances

[abstract]
--
How to create, start, stop, reboot, list and monitor EC2 instances using the {sdk-java}.
--

[[creating-an-instance,creating-an-instance.title]]
== Creating an Instance

Create a new {EC2} instance by calling the AmazonEC2Client's  `runInstances` method, providing it with a link:sdk-for-java/v1/reference/com/amazonaws/services/ec2/model/RunInstancesRequest.html["RunInstancesRequest", type="documentation"] containing the {url-ec2-user}AMIs.html[Amazon Machine Image (AMI)] to use and an {url-ec2-user}instance-types.html[instance type].

*Imports*

[source,java]
----
import com.amazonaws.services.ec2.AmazonEC2ClientBuilder;
import com.amazonaws.services.ec2.model.InstanceType;
import com.amazonaws.services.ec2.model.RunInstancesRequest;
import com.amazonaws.services.ec2.model.RunInstancesResult;
import com.amazonaws.services.ec2.model.Tag;
----

*Code*

[source,java]
----

RunInstancesRequest run_request = new RunInstancesRequest()
    .withImageId(ami_id)
    .withInstanceType(InstanceType.T1Micro)
    .withMaxCount(1)
    .withMinCount(1);

RunInstancesResult run_response = ec2.runInstances(run_request);

String reservation_id = run_response.getReservation().getInstances().get(0).getInstanceId();
----

See the  {https---github-com-awsdocs-aws-doc-sdk-examples-blob-master-java-example-code-ec2-src-main-java-aws-example-ec2-CreateInstance-java}[complete example].

[[starting-an-instance,starting-an-instance.title]]
== Starting an Instance

To start an {EC2} instance, call the AmazonEC2Client's  `startInstances` method, providing it with a link:sdk-for-java/v1/reference/com/amazonaws/services/ec2/model/StartInstancesRequest.html["StartInstancesRequest", type="documentation"] containing the ID of the instance to start.

*Imports*

[source,java]
----
import com.amazonaws.services.ec2.AmazonEC2;
import com.amazonaws.services.ec2.AmazonEC2ClientBuilder;
import com.amazonaws.services.ec2.model.StartInstancesRequest;
----

*Code*

[source,java]
----
final AmazonEC2 ec2 = AmazonEC2ClientBuilder.defaultClient();

StartInstancesRequest request = new StartInstancesRequest()
    .withInstanceIds(instance_id);

ec2.startInstances(request);
----

See the  {https---github-com-awsdocs-aws-doc-sdk-examples-blob-master-java-example-code-ec2-src-main-java-aws-example-ec2-StartStopInstance-java}[complete example].

[[stopping-an-instance,stopping-an-instance.title]]
== Stopping an Instance

To stop an {EC2} instance, call the AmazonEC2Client's  `stopInstances` method, providing it with a link:sdk-for-java/v1/reference/com/amazonaws/services/ec2/model/StopInstancesRequest.html["StopInstancesRequest", type="documentation"] containing the ID of the instance to stop.

*Imports*

[source,java]
----
import com.amazonaws.services.ec2.AmazonEC2;
import com.amazonaws.services.ec2.AmazonEC2ClientBuilder;
import com.amazonaws.services.ec2.model.StopInstancesRequest;
----

*Code*

[source,java]
----
final AmazonEC2 ec2 = AmazonEC2ClientBuilder.defaultClient();

StopInstancesRequest request = new StopInstancesRequest()
    .withInstanceIds(instance_id);

ec2.stopInstances(request);
----

See the  {https---github-com-awsdocs-aws-doc-sdk-examples-blob-master-java-example-code-ec2-src-main-java-aws-example-ec2-StartStopInstance-java}[complete example].

[[rebooting-an-instance,rebooting-an-instance.title]]
== Rebooting an Instance

To reboot an {EC2} instance, call the AmazonEC2Client's  `rebootInstances` method, providing it with a link:sdk-for-java/v1/reference/com/amazonaws/services/ec2/model/RebootInstancesRequest.html["RebootInstancesRequest", type="documentation"] containing the ID of the instance to reboot.

*Imports*

[source,java]
----
import com.amazonaws.services.ec2.AmazonEC2;
import com.amazonaws.services.ec2.AmazonEC2ClientBuilder;
import com.amazonaws.services.ec2.model.RebootInstancesRequest;
import com.amazonaws.services.ec2.model.RebootInstancesResult;
----

*Code*

[source,java]
----
final AmazonEC2 ec2 = AmazonEC2ClientBuilder.defaultClient();

RebootInstancesRequest request = new RebootInstancesRequest()
    .withInstanceIds(instance_id);

RebootInstancesResult response = ec2.rebootInstances(request);
----

See the  {https---github-com-awsdocs-aws-doc-sdk-examples-blob-master-java-example-code-ec2-src-main-java-aws-example-ec2-RebootInstance-java}[complete example].

[[describing-instances,describing-instances.title]]
== Describing Instances

To list your instances, create a  link:sdk-for-java/v1/reference/com/amazonaws/services/ec2/model/DescribeInstancesRequest.html["DescribeInstancesRequest", type="documentation"] and call the AmazonEC2Client's `describeInstances` method. It will return a link:sdk-for-java/v1/reference/com/amazonaws/services/ec2/model/DescribeInstancesResult.html["DescribeInstancesResult", type="documentation"] object that you can use to list the {EC2} instances for your account and region.

Instances are grouped by __reservation__. Each reservation corresponds to the call to `startInstances` that launched the instance. To list your instances, you must first call the `DescribeInstancesResult` class' `getReservations' method, and then call `getInstances` on each returned link:sdk-for-java/v1/reference/com/amazonaws/services/ec2/model/Reservation.html["Reservation", type="documentation"] object.

*Imports*

[source,java]
----
import com.amazonaws.services.ec2.AmazonEC2;
import com.amazonaws.services.ec2.AmazonEC2ClientBuilder;
import com.amazonaws.services.ec2.model.DescribeInstancesRequest;
import com.amazonaws.services.ec2.model.DescribeInstancesResult;
import com.amazonaws.services.ec2.model.Instance;
import com.amazonaws.services.ec2.model.Reservation;
----

*Code*

[source,java]
----
final AmazonEC2 ec2 = AmazonEC2ClientBuilder.defaultClient();
boolean done = false;

DescribeInstancesRequest request = new DescribeInstancesRequest();
while(!done) {
    DescribeInstancesResult response = ec2.describeInstances(request);

    for(Reservation reservation : response.getReservations()) {
        for(Instance instance : reservation.getInstances()) {
            System.out.printf(
                "Found instance with id %s, " +
                "AMI %s, " +
                "type %s, " +
                "state %s " +
                "and monitoring state %s",
                instance.getInstanceId(),
                instance.getImageId(),
                instance.getInstanceType(),
                instance.getState().getName(),
                instance.getMonitoring().getState());
        }
    }

    request.setNextToken(response.getNextToken());

    if(response.getNextToken() == null) {
        done = true;
    }
}
----

Results are paged; you can get further results by passing the value returned from the result object's  `getNextToken` method to your original request object's `setNextToken` method, then using the same request object in your next call to ``describeInstances``.

See the {https---github-com-awsdocs-aws-doc-sdk-examples-blob-master-java-example-code-ec2-src-main-java-aws-example-ec2-DescribeInstances-java}[complete example].

[[monitoring-an-instance,monitoring-an-instance.title]]
== Monitoring an Instance

You can monitor various aspects of your {EC2} instances, such as CPU and network utilization, available memory, and disk space remaining. To learn more about instance monitoring, see  {https---docs-aws-amazon-com-AWSEC2-latest-UserGuide-monitoring-ec2-html}[Monitoring {EC2}] in the {guide-ec2-user}.

To start monitoring an instance, you must create a link:sdk-for-java/v1/reference/com/amazonaws/services/ec2/model/MonitorInstancesRequest.html["MonitorInstancesRequest", type="documentation"] with the ID of the instance to monitor, and pass it to the AmazonEC2Client's `monitorInstances` method.

*Imports*

[source,java]
----
import com.amazonaws.services.ec2.AmazonEC2;
import com.amazonaws.services.ec2.AmazonEC2ClientBuilder;
import com.amazonaws.services.ec2.model.MonitorInstancesRequest;
----

*Code*

[source,java]
----
final AmazonEC2 ec2 = AmazonEC2ClientBuilder.defaultClient();

MonitorInstancesRequest request = new MonitorInstancesRequest()
        .withInstanceIds(instance_id);

ec2.monitorInstances(request);
----

See the  {https---github-com-awsdocs-aws-doc-sdk-examples-blob-master-java-example-code-ec2-src-main-java-aws-example-ec2-MonitorInstance-java}[complete example].

[[stopping-instance-monitoring,stopping-instance-monitoring.title]]
== Stopping Instance Monitoring

To stop monitoring an instance, create an  link:sdk-for-java/v1/reference/com/amazonaws/services/ec2/model/UnmonitorInstancesRequest.html["UnmonitorInstancesRequest", type="documentation"] with the ID of the instance to stop monitoring, and pass it to the AmazonEC2Client's `unmonitorInstances` method.

*Imports*

[source,java]
----
import com.amazonaws.services.ec2.AmazonEC2;
import com.amazonaws.services.ec2.AmazonEC2ClientBuilder;
import com.amazonaws.services.ec2.model.UnmonitorInstancesRequest;
----

*Code*

[source,java]
----
final AmazonEC2 ec2 = AmazonEC2ClientBuilder.defaultClient();

UnmonitorInstancesRequest request = new UnmonitorInstancesRequest()
    .withInstanceIds(instance_id);

ec2.unmonitorInstances(request);
----

See the  {https---github-com-awsdocs-aws-doc-sdk-examples-blob-master-java-example-code-ec2-src-main-java-aws-example-ec2-MonitorInstance-java}[complete example].

[[more-information,more-information.title]]
== More Information

* {https---docs-aws-amazon-com-AWSEC2-latest-APIReference-API-RunInstances-html}[RunInstances] in the {EC2} API Reference
* {https---docs-aws-amazon-com-AWSEC2-latest-APIReference-API-DescribeInstances-html}[DescribeInstances] in the {EC2} API Reference
* {https---docs-aws-amazon-com-AWSEC2-latest-APIReference-API-StartInstances-html}[StartInstances] in the {EC2} API Reference
* {https---docs-aws-amazon-com-AWSEC2-latest-APIReference-API-StopInstances-html}[StopInstances] in the {EC2} API Reference
* {https---docs-aws-amazon-com-AWSEC2-latest-APIReference-API-RebootInstances-html}[RebootInstances] in the {EC2} API Reference
* {https---docs-aws-amazon-com-AWSEC2-latest-APIReference-API-MonitorInstances-html}[MonitorInstances] in the {EC2} API Reference
* {https---docs-aws-amazon-com-AWSEC2-latest-APIReference-API-UnmonitorInstances-html}[UnmonitorInstances] in the {EC2} API Reference
