//!!NODE_ROOT <section>
include::../../includes.txt[]
:https---docs-aws-amazon-com-AmazonCloudWatch-latest-APIReference-API-ListMetrics-html: {url-cw-api}API_ListMetrics.html
:https---docs-aws-amazon-com-AmazonCloudWatch-latest-monitoring-CW-Support-For-{AWS}-html: {url-doc-domain}AmazonCloudWatch/latest/monitoring/CW_Support_For_AWS.html

[."topic"]
[[examples-cloudwatch-get-metrics,examples-cloudwatch-get-metrics.title]]
= [[getting-metrics-from-cw, Getting Metrics from CloudWatch]]Getting Metrics from CloudWatch
:info_doctype: section
:info_title: Getting Metrics from CloudWatch
:info_abstract: How to list metrics from {CWlong} using the {sdk-java}.
:info_keywordset: sdk-javametricslistingcodeexamples

[abstract]
--
How to list metrics from {CWlong} using the {sdk-java}.
--

[[listing-metrics,listing-metrics.title]]
== Listing Metrics

To list CloudWatch metrics, create a  link:sdk-for-java/v1/reference/com/amazonaws/services/cloudwatch/model/ListMetricsRequest.html["ListMetricsRequest", type="documentation"] and call the AmazonCloudWatchClient's `listMetrics` method. You can use the `ListMetricsRequest` to filter the returned metrics by namespace, metric name, or dimensions.

[NOTE]
====

A list of metrics and dimensions that are posted by {AWS-services} can be found within the {https---docs-aws-amazon-com-AmazonCloudWatch-latest-monitoring-CW-Support-For-{AWS}-html}[Amazon CloudWatch Metrics and Dimensions Reference] in the {guide-cw-user}.

====

*Imports*

[source,java]
----
import com.amazonaws.services.cloudwatch.AmazonCloudWatch;
import com.amazonaws.services.cloudwatch.AmazonCloudWatchClientBuilder;
import com.amazonaws.services.cloudwatch.model.ListMetricsRequest;
import com.amazonaws.services.cloudwatch.model.ListMetricsResult;
import com.amazonaws.services.cloudwatch.model.Metric;
----

*Code*

[source,java]
----
final AmazonCloudWatch cw =
    AmazonCloudWatchClientBuilder.defaultClient();

ListMetricsRequest request = new ListMetricsRequest()
        .withMetricName(name)
        .withNamespace(namespace);

boolean done = false;

while(!done) {
    ListMetricsResult response = cw.listMetrics(request);

    for(Metric metric : response.getMetrics()) {
        System.out.printf(
            "Retrieved metric %s", metric.getMetricName());
    }

    request.setNextToken(response.getNextToken());

    if(response.getNextToken() == null) {
        done = true;
    }
}
----

The metrics are returned in a  link:sdk-for-java/v1/reference/com/amazonaws/services/cloudwatch/model/ListMetricsResult.html["ListMetricsResult", type="documentation"] by calling its `getMetrics` method. The results may be __paged__. To retrieve the next batch of results, call `setNextToken` on the original request object with the return value of the `ListMetricsResult` object's `getNextToken` method, and pass the modified request object back to another call to ``listMetrics``.

[[more-information,more-information.title]]
== More Information

* {https---docs-aws-amazon-com-AmazonCloudWatch-latest-APIReference-API-ListMetrics-html}[ListMetrics] in the {guide-cw-api}.
