//!!NODE_ROOT <section>
include::../../includes.txt[]
:https---www-bouncycastle-org-latest-releases-html: https://www.bouncycastle.org/latest_releases.html

[."topic"]
[[examples-crypto-kms,examples-crypto-kms.title]]
= [[s3-client-side-encryption-with-kms-managed-keys, S3 client-side encryption with KMS managed keys]]{S3} client-side encryption with {AWS} KMS managed keys
:info_doctype: section
:info_title: {S3} client-side encryption with {AWS} KMS managed keys
:info_abstract: How to use the cryptography configuration settings for the {sdk-java}
:info_keywordset: sdk-javacode examplescryptographyencryption

[abstract]
--
How to use the cryptography configuration settings for the {sdk-java}
--

The following examples use the  link:sdk-for-java/v1/reference/com/amazonaws/services/s3/AmazonS3EncryptionClientV2Builder.html["AmazonS3EncryptionClientV2Builder", type="documentation"] class to create an {S3} client with client-side encryption enabled. Once configured, any objects you upload to {S3} using this client will be encrypted. Any objects you get from {S3} using this client are automatically decrypted.

[NOTE]
====

The following examples demonstrate how to use the {S3} client-side encryption with {AWS} KMS managed keys. To learn how to use encryption with your own keys, see xref:examples-crypto-masterkey[{S3} client-side encryption with client master keys,linkend=examples-crypto-masterkey].

====

You can choose from two encryption modes when enabling client-side {S3} encryption: strict authenticated or authenticated. The following sections show how to enable each type. To learn which algorithms each mode uses, see the  link:sdk-for-java/v1/reference/com/amazonaws/services/s3/model/CryptoMode.html["CryptoMode", type="documentation"] definition.

[[required-imports,required-imports.title]]
== Required imports

Import the following classes for these examples.

*Imports*

[source,java]
----
import com.amazonaws.ClientConfiguration;
import com.amazonaws.regions.Regions;
import com.amazonaws.services.kms.AWSKMS;
import com.amazonaws.services.kms.AWSKMSClientBuilder;
import com.amazonaws.services.kms.model.GenerateDataKeyRequest;
import com.amazonaws.services.kms.model.GenerateDataKeyResult;
import com.amazonaws.services.s3.AmazonS3EncryptionClientV2Builder;
import com.amazonaws.services.s3.AmazonS3EncryptionV2;
import com.amazonaws.services.s3.model.CryptoConfigurationV2;
import com.amazonaws.services.s3.model.CryptoMode;
import com.amazonaws.services.s3.model.EncryptionMaterials;
import com.amazonaws.services.s3.model.KMSEncryptionMaterialsProvider;
----


[[strict-authenticated-encryption-kms,strict-authenticated-encryption-kms.title]]
== Strict authenticated encryption

Strict authenticated encryption is the default mode if no  `CryptoMode` is specified.

To explicitly enable this mode, specify the `StrictAuthenticatedEncryption` value in the `withCryptoConfiguration` method.

[NOTE]
====

To use client-side authenticated encryption, you must include the latest {https---www-bouncycastle-org-latest-releases-html}[Bouncy Castle jar] file in the classpath of your application.

====

*Code*

[source,java]
----
AmazonS3EncryptionV2 s3Encryption = AmazonS3EncryptionClientV2Builder.standard()
         .withRegion(Regions.US_WEST_2)
         .withCryptoConfiguration(new CryptoConfigurationV2().withCryptoMode((CryptoMode.StrictAuthenticatedEncryption)))
         .withEncryptionMaterialsProvider(new KMSEncryptionMaterialsProvider(keyId))
         .build();

s3Encryption.putObject(bucket_name, ENCRYPTED_KEY3, "This is the 3rd content to encrypt with a key created in the {console}");
System.out.println(s3Encryption.getObjectAsString(bucket_name, ENCRYPTED_KEY3));
----

Call the  `putObject` method on the {S3} encryption client to upload objects.

*Code*

[source,java]
----
s3Encryption.putObject(bucket_name, ENCRYPTED_KEY3, "This is the 3rd content to encrypt with a key created in the {console}");
----

You can retrieve the object using the same client. This example calls the  `getObjectAsString` method to retrieve the string that was stored.

*Code*

[source,java]
----
System.out.println(s3Encryption.getObjectAsString(bucket_name, ENCRYPTED_KEY3));
----


[[authenticated-encryption-kms,authenticated-encryption-kms.title]]
== Authenticated encryption mode

When you use  `AuthenticatedEncryption` mode, an improved key wrapping algorithm is applied during encryption. When decrypting in this mode, the algorithm can verify the integrity of the decrypted object and throw an exception if the check fails. For more details about how authenticated encryption works, see the link:developer/amazon-s3-client-side-authenticated-encryption["pass:q[[.shared\]`S3`] Client-Side Authenticated Encryption", type="blog"] blog post.

[NOTE]
====

To use client-side authenticated encryption, you must include the latest {https---www-bouncycastle-org-latest-releases-html}[Bouncy Castle jar] file in the classpath of your application.

====

To enable this mode, specify the  `AuthenticatedEncryption` value in the `withCryptoConfiguration` method.

*Code*

[source,java]
----
AmazonS3EncryptionV2 s3Encryption = AmazonS3EncryptionClientV2Builder.standard()
         .withRegion(Regions.US_WEST_2)
         .withCryptoConfiguration(new CryptoConfigurationV2().withCryptoMode((CryptoMode.AuthenticatedEncryption)))
         .withEncryptionMaterialsProvider(new KMSEncryptionMaterialsProvider(keyId))
         .build();
----