//!!NODE_ROOT <section>
include::../../includes.txt[]

[."topic"]
[[examples-cloudwatch,examples-cloudwatch.title]]
= [[cw-examples-using-the-sdk-java, CloudWatch Examples Using the SDK for Java]]CloudWatch Examples Using the {sdk-java}
:info_doctype: section
:info_title: CloudWatch Examples Using the {sdk-java}
:info_titleabbrev: {CWlong} Examples
:info_abstract: Programming {CWlong} using the {sdk-java}
:info_keywordset: sdk-javacode examplesCloudwatch

[abstract]
--
Programming {CWlong} using the {sdk-java}
--

This section provides examples of programming
link:cloudwatch/["pass:q[[.shared\]`CW`]", type="marketing"] using the
link:sdk-for-java/["pass:q[[.shared\]`Javalong`]", type="marketing"].

Amazon CloudWatch monitors your {AWSlong} ({AWS}) resources and the applications you run on {AWS} in real time. You can use CloudWatch to collect and track metrics, which are variables you can measure for your resources and applications. CloudWatch alarms send notifications or automatically make changes to the resources you are monitoring based on rules that you define.

For more information about {CW}, see the {link-cw-user}.

[NOTE]
====

The examples include only the code needed to demonstrate each technique. The {url-awsdocs-github}aws-doc-sdk-examples/tree/master/java[complete example code is available on GitHub]. From there, you can download a single source file or clone the repository locally to get all the examples to build and run.

====

[.topiclist-abbrev]
[[Topic List]]


include::examples-cloudwatch-get-metrics.adoc[leveloffset=+1]


include::examples-cloudwatch-publish-custom-metrics.adoc[leveloffset=+1]


include::examples-cloudwatch-create-alarms.adoc[leveloffset=+1]


include::examples-cloudwatch-use-alarm-actions.adoc[leveloffset=+1]


include::examples-cloudwatch-send-events.adoc[leveloffset=+1]
