//!!NODE_ROOT <section>
include::../../includes.txt[]
:https---github-com-awsdocs-aws-doc-sdk-examples-blob-master-java-example-code-s3-src-main-java-aws-example-s3-S3Encrypt-java: {url-awsdocs-github}aws-doc-sdk-examples/blob/master/java/example_code/s3/src/main/java/aws/example/s3/S3Encrypt.java
:https---docs-aws-amazon-com-general-latest-gr-aws-sdk-cryptography-html: {url-doc-domain}general/latest/gr/aws_sdk_cryptography.html

[."topic"]
[[examples-crypto,examples-crypto.title]]
= [[use-s3-client-side-encryption, Use S3 client-side encryption]]Use {S3} client-side encryption
:info_doctype: section
:info_title: Use {S3} client-side encryption
:info_abstract: How to use the cryptography configuration settings for the {sdk-java}
:info_keywordset: sdk-javacode examples

[abstract]
--
How to use the cryptography configuration settings for the {sdk-java}
--

Encrypting data using the {S3} encryption client is one way you can provide an additional layer of protection for sensitive information you store in {S3}. The examples in this section demonstrate how to create and configure the {S3} encryption client for your application.

If you are new to cryptography, see the link:kms/latest/developerguide/crypto-intro.html["Cryptography Basics", type="documentation"] in the {AWS} KMS Developer Guide for a basic overview of cryptography terms and algorithms. For information about cryptography support across all {AWS} SDKs, see {https---docs-aws-amazon-com-general-latest-gr-aws-sdk-cryptography-html}[{AWS} SDK Support for {S3} Client-Side Encryption] in the {AWS-GEN-REF-long}.

[NOTE]
====

These code examples assume that you understand the material in xref:basics[Using the {sdk-java},linkend=basics] and have configured default {AWS} credentials using the information in xref:setup-credentials[Set up {AWS} Credentials and Region for Development,linkend=setup-credentials].

====

If you are using version 1.11.836 or earlier of the {sdk-java}, see  xref:s3-encryption-migration[{S3} Encryption Client Migration,linkend=s3-encryption-migration] for information on migrating your applications to later versions. If you cannot migrate, see {https---github-com-awsdocs-aws-doc-sdk-examples-blob-master-java-example-code-s3-src-main-java-aws-example-s3-S3Encrypt-java}[this complete example] on GitHub.

Otherwise, if you are using version 1.11.837 or later of the {sdk-java}, explore the example topics listed below to use {S3} client-side encryption.

[.topiclist-abbrev]
[[Topic List]]


include::examples-crypto-masterkey.adoc[leveloffset=+1]


include::examples-crypto-kms.adoc[leveloffset=+1]
