//!!NODE_ROOT <section>
include::../../includes.txt[]
:https---docs-aws-amazon-com-AmazonCloudWatch-latest-APIReference-API-DeleteAlarms-html: {url-cw-api}API_DeleteAlarms.html
:https---docs-aws-amazon-com-AmazonCloudWatch-latest-APIReference-API-DescribeAlarms-html: {url-cw-api}API_DescribeAlarms.html
:https---docs-aws-amazon-com-AmazonCloudWatch-latest-APIReference-API-PutMetricAlarm-html: {url-cw-api}API_PutMetricAlarm.html

[."topic"]
[[examples-cloudwatch-create-alarms,examples-cloudwatch-create-alarms.title]]
= [[working-with-cw-alarms, Working with CloudWatch Alarms]]Working with CloudWatch Alarms
:info_doctype: section
:info_title: Working with CloudWatch Alarms
:info_abstract: How to create, list, and delete alarms in {CWlong} using the {sdk-java}
:info_keywordset: create alarmdelete alarmlist alarmsmetric alarmsexample code

[abstract]
--
How to create, list, and delete alarms in {CWlong} using the {sdk-java}
--

[[create-an-alarm,create-an-alarm.title]]
== Create an Alarm

To create an alarm based on a CloudWatch metric, call the AmazonCloudWatchClient's  `putMetricAlarm` method with a link:sdk-for-java/v1/reference/com/amazonaws/services/cloudwatch/model/PutMetricAlarmRequest.html["PutMetricAlarmRequest", type="documentation"] filled with the alarm conditions.

*Imports*

[source,java]
----
import com.amazonaws.services.cloudwatch.AmazonCloudWatch;
import com.amazonaws.services.cloudwatch.AmazonCloudWatchClientBuilder;
import com.amazonaws.services.cloudwatch.model.ComparisonOperator;
import com.amazonaws.services.cloudwatch.model.Dimension;
import com.amazonaws.services.cloudwatch.model.PutMetricAlarmRequest;
import com.amazonaws.services.cloudwatch.model.PutMetricAlarmResult;
import com.amazonaws.services.cloudwatch.model.StandardUnit;
import com.amazonaws.services.cloudwatch.model.Statistic;
----

*Code*

[source,java]
----
final AmazonCloudWatch cw =
    AmazonCloudWatchClientBuilder.defaultClient();

Dimension dimension = new Dimension()
    .withName("InstanceId")
    .withValue(instanceId);

PutMetricAlarmRequest request = new PutMetricAlarmRequest()
    .withAlarmName(alarmName)
    .withComparisonOperator(
        ComparisonOperator.GreaterThanThreshold)
    .withEvaluationPeriods(1)
    .withMetricName("CPUUtilization")
    .withNamespace("{AWS}/EC2")
    .withPeriod(60)
    .withStatistic(Statistic.Average)
    .withThreshold(70.0)
    .withActionsEnabled(false)
    .withAlarmDescription(
        "Alarm when server CPU utilization exceeds 70%")
    .withUnit(StandardUnit.Seconds)
    .withDimensions(dimension);

PutMetricAlarmResult response = cw.putMetricAlarm(request);
----


[[list-alarms,list-alarms.title]]
== List Alarms

To list the CloudWatch alarms that you have created, call the AmazonCloudWatchClient's  `describeAlarms` method with a link:sdk-for-java/v1/reference/com/amazonaws/services/cloudwatch/model/DescribeAlarmsRequest.html["DescribeAlarmsRequest", type="documentation"] that you can use to set options for the result.

*Imports*

[source,java]
----
import com.amazonaws.services.cloudwatch.AmazonCloudWatch;
import com.amazonaws.services.cloudwatch.AmazonCloudWatchClientBuilder;
import com.amazonaws.services.cloudwatch.model.DescribeAlarmsRequest;
import com.amazonaws.services.cloudwatch.model.DescribeAlarmsResult;
import com.amazonaws.services.cloudwatch.model.MetricAlarm;
----

*Code*

[source,java]
----
final AmazonCloudWatch cw =
    AmazonCloudWatchClientBuilder.defaultClient();

boolean done = false;
DescribeAlarmsRequest request = new DescribeAlarmsRequest();

while(!done) {

    DescribeAlarmsResult response = cw.describeAlarms(request);

    for(MetricAlarm alarm : response.getMetricAlarms()) {
        System.out.printf("Retrieved alarm %s", alarm.getAlarmName());
    }

    request.setNextToken(response.getNextToken());

    if(response.getNextToken() == null) {
        done = true;
    }
}
----

The list of alarms can be obtained by calling  `getMetricAlarms` on the link:sdk-for-java/v1/reference/com/amazonaws/services/cloudwatch/model/DescribeAlarmsResult.html["DescribeAlarmsResult", type="documentation"] that is returned by ``describeAlarms``.

The results may be __paged__. To retrieve the next batch of results, call `setNextToken` on the original request object with the return value of the `DescribeAlarmsResult` object's `getNextToken` method, and pass the modified request object back to another call to ``describeAlarms``.

[NOTE]
====

You can also retrieve alarms for a specific metric by using the AmazonCloudWatchClient's `describeAlarmsForMetric` method. Its use is similar to ``describeAlarms``.

====

[[delete-alarms,delete-alarms.title]]
== Delete Alarms

To delete CloudWatch alarms, call the AmazonCloudWatchClient's  `deleteAlarms` method with a link:sdk-for-java/v1/reference/com/amazonaws/services/cloudwatch/model/DeleteAlarmsRequest.html["DeleteAlarmsRequest", type="documentation"] containing one or more names of alarms that you want to delete.

*Imports*

[source,java]
----
import com.amazonaws.services.cloudwatch.AmazonCloudWatch;
import com.amazonaws.services.cloudwatch.AmazonCloudWatchClientBuilder;
import com.amazonaws.services.cloudwatch.model.DeleteAlarmsRequest;
import com.amazonaws.services.cloudwatch.model.DeleteAlarmsResult;
----

*Code*

[source,java]
----
final AmazonCloudWatch cw =
    AmazonCloudWatchClientBuilder.defaultClient();

DeleteAlarmsRequest request = new DeleteAlarmsRequest()
    .withAlarmNames(alarm_name);

DeleteAlarmsResult response = cw.deleteAlarms(request);
----


[[more-information,more-information.title]]
== More Information

* link:AmazonCloudWatch/latest/monitoring/AlarmThatSendsEmail.html["Creating pass:q[[.shared\]`CWlong`] Alarms", type="documentation"] in the {guide-cw-user}
* {https---docs-aws-amazon-com-AmazonCloudWatch-latest-APIReference-API-PutMetricAlarm-html}[PutMetricAlarm] in the {guide-cw-api}
* {https---docs-aws-amazon-com-AmazonCloudWatch-latest-APIReference-API-DescribeAlarms-html}[DescribeAlarms] in the {guide-cw-api}
* {https---docs-aws-amazon-com-AmazonCloudWatch-latest-APIReference-API-DeleteAlarms-html}[DeleteAlarms] in the {guide-cw-api}
