//!!NODE_ROOT <section>
include::../../includes.txt[]
:https---docs-aws-amazon-com-IAM-latest-APIReference-API-DeleteAccessKey-html: {url-doc-domain}IAM/latest/APIReference/API_DeleteAccessKey.html
:https---docs-aws-amazon-com-IAM-latest-APIReference-API-UpdateAccessKey-html: {url-doc-domain}IAM/latest/APIReference/API_UpdateAccessKey.html
:https---docs-aws-amazon-com-IAM-latest-APIReference-API-GetAccessKeyLastUsed-html: {url-doc-domain}IAM/latest/APIReference/API_GetAccessKeyLastUsed.html
:https---docs-aws-amazon-com-IAM-latest-APIReference-API-ListAccessKeys-html: {url-doc-domain}IAM/latest/APIReference/API_ListAccessKeys.html
:https---docs-aws-amazon-com-IAM-latest-APIReference-API-CreateAccessKey-html: {url-doc-domain}IAM/latest/APIReference/API_CreateAccessKey.html
:https---github-com-awsdocs-aws-doc-sdk-examples-blob-master-java-example-code-iam-src-main-java-aws-example-iam-DeleteAccessKey-java: {url-awsdocs-github}aws-doc-sdk-examples/blob/master/java/example_code/iam/src/main/java/aws/example/iam/DeleteAccessKey.java
:https---github-com-awsdocs-aws-doc-sdk-examples-blob-master-java-example-code-iam-src-main-java-aws-example-iam-UpdateAccessKey-java: {url-awsdocs-github}aws-doc-sdk-examples/blob/master/java/example_code/iam/src/main/java/aws/example/iam/UpdateAccessKey.java
:https---github-com-awsdocs-aws-doc-sdk-examples-blob-master-java-example-code-iam-src-main-java-aws-example-iam-AccessKeyLastUsed-java: {url-awsdocs-github}aws-doc-sdk-examples/blob/master/java/example_code/iam/src/main/java/aws/example/iam/AccessKeyLastUsed.java
:https---github-com-awsdocs-aws-doc-sdk-examples-blob-master-java-example-code-iam-src-main-java-aws-example-iam-ListAccessKeys-java: {url-awsdocs-github}aws-doc-sdk-examples/blob/master/java/example_code/iam/src/main/java/aws/example/iam/ListAccessKeys.java
:https---github-com-awsdocs-aws-doc-sdk-examples-blob-master-java-example-code-iam-src-main-java-aws-example-iam-CreateAccessKey-java: {url-awsdocs-github}aws-doc-sdk-examples/blob/master/java/example_code/iam/src/main/java/aws/example/iam/CreateAccessKey.java
[."topic"]
[[examples-iam-access-keys,examples-iam-access-keys.title]]
= [[managing-iam-access-keys, Managing IAM Access Keys]]Managing IAM Access Keys
:info_doctype: section
:info_title: Managing IAM Access Keys
:info_abstract: How to manage IAM access keys with the {sdk-java}.
:info_keywordset: sdk-javacodeexamplesIAM access keyscreatinglistingupdatingdeletinggetting last access time

[abstract]
--
How to manage IAM access keys with the {sdk-java}.
--

[[creating-an-access-key,creating-an-access-key.title]]
== Creating an Access Key

To create an IAM access key, call the AmazonIdentityManagementClient``createAccessKey`` method with an link:sdk-for-java/v1/reference/com/amazonaws/services/identitymanagement/model/CreateAccessKeyRequest.html["CreateAccessKeyRequest", type="documentation"] object.

`CreateAccessKeyRequest` has two constructors -- one that takes a user name and another with no parameters. If you use the version that takes no parameters, you must set the user name using the `withUserName` setter method before passing it to the `createAccessKey` method.

*Imports*

[source,java]
----
import com.amazonaws.services.identitymanagement.AmazonIdentityManagement;
import com.amazonaws.services.identitymanagement.AmazonIdentityManagementClientBuilder;
import com.amazonaws.services.identitymanagement.model.CreateAccessKeyRequest;
import com.amazonaws.services.identitymanagement.model.CreateAccessKeyResult;
----

*Code*

[source,java]
----
final AmazonIdentityManagement iam =
    AmazonIdentityManagementClientBuilder.defaultClient();

CreateAccessKeyRequest request = new CreateAccessKeyRequest()
    .withUserName(user);

CreateAccessKeyResult response = iam.createAccessKey(request);
----

See the  {https---github-com-awsdocs-aws-doc-sdk-examples-blob-master-java-example-code-iam-src-main-java-aws-example-iam-CreateAccessKey-java}[complete example] on GitHub.

[[listing-access-keys,listing-access-keys.title]]
== Listing Access Keys

To list the access keys for a given user, create a  link:sdk-for-java/v1/reference/com/amazonaws/services/identitymanagement/model/ListAccessKeysRequest.html["ListAccessKeysRequest", type="documentation"] object that contains the user name to list keys for, and pass it to the AmazonIdentityManagementClient's `listAccessKeys` method.

[NOTE]
====

If you do not supply a user name to ``listAccessKeys``, it will attempt to list access keys associated with the {AWS-account} that signed the request.

====

*Imports*

[source,java]
----
import com.amazonaws.services.identitymanagement.AmazonIdentityManagement;
import com.amazonaws.services.identitymanagement.AmazonIdentityManagementClientBuilder;
import com.amazonaws.services.identitymanagement.model.AccessKeyMetadata;
import com.amazonaws.services.identitymanagement.model.ListAccessKeysRequest;
import com.amazonaws.services.identitymanagement.model.ListAccessKeysResult;
----

*Code*

[source,java]
----
final AmazonIdentityManagement iam =
    AmazonIdentityManagementClientBuilder.defaultClient();

boolean done = false;
ListAccessKeysRequest request = new ListAccessKeysRequest()
        .withUserName(username);

while (!done) {

    ListAccessKeysResult response = iam.listAccessKeys(request);

    for (AccessKeyMetadata metadata :
            response.getAccessKeyMetadata()) {
        System.out.format("Retrieved access key %s",
                metadata.getAccessKeyId());
    }

    request.setMarker(response.getMarker());

    if (!response.getIsTruncated()) {
        done = true;
    }
}
----

The results of  `listAccessKeys` are paged (with a default maximum of 100 records per call). You can call `getIsTruncated` on the returned link:sdk-for-java/v1/reference/com/amazonaws/services/identitymanagement/model/ListAccessKeysResult.html["ListAccessKeysResult", type="documentation"] object to see if the query returned fewer results then are available. If so, then call `setMarker` on the `ListAccessKeysRequest` and pass it back to the next invocation of ``listAccessKeys``.

See the {https---github-com-awsdocs-aws-doc-sdk-examples-blob-master-java-example-code-iam-src-main-java-aws-example-iam-ListAccessKeys-java}[complete example] on GitHub.

[[retrieving-an-access-key-s-last-used-time,retrieving-an-access-key-s-last-used-time.title]]
== Retrieving an Access Key's Last Used Time

To get the time an access key was last used, call the AmazonIdentityManagementClient's  `getAccessKeyLastUsed` method with the access key's ID (which can be passed in using a link:sdk-for-java/v1/reference/com/amazonaws/services/identitymanagement/model/GetAccessKeyLastUsedRequest.html["GetAccessKeyLastUsedRequest", type="documentation"] object, or directly to the overload that takes the access key ID directly.

You can then use the returned link:sdk-for-java/v1/reference/com/amazonaws/services/identitymanagement/model/GetAccessKeyLastUsedResult.html["GetAccessKeyLastUsedResult", type="documentation"] object to retrieve the key's last used time.

*Imports*

[source,java]
----
import com.amazonaws.services.identitymanagement.AmazonIdentityManagement;
import com.amazonaws.services.identitymanagement.AmazonIdentityManagementClientBuilder;
import com.amazonaws.services.identitymanagement.model.GetAccessKeyLastUsedRequest;
import com.amazonaws.services.identitymanagement.model.GetAccessKeyLastUsedResult;
----

*Code*

[source,java]
----
final AmazonIdentityManagement iam =
    AmazonIdentityManagementClientBuilder.defaultClient();

GetAccessKeyLastUsedRequest request = new GetAccessKeyLastUsedRequest()
    .withAccessKeyId(access_id);

GetAccessKeyLastUsedResult response = iam.getAccessKeyLastUsed(request);

System.out.println("Access key was last used at: " +
        response.getAccessKeyLastUsed().getLastUsedDate());
----

See the  {https---github-com-awsdocs-aws-doc-sdk-examples-blob-master-java-example-code-iam-src-main-java-aws-example-iam-AccessKeyLastUsed-java}[complete example] on GitHub.

[[iam-access-keys-update,iam-access-keys-update.title]]
== Activating or Deactivating Access Keys

You can activate or deactivate an access key by creating an  link:sdk-for-java/v1/reference/com/amazonaws/services/identitymanagement/model/UpdateAccessKeyRequest.html["UpdateAccessKeyRequest", type="documentation"] object, providing the access key ID, optionally the user name, and the desired link:sdk-for-java/v1/reference/com/amazonaws/services/identitymanagement/model/StatusType.html["Status", type="documentation"], then passing the request object to the AmazonIdentityManagementClient's `updateAccessKey` method.

*Imports*

[source,java]
----
import com.amazonaws.services.identitymanagement.AmazonIdentityManagement;
import com.amazonaws.services.identitymanagement.AmazonIdentityManagementClientBuilder;
import com.amazonaws.services.identitymanagement.model.UpdateAccessKeyRequest;
import com.amazonaws.services.identitymanagement.model.UpdateAccessKeyResult;
----

*Code*

[source,java]
----
final AmazonIdentityManagement iam =
    AmazonIdentityManagementClientBuilder.defaultClient();

UpdateAccessKeyRequest request = new UpdateAccessKeyRequest()
    .withAccessKeyId(access_id)
    .withUserName(username)
    .withStatus(status);

UpdateAccessKeyResult response = iam.updateAccessKey(request);
----

See the  {https---github-com-awsdocs-aws-doc-sdk-examples-blob-master-java-example-code-iam-src-main-java-aws-example-iam-UpdateAccessKey-java}[complete example] on GitHub.

[[deleting-an-access-key,deleting-an-access-key.title]]
== Deleting an Access Key

To permanently delete an access key, call the AmazonIdentityManagementClient's  `deleteKey` method, providing it with a link:sdk-for-java/v1/reference/com/amazonaws/services/identitymanagement/model/DeleteAccessKeyRequest.html["DeleteAccessKeyRequest", type="documentation"] containing the access key's ID and username.

[NOTE]
====

Once deleted, a key can no longer be retrieved or used. To temporarily deactivate a key so that it can be activated again later, use xref:iam-access-keys-update[updateAccessKey,linkend=iam-access-keys-update] method instead.

====

*Imports*

[source,java]
----
import com.amazonaws.services.identitymanagement.AmazonIdentityManagement;
import com.amazonaws.services.identitymanagement.AmazonIdentityManagementClientBuilder;
import com.amazonaws.services.identitymanagement.model.DeleteAccessKeyRequest;
import com.amazonaws.services.identitymanagement.model.DeleteAccessKeyResult;
----

*Code*

[source,java]
----
final AmazonIdentityManagement iam =
    AmazonIdentityManagementClientBuilder.defaultClient();

DeleteAccessKeyRequest request = new DeleteAccessKeyRequest()
    .withAccessKeyId(access_key)
    .withUserName(username);

DeleteAccessKeyResult response = iam.deleteAccessKey(request);
----

See the  {https---github-com-awsdocs-aws-doc-sdk-examples-blob-master-java-example-code-iam-src-main-java-aws-example-iam-DeleteAccessKey-java}[complete example] on GitHub.

[[more-information,more-information.title]]
== More Information

* {https---docs-aws-amazon-com-IAM-latest-APIReference-API-CreateAccessKey-html}[CreateAccessKey] in the IAM API Reference
* {https---docs-aws-amazon-com-IAM-latest-APIReference-API-ListAccessKeys-html}[ListAccessKeys] in the IAM API Reference
* {https---docs-aws-amazon-com-IAM-latest-APIReference-API-GetAccessKeyLastUsed-html}[GetAccessKeyLastUsed] in the IAM API Reference
* {https---docs-aws-amazon-com-IAM-latest-APIReference-API-UpdateAccessKey-html}[UpdateAccessKey] in the IAM API Reference
* {https---docs-aws-amazon-com-IAM-latest-APIReference-API-DeleteAccessKey-html}[DeleteAccessKey] in the IAM API Reference
