//!!NODE_ROOT <section>
include::../../includes.txt[]
:https---docs-aws-amazon-com-AWSSimpleQueueService-latest-APIReference-API-SetQueueAttributes-html: {url-doc-domain}AWSSimpleQueueService/latest/APIReference/API_SetQueueAttributes.html
:https---docs-aws-amazon-com-AWSSimpleQueueService-latest-APIReference-API-ReceiveMessage-html: {url-doc-domain}AWSSimpleQueueService/latest/APIReference/API_ReceiveMessage.html
:https---docs-aws-amazon-com-AWSSimpleQueueService-latest-APIReference-API-CreateQueue-html: {url-doc-domain}AWSSimpleQueueService/latest/APIReference/API_CreateQueue.html
:https---github-com-awsdocs-aws-doc-sdk-examples-blob-master-java-example-code-sqs-src-main-java-aws-example-sqs-LongPolling-java: {url-awsdocs-github}aws-doc-sdk-examples/blob/master/java/example_code/sqs/src/main/java/aws/example/sqs/LongPolling.java

[."topic"]
[[examples-sqs-long-polling,examples-sqs-long-polling.title]]
= [[enabling-long-polling-for-sqs-message-queues, Enabling Long Polling for {SQS} Message Queues]]Enabling Long Polling for {SQS} Message Queues
:info_doctype: section
:info_title: Enabling Long Polling for {SQS} Message Queues
:info_abstract: How to enable long polling for {SQS} message queues.
:info_keywordset: sdk-javacode examplesSQSlong pollingqueue management

[abstract]
--
How to enable long polling for {SQS} message queues.
--

{SQS} uses  _short polling_ by default, querying only a subset of the servers--based on a weighted random distribution--to determine whether any messages are available for inclusion in the response.

Long polling helps reduce your cost of using {SQS} by reducing the number of empty responses when there are no messages available to return in reply to a ReceiveMessage request sent to an {SQS} queue and eliminating false empty responses.

[NOTE]
====

You can set a long polling frequency from __1-20 seconds__.

====

[[sqs-long-polling-create-queue,sqs-long-polling-create-queue.title]]
== Enabling Long Polling when Creating a Queue

To enable long polling when creating an {SQS} queue, set the  `ReceiveMessageWaitTimeSeconds` attribute on the link:sdk-for-java/v1/reference/com/amazonaws/services/sqs/model/CreateQueueRequest.html["CreateQueueRequest", type="documentation"] object before calling the AmazonSQS class' `createQueue` method.

*Imports*

[source,java]
----
import com.amazonaws.services.sqs.AmazonSQS;
import com.amazonaws.services.sqs.AmazonSQSClientBuilder;
import com.amazonaws.services.sqs.model.AmazonSQSException;
import com.amazonaws.services.sqs.model.CreateQueueRequest;
----

*Code*

[source,java]
----
final AmazonSQS sqs = AmazonSQSClientBuilder.defaultClient();

// Enable long polling when creating a queue
CreateQueueRequest create_request = new CreateQueueRequest()
        .withQueueName(queue_name)
        .addAttributesEntry("ReceiveMessageWaitTimeSeconds", "20");

try {
    sqs.createQueue(create_request);
} catch (AmazonSQSException e) {
    if (!e.getErrorCode().equals("QueueAlreadyExists")) {
        throw e;
    }
}
----

See the  {https---github-com-awsdocs-aws-doc-sdk-examples-blob-master-java-example-code-sqs-src-main-java-aws-example-sqs-LongPolling-java}[complete example] on GitHub.

[[sqs-long-polling-existing-queue,sqs-long-polling-existing-queue.title]]
== Enabling Long Polling on an Existing Queue

In addition to enabling long polling when creating a queue, you can also enable it on an existing queue by setting  `ReceiveMessageWaitTimeSeconds` on the link:sdk-for-java/v1/reference/com/amazonaws/services/sqs/model/SetQueueAttributesRequest.html["SetQueueAttributesRequest", type="documentation"] before calling the AmazonSQS class' `setQueueAttributes` method.

*Imports*

[source,java]
----
import com.amazonaws.services.sqs.model.SetQueueAttributesRequest;
----

*Code*

[source,java]
----
SetQueueAttributesRequest set_attrs_request = new SetQueueAttributesRequest()
        .withQueueUrl(queue_url)
        .addAttributesEntry("ReceiveMessageWaitTimeSeconds", "20");
sqs.setQueueAttributes(set_attrs_request);
----

See the  {https---github-com-awsdocs-aws-doc-sdk-examples-blob-master-java-example-code-sqs-src-main-java-aws-example-sqs-LongPolling-java}[complete example] on GitHub.

[[sqs-long-polling-receive-message,sqs-long-polling-receive-message.title]]
== Enabling Long Polling on Message Receipt

You can enable long polling when receiving a message by setting the wait time in seconds on the  link:sdk-for-java/v1/reference/com/amazonaws/services/sqs/model/ReceiveMessageRequest.html["ReceiveMessageRequest", type="documentation"] that you supply to the AmazonSQS class' `receiveMessage` method.

[NOTE]
====

You should make sure that the {AWS} client's request timeout is larger than the maximum long poll time (20s) so that your `receiveMessage` requests don't time out while waiting for the next poll event!

====

*Imports*

[source,java]
----
import com.amazonaws.services.sqs.model.ReceiveMessageRequest;
----

*Code*

[source,java]
----
ReceiveMessageRequest receive_request = new ReceiveMessageRequest()
        .withQueueUrl(queue_url)
        .withWaitTimeSeconds(20);
sqs.receiveMessage(receive_request);
----

See the  {https---github-com-awsdocs-aws-doc-sdk-examples-blob-master-java-example-code-sqs-src-main-java-aws-example-sqs-LongPolling-java}[complete example] on GitHub.

[[more-info,more-info.title]]
== More Info

* link:AWSSimpleQueueService/latest/SQSDeveloperGuide/sqs-long-polling.html["pass:q[[.shared\]`SQS`] Long Polling", type="documentation"] in the {SQS} Developer Guide
* {https---docs-aws-amazon-com-AWSSimpleQueueService-latest-APIReference-API-CreateQueue-html}[CreateQueue] in the {SQS} API Reference
* {https---docs-aws-amazon-com-AWSSimpleQueueService-latest-APIReference-API-ReceiveMessage-html}[ReceiveMessage] in the {SQS} API Reference
* {https---docs-aws-amazon-com-AWSSimpleQueueService-latest-APIReference-API-SetQueueAttributes-html}[SetQueueAttributes] in the {SQS} API Reference
