//!!NODE_ROOT <section>
include::../../includes.txt[]
:https---github-com-awsdocs-aws-doc-sdk-examples-blob-master-java-example-code-s3-src-main-java-aws-example-s3-DeleteBucket-java: {url-awsdocs-github}aws-doc-sdk-examples/blob/master/java/example_code/s3/src/main/java/aws/example/s3/DeleteBucket.java
:https---github-com-awsdocs-aws-doc-sdk-examples-blob-master-java-example-code-s3-src-main-java-aws-example-s3-ListBuckets-java: {url-awsdocs-github}aws-doc-sdk-examples/blob/master/java/example_code/s3/src/main/java/aws/example/s3/ListBuckets.java
:https---github-com-awsdocs-aws-doc-sdk-examples-blob-master-java-example-code-s3-src-main-java-aws-example-s3-CreateBucket-java: {url-awsdocs-github}aws-doc-sdk-examples/blob/master/java/example_code/s3/src/main/java/aws/example/s3/CreateBucket.java

[."topic"]
[[examples-s3-buckets,examples-s3-buckets.title]]
= [[creating-listing-and-deleting-s3-buckets, Creating, Listing, and Deleting S3 Buckets]]Creating, Listing, and Deleting {S3} Buckets
:info_doctype: section
:info_title: Creating, Listing, and Deleting {S3} Buckets
:info_abstract: How to create, list, or delete a bucket using the {sdk-java}.
:info_keywordset: S3{sdk-java}createbucketlist bucketdelete bucketdelete versioned bucket

[abstract]
--
How to create, list, or delete a bucket using the {sdk-java}.
--

Every object (file) in {S3} must reside within a  __bucket__, which represents a collection (container) of objects. Each bucket is known by a _key_ (name), which must be unique. For detailed information about buckets and their configuration, see {url-s3-dev}UsingBucket.html[Working with {S3} Buckets] in the {guide-s3-dev}.

[NOTE]
====

Best Practice

We recommend that you enable the {url-s3-api}RESTBucketPUTlifecycle.html[AbortIncompleteMultipartUpload] lifecycle rule on your {S3} buckets.

This rule directs {S3} to abort multipart uploads that don't complete within a specified number of days after being initiated. When the set time limit is exceeded, {S3} aborts the upload and then deletes the incomplete upload data.

For more information, see {url-s3-ug}lifecycle-configuration-bucket-with-versioning.html[Lifecycle Configuration for a Bucket with Versioning] in the {guide-s3-ug}.

====

[NOTE]
====

These code examples assume that you understand the material in  xref:basics[Using the {sdk-java},linkend=basics] and have configured default {AWS} credentials using the information in xref:setup-credentials[Set up {AWS} Credentials and Region for Development,linkend=setup-credentials].

====

[[create-bucket,create-bucket.title]]
== Create a Bucket

Use the AmazonS3 client's  `createBucket` method. The new link:sdk-for-java/v1/reference/com/amazonaws/services/s3/model/Bucket.html["Bucket", type="documentation"] is returned. The `createBucket` method will raise an exception if the bucket already exists.

[NOTE]
====

To check whether a bucket already exists before attempting to create one with the same name, call the `doesBucketExist` method. It will return `true` if the bucket exists, and `false` otherwise.

====

*Imports*

[source,java]
----
import com.amazonaws.regions.Regions;
import com.amazonaws.services.s3.AmazonS3;
import com.amazonaws.services.s3.AmazonS3ClientBuilder;
import com.amazonaws.services.s3.model.AmazonS3Exception;
import com.amazonaws.services.s3.model.Bucket;

import java.util.List;
----

*Code*

[source,java]
----
if (s3.doesBucketExistV2(bucket_name)) {
    System.out.format("Bucket %s already exists.\n", bucket_name);
    b = getBucket(bucket_name);
} else {
    try {
        b = s3.createBucket(bucket_name);
    } catch (AmazonS3Exception e) {
        System.err.println(e.getErrorMessage());
    }
}
return b;
----

See the  {https---github-com-awsdocs-aws-doc-sdk-examples-blob-master-java-example-code-s3-src-main-java-aws-example-s3-CreateBucket-java}[complete example] on GitHub.

[[list-buckets,list-buckets.title]]
== List Buckets

Use the AmazonS3 client's  `listBucket` method. If successful, a list of link:sdk-for-java/v1/reference/com/amazonaws/services/s3/model/Bucket.html["Bucket", type="documentation"] is returned.

*Imports*

[source,java]
----
import com.amazonaws.regions.Regions;
import com.amazonaws.services.s3.AmazonS3;
import com.amazonaws.services.s3.AmazonS3ClientBuilder;
import com.amazonaws.services.s3.model.Bucket;

import java.util.List;
----

*Code*

[source,java]
----
List<Bucket> buckets = s3.listBuckets();
System.out.println("Your {S3} buckets are:");
for (Bucket b : buckets) {
    System.out.println("* " + b.getName());
}
----

See the  {https---github-com-awsdocs-aws-doc-sdk-examples-blob-master-java-example-code-s3-src-main-java-aws-example-s3-ListBuckets-java}[complete example] on GitHub.

[[delete-bucket,delete-bucket.title]]
== Delete a Bucket

Before you can delete an {S3} bucket, you must ensure that the bucket is empty or an error will result. If you have a  {url-s3-dev}Versioning.html[versioned bucket], you must also delete any versioned objects associated with the bucket.

[NOTE]
====

The {https---github-com-awsdocs-aws-doc-sdk-examples-blob-master-java-example-code-s3-src-main-java-aws-example-s3-DeleteBucket-java}[complete example] includes each of these steps in order, providing a complete solution for deleting an {S3} bucket and its contents.

====

[.topiclist-abbrev]
[[Topic List]]


[[remove-objects-from-an-unversioned-bucket-before-deleting-it,remove-objects-from-an-unversioned-bucket-before-deleting-it.title]]
=== Remove Objects from an Unversioned Bucket Before Deleting It

Use the AmazonS3 client's  `listObjects` method to retrieve the list of objects and `deleteObject` to delete each one.

*Imports*

[source,java]
----
import com.amazonaws.AmazonServiceException;
import com.amazonaws.regions.Regions;
import com.amazonaws.services.s3.AmazonS3;
import com.amazonaws.services.s3.AmazonS3ClientBuilder;
import com.amazonaws.services.s3.model.*;

import java.util.Iterator;
----

*Code*

[source,java]
----
System.out.println(" - removing objects from bucket");
ObjectListing object_listing = s3.listObjects(bucket_name);
while (true) {
    for (Iterator<?> iterator =
         object_listing.getObjectSummaries().iterator();
         iterator.hasNext(); ) {
        S3ObjectSummary summary = (S3ObjectSummary) iterator.next();
        s3.deleteObject(bucket_name, summary.getKey());
    }

    // more object_listing to retrieve?
    if (object_listing.isTruncated()) {
        object_listing = s3.listNextBatchOfObjects(object_listing);
    } else {
        break;
    }
}
----

See the  {https---github-com-awsdocs-aws-doc-sdk-examples-blob-master-java-example-code-s3-src-main-java-aws-example-s3-DeleteBucket-java}[complete example] on GitHub.

[[remove-objects-from-a-versioned-bucket-before-deleting-it,remove-objects-from-a-versioned-bucket-before-deleting-it.title]]
=== Remove Objects from a Versioned Bucket Before Deleting It

If you're using a  {url-s3-dev}Versioning.html[versioned bucket], you also need to remove any stored versions of the objects in the bucket before the bucket can be deleted.

Using a pattern similar to the one used when removing objects within a bucket, remove versioned objects by using the AmazonS3 client's `listVersions` method to list any versioned objects, and then `deleteVersion` to delete each one.

*Imports*

[source,java]
----
import com.amazonaws.AmazonServiceException;
import com.amazonaws.regions.Regions;
import com.amazonaws.services.s3.AmazonS3;
import com.amazonaws.services.s3.AmazonS3ClientBuilder;
import com.amazonaws.services.s3.model.*;

import java.util.Iterator;
----

*Code*

[source,java]
----
System.out.println(" - removing versions from bucket");
VersionListing version_listing = s3.listVersions(
        new ListVersionsRequest().withBucketName(bucket_name));
while (true) {
    for (Iterator<?> iterator =
         version_listing.getVersionSummaries().iterator();
         iterator.hasNext(); ) {
        S3VersionSummary vs = (S3VersionSummary) iterator.next();
        s3.deleteVersion(
                bucket_name, vs.getKey(), vs.getVersionId());
    }

    if (version_listing.isTruncated()) {
        version_listing = s3.listNextBatchOfVersions(
                version_listing);
    } else {
        break;
    }
}
----

See the  {https---github-com-awsdocs-aws-doc-sdk-examples-blob-master-java-example-code-s3-src-main-java-aws-example-s3-DeleteBucket-java}[complete example] on GitHub.

[[delete-an-empty-bucket,delete-an-empty-bucket.title]]
=== Delete an Empty Bucket

Once you remove the objects from a bucket (including any versioned objects), you can delete the bucket itself by using the AmazonS3 client's  `deleteBucket` method.

*Imports*

[source,java]
----
import com.amazonaws.AmazonServiceException;
import com.amazonaws.regions.Regions;
import com.amazonaws.services.s3.AmazonS3;
import com.amazonaws.services.s3.AmazonS3ClientBuilder;
import com.amazonaws.services.s3.model.*;

import java.util.Iterator;
----

*Code*

[source,java]
----
System.out.println(" OK, bucket ready to delete!");
s3.deleteBucket(bucket_name);
----

See the  {https---github-com-awsdocs-aws-doc-sdk-examples-blob-master-java-example-code-s3-src-main-java-aws-example-s3-DeleteBucket-java}[complete example] on GitHub.