//!!NODE_ROOT <section>
include::../../includes.txt[]
:https---docs-aws-amazon-com-AmazonCloudWatch-latest-APIReference-API-DisableAlarmActions-html: {url-cw-api}API_DisableAlarmActions.html
:https---docs-aws-amazon-com-AmazonCloudWatch-latest-APIReference-API-EnableAlarmActions-html: {url-cw-api}API_EnableAlarmActions.html
:https---docs-aws-amazon-com-AmazonCloudWatch-latest-APIReference-API-PutMetricAlarm-html: {url-cw-api}API_PutMetricAlarm.html

[."topic"]
[[examples-cloudwatch-use-alarm-actions,examples-cloudwatch-use-alarm-actions.title]]
= [[using-alarm-actions-in-cw, Using Alarm Actions in CloudWatch]]Using Alarm Actions in CloudWatch
:info_doctype: section
:info_title: Using Alarm Actions in CloudWatch
:info_abstract: How to enable or disable alarm actions for {CWlong} with the {sdk-java}.
:info_keywordset: cloudwatch alarmsenable alarmsdisable alarmscode examples

[abstract]
--
How to enable or disable alarm actions for {CWlong} with the {sdk-java}.
--

Using CloudWatch alarm actions, you can create alarms that perform actions such as automatically stopping, terminating, rebooting, or recovering {EC2} instances.

[NOTE]
====

Alarm actions can be added to an alarm by using the link:sdk-for-java/v1/reference/com/amazonaws/services/cloudwatch/model/PutMetricAlarmRequest.html["PutMetricAlarmRequest", type="documentation"]'s `setAlarmActions` method when xref:examples-cloudwatch-create-alarms[creating an alarm,linkend=examples-cloudwatch-create-alarms].

====

[[enable-alarm-actions,enable-alarm-actions.title]]
== Enable Alarm Actions

To enable alarm actions for a CloudWatch alarm, call the AmazonCloudWatchClient's  `enableAlarmActions` with a link:sdk-for-java/v1/reference/com/amazonaws/services/cloudwatch/model/EnableAlarmActionsRequest.html["EnableAlarmActionsRequest", type="documentation"] containing one or more names of alarms whose actions you want to enable.

*Imports*

[source,java]
----
import com.amazonaws.services.cloudwatch.AmazonCloudWatch;
import com.amazonaws.services.cloudwatch.AmazonCloudWatchClientBuilder;
import com.amazonaws.services.cloudwatch.model.EnableAlarmActionsRequest;
import com.amazonaws.services.cloudwatch.model.EnableAlarmActionsResult;
----

*Code*

[source,java]
----
final AmazonCloudWatch cw =
    AmazonCloudWatchClientBuilder.defaultClient();

EnableAlarmActionsRequest request = new EnableAlarmActionsRequest()
    .withAlarmNames(alarm);

EnableAlarmActionsResult response = cw.enableAlarmActions(request);
----


[[disable-alarm-actions,disable-alarm-actions.title]]
== Disable Alarm Actions

To disable alarm actions for a CloudWatch alarm, call the AmazonCloudWatchClient's  `disableAlarmActions` with a link:sdk-for-java/v1/reference/com/amazonaws/services/cloudwatch/model/DisableAlarmActionsRequest.html["DisableAlarmActionsRequest", type="documentation"] containing one or more names of alarms whose actions you want to disable.

*Imports*

[source,java]
----
import com.amazonaws.services.cloudwatch.AmazonCloudWatch;
import com.amazonaws.services.cloudwatch.AmazonCloudWatchClientBuilder;
import com.amazonaws.services.cloudwatch.model.DisableAlarmActionsRequest;
import com.amazonaws.services.cloudwatch.model.DisableAlarmActionsResult;
----

*Code*

[source,java]
----
final AmazonCloudWatch cw =
    AmazonCloudWatchClientBuilder.defaultClient();

DisableAlarmActionsRequest request = new DisableAlarmActionsRequest()
    .withAlarmNames(alarmName);

DisableAlarmActionsResult response = cw.disableAlarmActions(request);
----


[[more-information,more-information.title]]
== More Information

* link:AmazonCloudWatch/latest/monitoring/UsingAlarmActions.html["Create Alarms to Stop, Terminate, Reboot, or Recover an Instance", type="documentation"] in the {guide-cw-user}
* {https---docs-aws-amazon-com-AmazonCloudWatch-latest-APIReference-API-PutMetricAlarm-html}[PutMetricAlarm] in the {guide-cw-api}
* {https---docs-aws-amazon-com-AmazonCloudWatch-latest-APIReference-API-EnableAlarmActions-html}[EnableAlarmActions] in the {guide-cw-api}
* {https---docs-aws-amazon-com-AmazonCloudWatch-latest-APIReference-API-DisableAlarmActions-html}[DisableAlarmActions] in the {guide-cw-api}
