//!!NODE_ROOT <section>
include::../../includes.txt[]
:https---docs-aws-amazon-com-AmazonCloudWatch-latest-APIReference-API-PutMetricData-html: {url-cw-api}API_PutMetricData.html
:https---docs-aws-amazon-com-AmazonCloudWatch-latest-monitoring-working-with-metrics-html: {url-doc-domain}AmazonCloudWatch/latest/monitoring/working_with_metrics.html

[."topic"]
[[examples-cloudwatch-publish-custom-metrics,examples-cloudwatch-publish-custom-metrics.title]]
= [[publishing-custom-metric-data, Publishing Custom Metric Data]]Publishing Custom Metric Data
:info_doctype: section
:info_title: Publishing Custom Metric Data
:info_abstract: How to publish your own custom metric data to {CWlong} using the {sdk-java}.
:info_keywordset: sdk-javacustommetricscode examples

[abstract]
--
How to publish your own custom metric data to {CWlong} using the {sdk-java}.
--

A number of {AWS-services} publish
link:AmazonCloudWatch/latest/monitoring/aws-namespaces.html["their own metrics", type="documentation"]
in namespaces beginning with "``AWS``" You can also publish custom metric data using
your own namespace (as long as it doesn't begin with "``AWS``").

[[publish-custom-metric-data,publish-custom-metric-data.title]]
== Publish Custom Metric Data

To publish your own metric data, call the AmazonCloudWatchClient's  `putMetricData` method with a
link:sdk-for-java/v1/reference/com/amazonaws/services/cloudwatch/model/PutMetricDataRequest.html["PutMetricDataRequest", type="documentation"].
The `PutMetricDataRequest` must include the custom namespace to use for the data, and information
about the data point itself in a
link:sdk-for-java/v1/reference/com/amazonaws/services/cloudwatch/model/MetricDatum.html["MetricDatum", type="documentation"] object.

[NOTE]
====

You cannot specify a namespace that begins with "``AWS``". Namespaces that begin with
"``AWS``" are reserved for use by {AWSlong} products.

====

*Imports*

[source,java]
----
import com.amazonaws.services.cloudwatch.AmazonCloudWatch;
import com.amazonaws.services.cloudwatch.AmazonCloudWatchClientBuilder;
import com.amazonaws.services.cloudwatch.model.Dimension;
import com.amazonaws.services.cloudwatch.model.MetricDatum;
import com.amazonaws.services.cloudwatch.model.PutMetricDataRequest;
import com.amazonaws.services.cloudwatch.model.PutMetricDataResult;
import com.amazonaws.services.cloudwatch.model.StandardUnit;
----

*Code*

[source,java]
----
final AmazonCloudWatch cw =
    AmazonCloudWatchClientBuilder.defaultClient();

Dimension dimension = new Dimension()
    .withName("UNIQUE_PAGES")
    .withValue("URLS");

MetricDatum datum = new MetricDatum()
    .withMetricName("PAGES_VISITED")
    .withUnit(StandardUnit.None)
    .withValue(data_point)
    .withDimensions(dimension);

PutMetricDataRequest request = new PutMetricDataRequest()
    .withNamespace("SITE/TRAFFIC")
    .withMetricData(datum);

PutMetricDataResult response = cw.putMetricData(request);
----


[[more-information,more-information.title]]
== More Information

* {https---docs-aws-amazon-com-AmazonCloudWatch-latest-monitoring-working-with-metrics-html}[Using {CWlong} Metrics] in the {guide-cw-user}.
* link:AmazonCloudWatch/latest/monitoring/aws-namespaces.html["pass:q[[.shared\]`AWS`] Namespaces", type="documentation"] in the {guide-cw-user}.
* {https---docs-aws-amazon-com-AmazonCloudWatch-latest-APIReference-API-PutMetricData-html}[PutMetricData] in the {guide-cw-api}.
