//!!NODE_ROOT <section>
include::../../includes.txt[]
:https---docs-aws-amazon-com-AWSEC2-latest-APIReference-API-DescribeAvailabilityZones-html: {url-doc-domain}AWSEC2/latest/APIReference/API_DescribeAvailabilityZones.html
:https---docs-aws-amazon-com-AWSEC2-latest-APIReference-API-DescribeRegions-html: {url-doc-domain}AWSEC2/latest/APIReference/API_DescribeRegions.html
:https---github-com-awsdocs-aws-doc-sdk-examples-blob-master-java-example-code-ec2-src-main-java-aws-example-ec2-DescribeAccount-java: {url-awsdocs-github}aws-doc-sdk-examples/blob/master/java/example_code/ec2/src/main/java/aws/example/ec2/DescribeAccount.java
:https---github-com-awsdocs-aws-doc-sdk-examples-blob-master-java-example-code-ec2-src-main-java-aws-example-ec2-DescribeRegionsAndZones-java: {url-awsdocs-github}aws-doc-sdk-examples/blob/master/java/example_code/ec2/src/main/java/aws/example/ec2/DescribeRegionsAndZones.java

[."topic"]
[[examples-ec2-regions-zones,examples-ec2-regions-zones.title]]
= [[use-regions-and-availability-zones, Use regions and availability zones]]Use regions and availability zones
:info_doctype: section
:info_title: Use regions and availability zones
:info_abstract: How to list EC2 regions and availability zones using the {sdk-java}.
:info_keywordset: sdk-javacodeexamplesEC2list regionsdescribe regionslist availability zonesdescribe availability zones

[abstract]
--
How to list EC2 regions and availability zones using the {sdk-java}.
--

[[describe-regions,describe-regions.title]]
== Describe regions

To list the Regions available to your account, call the AmazonEC2Client's  `describeRegions` method. It returns a link:sdk-for-java/v1/reference/com/amazonaws/services/ec2/model/DescribeRegionsResult.html["DescribeRegionsResult", type="documentation"]. Call the returned object's `getRegions` method to get a list of link:sdk-for-java/v1/reference/com/amazonaws/services/ec2/model/Region.html["Region", type="documentation"] objects that represent each Region.

*Imports*

[source,java]
----
import com.amazonaws.services.ec2.AmazonEC2;
import com.amazonaws.services.ec2.AmazonEC2ClientBuilder;
import com.amazonaws.services.ec2.model.DescribeRegionsResult;
import com.amazonaws.services.ec2.model.Region;
import com.amazonaws.services.ec2.model.AvailabilityZone;
import com.amazonaws.services.ec2.model.DescribeAvailabilityZonesResult;
----

*Code*

[source,java]
----
DescribeRegionsResult regions_response = ec2.describeRegions();

for(Region region : regions_response.getRegions()) {
    System.out.printf(
        "Found region %s " +
        "with endpoint %s",
        region.getRegionName(),
        region.getEndpoint());
}
----

See the  {https---github-com-awsdocs-aws-doc-sdk-examples-blob-master-java-example-code-ec2-src-main-java-aws-example-ec2-DescribeRegionsAndZones-java}[complete example].

[[describe-availability-zones,describe-availability-zones.title]]
== Describe availability zones

To list each Availability Zone available to your account, call the AmazonEC2Client's  `describeAvailabilityZones` method. It returns a link:sdk-for-java/v1/reference/com/amazonaws/services/ec2/model/DescribeAvailabilityZonesResult.html["DescribeAvailabilityZonesResult", type="documentation"]. Call its `getAvailabilityZones` method to get a list of link:sdk-for-java/v1/reference/com/amazonaws/services/ec2/model/AvailabilityZone.html["AvailabilityZone", type="documentation"] objects that represent each Availability Zone.

*Imports*

[source,java]
----
import com.amazonaws.services.ec2.AmazonEC2;
import com.amazonaws.services.ec2.AmazonEC2ClientBuilder;
import com.amazonaws.services.ec2.model.DescribeRegionsResult;
import com.amazonaws.services.ec2.model.Region;
import com.amazonaws.services.ec2.model.AvailabilityZone;
import com.amazonaws.services.ec2.model.DescribeAvailabilityZonesResult;
----

*Code*

[source,java]
----
DescribeAvailabilityZonesResult zones_response =
    ec2.describeAvailabilityZones();

for(AvailabilityZone zone : zones_response.getAvailabilityZones()) {
    System.out.printf(
        "Found availability zone %s " +
        "with status %s " +
        "in region %s",
        zone.getZoneName(),
        zone.getState(),
        zone.getRegionName());
}
----

See the  {https---github-com-awsdocs-aws-doc-sdk-examples-blob-master-java-example-code-ec2-src-main-java-aws-example-ec2-DescribeRegionsAndZones-java}[complete example].

[[describe-accounts,describe-accounts.title]]
== Describe accounts

To describe your account, call the AmazonEC2Client's  `describeAccountAttributes` method. This method returns a link:sdk-for-java/v1/reference/com/amazonaws/services/ec2/model/DescribeAccountAttributesResult.html["DescribeAccountAttributesResult", type="documentation"] object. Invoke this objects `getAccountAttributes` method to get a list of link:sdk-for-java/v1/reference/com/amazonaws/services/ec2/model/AccountAttribute.html["AccountAttribute", type="documentation"] objects. You can iterate through the list to retrieve an link:sdk-for-java/v1/reference/com/amazonaws/services/ec2/model/AccountAttribute.html["AccountAttribute", type="documentation"] object.

You can get your account's attribute values by invoking the link:sdk-for-java/v1/reference/com/amazonaws/services/ec2/model/AccountAttribute.html["AccountAttribute", type="documentation"] object's `getAttributeValues` method. This method returns a list of link:sdk-for-java/v1/reference/com/amazonaws/services/ec2/model/AccountAttributeValue.html["AccountAttributeValue", type="documentation"] objects. You can iterate through this second list to display the value of attributes (see the following code example).

*Imports*

[source,java]
----
import com.amazonaws.services.ec2.AmazonEC2;
import com.amazonaws.services.ec2.AmazonEC2ClientBuilder;
import com.amazonaws.services.ec2.model.AccountAttributeValue;
import com.amazonaws.services.ec2.model.DescribeAccountAttributesResult;
import com.amazonaws.services.ec2.model.AccountAttribute;
import java.util.List;
import java.util.ListIterator;
----

*Code*

[source,java]
----
AmazonEC2 ec2 = AmazonEC2ClientBuilder.defaultClient();

try{
    DescribeAccountAttributesResult accountResults = ec2.describeAccountAttributes();
    List<AccountAttribute> accountList = accountResults.getAccountAttributes();

    for (ListIterator iter = accountList.listIterator(); iter.hasNext(); ) {

        AccountAttribute attribute = (AccountAttribute) iter.next();
        System.out.print("\n The name of the attribute is "+attribute.getAttributeName());
        List<AccountAttributeValue> values = attribute.getAttributeValues();

         //iterate through the attribute values
        for (ListIterator iterVals = values.listIterator(); iterVals.hasNext(); ) {
            AccountAttributeValue myValue = (AccountAttributeValue) iterVals.next();
            System.out.print("\n The value of the attribute is "+myValue.getAttributeValue());
        }
    }
    System.out.print("Done");
}
catch (Exception e)
{
    e.getStackTrace();
}
----

See the  {https---github-com-awsdocs-aws-doc-sdk-examples-blob-master-java-example-code-ec2-src-main-java-aws-example-ec2-DescribeAccount-java}[complete example] on GitHub.

[[more-information,more-information.title]]
== More information

* {url-ec2-user}using-regions-availability-zones.html[Regions and Availability Zones] in the {guide-ec2-user}
* {https---docs-aws-amazon-com-AWSEC2-latest-APIReference-API-DescribeRegions-html}[DescribeRegions] in the {EC2} API Reference
* {https---docs-aws-amazon-com-AWSEC2-latest-APIReference-API-DescribeAvailabilityZones-html}[DescribeAvailabilityZones] in the {EC2} API Reference
