//!!NODE_ROOT <section>
include::../../includes.txt[]

[."topic"]
[[java-dg-region-selection,java-dg-region-selection.title]]
= [[aws-region-selection, Region Selection]]{AWS-Region} Selection
:info_doctype: section
:info_title: {AWS-Region} Selection
:info_abstract: How to check service availability and choose an {AWS-Region} and specific endpoints.

[abstract]
--
How to check service availability and choose an {AWS-Region} and specific endpoints.
--

Regions enable you to access {AWS-services} that physically reside in a specific geographic area. This can be useful both for redundancy and to keep your data and applications running close to where you and your users will access them.

[[region-selection-query-service,region-selection-query-service.title]]
== Checking for Service Availability in a Region

To see if a particular {AWS-service} is available in a region, use the  `isServiceSupported` method on the region that you'd like to use.

[source,java]
----
Region.getRegion(Regions.US_WEST_2)
    .isServiceSupported(AmazonDynamoDB.ENDPOINT_PREFIX);
----

See the  link:sdk-for-java/v1/reference/com/amazonaws/regions/Regions.html["Regions", type="documentation"] class documentation for the regions you can specify, and use the endpoint
prefix of the service to query. Each service's endpoint prefix is defined in the service
interface. For example, the {DDB} endpoint prefix is defined in
link:sdk-for-java/v1/reference/com/amazonaws/services/dynamodbv2/AmazonDynamoDB.html["AmazonDynamoDB", type="documentation"].

[[region-selection-choose-region,region-selection-choose-region.title]]
== Choosing a Region

Beginning with version 1.4 of the {sdk-java}, you can specify a region name and the SDK will automatically choose an appropriate endpoint for you. To choose the endpoint yourself, see  xref:region-selection-choose-endpoint[Choosing a Specific Endpoint,linkend=region-selection-choose-endpoint].

To explicitly set a region, we recommend that you use the link:sdk-for-java/v1/reference/com/amazonaws/regions/Regions.html["Regions", type="documentation"] enum. This is an enumeration of all publicly available regions. To create a client with a region from the enum, use the following code.

[source,java]
----
AmazonEC2 ec2 = AmazonEC2ClientBuilder.standard()
                    .withRegion(Regions.US_WEST_2)
                    .build();
----

If the region you are attempting to use isn't in the  `Regions` enum, you can set the region using a _string_ that represents the name of the region.

[source,java]
----
AmazonEC2 ec2 = AmazonEC2ClientBuilder.standard()
                    .withRegion("{region_api_default}")
                    .build();
----

[NOTE]
====

After you build a client with the builder, it's  _immutable_ and the region __cannot be changed__. If you are working with multiple {AWS-Regions} for the same service, you should create multiple clients--one per region.

====

[[region-selection-choose-endpoint,region-selection-choose-endpoint.title]]
== Choosing a Specific Endpoint

Each {AWS} client can be configured to use a  _specific endpoint_ within a region by calling the `withEndpointConfiguration` method when creating the client.

For example, to configure the {S3} client to use the Europe (Ireland) Region, use the following code.

[source,java]
----
AmazonS3 s3 = AmazonS3ClientBuilder.standard()
     .withEndpointConfiguration(new EndpointConfiguration(
          "https://s3.eu-west-1.amazonaws.com",
          "eu-west-1"))
     .withCredentials(CREDENTIALS_PROVIDER)
     .build();
----

See  link:general/latest/gr/rande.html["Regions and Endpoints", type="documentation"] for the current list of regions and their corresponding endpoints for all {AWS-services}.

[[automatically-determine-the-aws-region-from-the-environment,automatically-determine-the-aws-region-from-the-environment.title]]
== Automatically Determine the Region from the Environment

[IMPORTANT]
====

This section applies only when using a  xref:creating-clients[client builder,linkend=creating-clients] to access {AWS-services}. {AWS} clients created by using the client constructor will not automatically determine region from the environment and will, instead, use the _default_ SDK region (USEast1).

====

When running on {EC2} or Lambda, you might want to configure clients to use the same region that your code is running on. This decouples your code from the environment it's running in and makes it easier to deploy your application to multiple regions for lower latency or redundancy.

_You must use client builders to have the SDK automatically detect the region your code is running in._

To use the default credential/region provider chain to determine the region from the environment, use the client builder's `defaultClient` method.

[source,java]
----
AmazonEC2 ec2 = AmazonEC2ClientBuilder.defaultClient();
----

This is the same as using  `standard` followed by ``build``.

[source,java]
----
AmazonEC2 ec2 = AmazonEC2ClientBuilder.standard()
                    .build();
----

If you don't explicitly set a region using the  `withRegion` methods, the SDK consults the default region provider chain to try and determine the region to use.

[[default-region-provider-chain,default-region-provider-chain.title]]
=== Default Region Provider Chain

*The following is the region lookup process:*

. Any explicit region set by using `withRegion` or `setRegion` on the builder itself takes precedence over anything else.
. The `AWS_REGION` environment variable is checked. If it's set, that region is used to configure the client.
+
NOTE: This environment variable is set by the {LAM} container.
. The SDK checks the {AWS} shared configuration file (usually located at [path]``~/.aws/config``). If the  _region_ property is present, the SDK uses it.
+
** The `AWS_CONFIG_FILE` environment variable can be used to customize the location of the shared config file.
** The `AWS_PROFILE` environment variable or the `aws.profile` system property can be used to customize the profile that is loaded by the SDK.
. The SDK attempts to use the {EC2} instance metadata service to determine the region of the currently running {EC2} instance.
. If the SDK still hasn't found a region by this point, client creation fails with an exception.

When developing {AWS} applications, a common approach is to use the  _shared configuration file_ (described in xref:credentials-default[Using the Default Credential Provider Chain,linkend=credentials-default]) to set the region for local development, and rely on the default region provider chain to determine the region when running on {AWS} infrastructure. This greatly simplifies client creation and keeps your application portable.