//!!NODE_ROOT <section>
include::../../includes.txt[]
[."topic"]
[[java-dg-samples,java-dg-samples.title]]
= [[code-samples-included-with-the-sdk, Code Samples included with the SDK]]Code Samples included with the SDK
:info_doctype: section
:info_title: Code Samples included with the SDK

The {sdk-java} comes packaged with code samples that demonstrate many of the features of the SDK in buildable, runnable programs. You can study or modify these to implement your own {AWS} solutions using the {sdk-java}.

[[how-to-get-the-samples,how-to-get-the-samples.title]]
== How to Get the Samples

The {sdk-java} code samples are provided in the  _samples_ directory of the SDK. If you downloaded and installed the SDK using the information in xref:setup-install[Set up the {sdk-java},linkend=setup-install], you already have the samples on your system.

You can also view the latest samples on the {sdk-java} GitHub repository, in the {url-aws-github}aws-sdk-java/tree/master/src/samples[src/samples] directory.

[[samples-cmdline,samples-cmdline.title]]
== Building and Running the Samples Using the Command Line

The samples include  http://ant.apache.org/[Ant] build scripts so that you can easily build and run them from the command line. Each sample also contains a README file in HTML format that contains information specific to each sample.

[NOTE]
====

If you're browsing the sample code on GitHub, click the *Raw* button in the source code display when viewing the sample's README.html file. In raw mode, the HTML will render as intended in your browser.

====

[[prerequisitessamples,prerequisitessamples.title]]
=== Prerequisites

Before running any of the {sdk-java} samples, you need to set your {AWS} credentials in the environment or with the {CLI}, as specified in  xref:setup-credentials[Set up {AWS} Credentials and Region for Development,linkend=setup-credentials]. The samples use the default credential provider chain whenever possible. So by setting your credentials in this way, you can avoid the risky practice of inserting your {AWS} credentials in files within the source code directory (where they may inadvertently be checked in and shared publicly).

[[running-the-samples,running-the-samples.title]]
=== Running the Samples
. Change to the directory containing the sample's code. For example, if you're in the root directory of the {AWS} SDK download and want to run the [path]``AwsConsoleApp`` sample, you would type:
+
[source,none]
----
cd samples/AwsConsoleApp
----
. Build and run the sample with Ant. The default build target performs both actions, so you can just enter:
+
[source,none]
----
ant
----

The sample prints information to standard output--for example:

[source,none]
----
===========================================

Welcome to the {AWS} Java SDK!

===========================================
You have access to 4 Availability Zones.

You have 0 {EC2} instance(s) running.

You have 13 Amazon SimpleDB domain(s) containing a total of 62 items.

You have 23 {S3} bucket(s), containing 44 objects with a total size of 154767691 bytes.
----


[[building-and-running-the-samples-using-the-eclipse-ide,building-and-running-the-samples-using-the-eclipse-ide.title]]
== Building and Running the Samples Using the Eclipse IDE

If you use the {TElong}, you can also start a new project in Eclipse based on the {sdk-java} or add the SDK to an existing Java project.

[[id1samples,id1samples.title]]
=== Prerequisites

After installing the {TElong}, we recommend configuring the Toolkit with your security credentials. You can do this anytime by choosing  *Preferences* from the  *Window* menu in Eclipse, and then choosing the  *{AWS} Toolkit* section.

[[id2,id2.title]]
=== Running the Samples
. Open Eclipse.
. Create a new {AWS} Java project. In Eclipse, on the *File* menu, choose  **New**, and then click  **Project**. The  *New Project* wizard opens.
. Expand the *{AWS}* category, then choose  **{AWS} Java Project**.
. Choose **Next**. The project settings page is displayed.
. Enter a name in the *Project Name* box. The {sdk-java} Samples group displays the samples available in the SDK, as described previously.
. Select the samples you want to include in your project by selecting each check box.
. Enter your {AWS} credentials. If you've already configured the {TElong} with your credentials, this is automatically filled in.
. Choose **Finish**. The project is created and added to the  **Project Explorer**.
. Choose the sample [path]``.java`` file you want to run. For example, for the {S3} sample, choose  [path]``S3Sample.java``.
. Choose *Run* from the  *Run* menu.
. Right-click the project in **Project Explorer**, point to  **Build Path**, and then choose  **Add Libraries**.
. Choose **{AWS} Java SDK**, choose  **Next**, and then follow the remaining on-screen instructions.
