//!!NODE_ROOT <section>
include::../../includes.txt[]
:https---docs-aws-amazon-com-IAM-latest-UserGuide-id-credentials-temp-use-resources-html: {url-doc-domain}IAM/latest/UserGuide/id_credentials_temp_use-resources.html
:https---docs-aws-amazon-com-IAM-latest-UserGuide-id-credentials-temp-control-access-html: {url-doc-domain}IAM/latest/UserGuide/id_credentials_temp_control-access.html
:https---docs-aws-amazon-com-IAM-latest-UserGuide-id-credentials-temp-request-html: {url-doc-domain}IAM/latest/UserGuide/id_credentials_temp_request.html
:https---docs-aws-amazon-com-AWSJavaSDK-latest-javadoc-com-amazonaws-services-securitytoken-AWSSecurityTokenService-html-getSessionToken-com-amazonaws-services-securitytoken-model-GetSessionTokenRequest-: {v1javadocs}com/amazonaws/services/securitytoken/AWSSecurityTokenService.html#getSessionToken-com.amazonaws.services.securitytoken.model.GetSessionTokenRequest-
:https---docs-aws-amazon-com-IAM-latest-UserGuide-id-credentials-temp-enable-regions-html: {url-doc-domain}IAM/latest/UserGuide/id_credentials_temp_enable-regions.html

[."topic"]
[[prog-services-sts,prog-services-sts.title]]
= [[getting-temporary-credentials-with-sts, Getting Temporary Credentials with STS]]Getting Temporary Credentials with {STS}
:info_doctype: section
:info_title: Getting Temporary Credentials with {STS}

You can use {STSlong} (link:iam/["pass:q[[.shared\]`STS`]", type="marketing"]) to get temporary, limited-privilege credentials that can be used to access {AWS-services}.

There are three steps involved in using {STS}:

. Activate a region (optional).
. Retrieve temporary security credentials from {STS}.
. Use the credentials to access {AWS} resources.


[NOTE]
====

Activating a region is  __optional__; by default, temporary security credentials are obtained from the global endpoint __sts.amazonaws.com__. However, to reduce latency and to enable you to build redundancy into your requests by using additional endpoints if an {STS} request to the first endpoint fails, you can activate regions that are geographically closer to your services or applications that use the credentials.

====

[[optional-activate-and-use-an-sts-region,optional-activate-and-use-an-sts-region.title]]
== (Optional) Activate and use an STS region

To activate a region for use with {STS}, use the {console} to select and activate the region.

. Sign in as an IAM user with permissions to perform IAM administration tasks `"iam:*"` for the account for which you want to activate {STS} in a new region.
. Open the IAM console and in the navigation pane click **Account Settings**.
. Expand the *STS Regions* list, find the region that you want to use, and then click  **Activate**.

After this, you can direct calls to the STS endpoint that is associated with that region.

[NOTE]
====

For more information about activating STS regions and for a list of the available {STS} endpoints, see {https---docs-aws-amazon-com-IAM-latest-UserGuide-id-credentials-temp-enable-regions-html}[Activating and Deactivating {STS} in an {AWS-Region}] in the {guide-iam-user}.

====

[[retrieving-an-sts-token,retrieving-an-sts-token.title]]
== Retrieve temporary security credentials from STS
. Create an link:sdk-for-java/v1/reference/com/amazonaws/services/securitytoken/AWSSecurityTokenServiceClient.html["AWSSecurityTokenServiceClient", type="documentation"] object:
+
[source,java]
----
AWSSecurityTokenService sts_client = AWSSecurityTokenServiceClientBuilder.standard().withEndpointConfiguration(new AwsClientBuilder.EndpointConfiguration("sts-endpoint.amazonaws.com", "signing-region")).build()
----
+
When creating the client with no arguments (``AWSSecurityTokenService sts_client = new AWSSecurityTokenServiceClientBuilder().standard().build();``), the default credential provider chain is used to retrieve credentials. You can provide a specific credential provider if you want. For more information, see <<credentials,Providing {AWS} Credentials in the {sdk-java}>>.
. Create a link:sdk-for-java/v1/reference/com/amazonaws/services/securitytoken/model/GetSessionTokenRequest.html["GetSessionTokenRequest", type="documentation"] object, and optionally set the duration in seconds for which the temporary credentials are valid:
=======
+
[source,java]
----
GetSessionTokenRequest session_token_request = new GetSessionTokenRequest();
session_token_request.setDurationSeconds(7200); // optional.
----
+

The duration of temporary credentials can range from 900 seconds (15 minutes) to 129600 seconds (36 hours) for IAM users. If a duration isn't specified, then 43200 seconds (12 hours) is used by default.
+

For a root {AWS-account}, the valid range of temporary credentials is from 900 to 3600 seconds (1 hour), with a default value of 3600 seconds if no duration is specified.
+
IMPORTANT: It is __strongly recommended__, from a security standpoint, that you _use IAM users_ instead of the root account for {AWS} access. For more information, see IAM Best Practices in the {guide-iam-user}.
. Call {https---docs-aws-amazon-com-AWSJavaSDK-latest-javadoc-com-amazonaws-services-securitytoken-AWSSecurityTokenService-html-getSessionToken-com-amazonaws-services-securitytoken-model-GetSessionTokenRequest-}[getSessionToken] on the STS client to get a session token, using the `GetSessionTokenRequest` object:
+
[source,java]
----
GetSessionTokenResult session_token_result =
    sts_client.getSessionToken(session_token_request);
----
. Get session credentials using the result of the call to ``getSessionToken``:
+
[source,java]
----
Credentials session_creds = session_token_result.getCredentials();
----

The session credentials provide access only for the duration that was specified by the  `GetSessionTokenRequest` object. Once the credentials expire, you will need to call `getSessionToken` again to obtain a new session token for continued access to {AWS}.

[[use-the-token-to-access-aws-resources,use-the-token-to-access-aws-resources.title]]
== Use the temporary credentials to access Amazon resources

Once you have temporary security credentials, you can use them to initialize an {AWS-service} client to use its resources, using the technique described in  xref:credentials-explicit[Explicitly Specifying Credentials,linkend=credentials-explicit].

For example, to create an S3 client using temporary service credentials:

[source,java]
----
BasicSessionCredentials sessionCredentials = new BasicSessionCredentials(
   session_creds.getAccessKeyId(),
   session_creds.getSecretAccessKey(),
   session_creds.getSessionToken());

AmazonS3 s3 = AmazonS3ClientBuilder.standard()
                        .withCredentials(new AWSStaticCredentialsProvider(sessionCredentials))
                        .build();
----

You can now use the  `AmazonS3` object to make {S3} requests.

[[for-more-information,for-more-information.title]]
== For more information

For more information about how to use temporary security credentials to access {AWS} resources, visit the following sections in the {guide-iam-user}:



* {https---docs-aws-amazon-com-IAM-latest-UserGuide-id-credentials-temp-request-html}[Requesting Temporary Security Credentials]
* {https---docs-aws-amazon-com-IAM-latest-UserGuide-id-credentials-temp-control-access-html}[Controlling Permissions for Temporary Security Credentials]
* {https---docs-aws-amazon-com-IAM-latest-UserGuide-id-credentials-temp-use-resources-html}[Using Temporary Security Credentials to Request Access to {AWS} Resources]
* {https---docs-aws-amazon-com-IAM-latest-UserGuide-id-credentials-temp-enable-regions-html}[Activating and Deactivating {STS} in an {AWS-Region}]
