//!!NODE_ROOT <chapter>
include::../../includes.txt[]
[[prog-services,prog-services.title]]
= [[sdk-java-code-examples, SDK for Java Code Examples]]{sdk-java} Code Examples
:doctype: book
:sectnums:
:toc: left
:icons: font
:experimental:
:idprefix:
:idseparator: -
:sourcedir: .
:info_doctype: chapter
:info_title: {sdk-java} Code Examples
:info_titleabbrev: Code Examples

This section provides tutorials and examples of using the {sdk-java} v1 to program {AWS-services}.

Find the source code for these examples and others in the {AWS} documentation {url-awsdocs-github}aws-doc-sdk-examples[code examples repository on GitHub].

To propose a new code example for the {AWS} documentation team to consider producing, create a new request. The team is looking to produce code examples that cover broader scenarios and use cases, versus simple code snippets that cover only individual API calls. For instructions, see the "`Proposing new code examples`" section in the {url-awsdocs-github}aws-doc-sdk-examples/blob/master/README.rst[Readme on GitHub].

[[aws-sdk-for-java-2-x,aws-sdk-for-java-2-x.title]]
== {sdkjavav2}

In 2018, {AWS} released {sdk-java} v2. For more {AWS} examples, see the
link:sdk-for-java/v2/developer-guide/welcome.html["pass:q[[.shared\]`Javalong`\ 2.x Developer
Guide", type="documentation"].

[NOTE]
====

See xref:additional-resources[Additional Documentation and Resources,linkend=additional-resources] for more examples and additional resources available for {sdk-java} developers!

====

[.topiclist-abbrev]
[[Topic List]]


include::examples-cloudwatch.adoc[leveloffset=+1]


include::examples-dynamodb.adoc[leveloffset=+1]


include::prog-services-ec2.adoc[leveloffset=+1]


include::examples-iam.adoc[leveloffset=+1]


include::lambda-examples.adoc[leveloffset=+1]


include::examples-pinpoint.adoc[leveloffset=+1]


include::examples-s3.adoc[leveloffset=+1]


include::examples-sqs.adoc[leveloffset=+1]


include::prog-services-swf.adoc[leveloffset=+1]


include::java-dg-samples.adoc[leveloffset=+1]
