//!!NODE_ROOT <section>
include::../../includes.txt[]
:https---docs-aws-amazon-com-AWSJavaSDK-latest-javadoc-com-amazonaws-services-ec2-AmazonEC2Client-html-runInstances-com-amazonaws-services-ec2-model-RunInstancesRequest-: {v1javadocs}com/amazonaws/services/ec2/AmazonEC2Client.html#runInstances-com.amazonaws.services.ec2.model.RunInstancesRequest-
:https---docs-aws-amazon-com-AWSJavaSDK-latest-javadoc-com-amazonaws-services-ec2-model-RunInstancesRequest-html-withSecurityGroups-java-util-Collection-: {v1javadocs}com/amazonaws/services/ec2/model/RunInstancesRequest.html#withSecurityGroups-java.util.Collection-
:https---docs-aws-amazon-com-AWSJavaSDK-latest-javadoc-com-amazonaws-services-ec2-model-RunInstancesRequest-html-withKeyName-java-lang-String-: {v1javadocs}com/amazonaws/services/ec2/model/RunInstancesRequest.html#withKeyName-java.lang.String-
:https---docs-aws-amazon-com-AWSJavaSDK-latest-javadoc-com-amazonaws-services-ec2-model-RunInstancesRequest-html-withMaxCount-java-lang-Integer-: {v1javadocs}com/amazonaws/services/ec2/model/RunInstancesRequest.html#withMaxCount-java.lang.Integer-
:https---docs-aws-amazon-com-AWSJavaSDK-latest-javadoc-com-amazonaws-services-ec2-model-RunInstancesRequest-html-withMinCount-java-lang-Integer-: {v1javadocs}com/amazonaws/services/ec2/model/RunInstancesRequest.html#withMinCount-java.lang.Integer-
:https---docs-aws-amazon-com-AWSJavaSDK-latest-javadoc-com-amazonaws-services-ec2-model-RunInstancesRequest-html-withInstanceType-java-lang-String-: {v1javadocs}com/amazonaws/services/ec2/model/RunInstancesRequest.html#withInstanceType-java.lang.String-
:https---docs-aws-amazon-com-AWSJavaSDK-latest-javadoc-com-amazonaws-services-ec2-model-RunInstancesRequest-html-withImageId-java-lang-String-: {v1javadocs}com/amazonaws/services/ec2/model/RunInstancesRequest.html#withImageId-java.lang.String-

[."topic"]
[[run-instance,run-instance.title]]
= [[run-an-ec2-instance, Run an EC2 Instance]]Run an {EC2} Instance
:info_doctype: section
:info_title: Run an {EC2} Instance

Use the following procedure to launch one or more identically configured EC2 instances from the same Amazon Machine Image (AMI). After you create your EC2 instances, you can check their status. After your EC2 instances are running, you can connect to them.

. Create and initialize a link:sdk-for-java/v1/reference/com/amazonaws/services/ec2/model/RunInstancesRequest.html["RunInstancesRequest", type="documentation"] instance. Make sure that the AMI, key pair, and security group that you specify exist in the region that you specified when you created the client object.
+
[source,java]
----
RunInstancesRequest runInstancesRequest =
   new RunInstancesRequest();

runInstancesRequest.withImageId("ami-a9d09ed1")
                   .withInstanceType(InstanceType.T1Micro)
                   .withMinCount(1)
                   .withMaxCount(1)
                   .withKeyName("my-key-pair")
                   .withSecurityGroups("my-security-group");
----
+

{https---docs-aws-amazon-com-AWSJavaSDK-latest-javadoc-com-amazonaws-services-ec2-model-RunInstancesRequest-html-withImageId-java-lang-String-}[withImageId]:::
** The ID of the AMI. To learn how to find public AMIs provided by Amazon or create your own, see {url-ec2-user}AMIs.html[Amazon Machine Image (AMI)].


{https---docs-aws-amazon-com-AWSJavaSDK-latest-javadoc-com-amazonaws-services-ec2-model-RunInstancesRequest-html-withInstanceType-java-lang-String-}[withInstanceType]:::
** An instance type that is compatible with the specified AMI. For more information, see {url-ec2-user}instance-types.html[Instance Types] in the {guide-ec2-user}.


{https---docs-aws-amazon-com-AWSJavaSDK-latest-javadoc-com-amazonaws-services-ec2-model-RunInstancesRequest-html-withMinCount-java-lang-Integer-}[withMinCount]:::
** The minimum number of EC2 instances to launch. If this is more instances than {EC2} can launch in the target Availability Zone, {EC2} launches no instances.


{https---docs-aws-amazon-com-AWSJavaSDK-latest-javadoc-com-amazonaws-services-ec2-model-RunInstancesRequest-html-withMaxCount-java-lang-Integer-}[withMaxCount]:::
** The maximum number of EC2 instances to launch. If this is more instances than {EC2} can launch in the target Availability Zone, {EC2} launches the largest possible number of instances above ``MinCount``. You can launch between 1 and the maximum number of instances you're allowed for the instance type. For more information, see How many instances can I run in {EC2} in the {EC2} General FAQ.


{https---docs-aws-amazon-com-AWSJavaSDK-latest-javadoc-com-amazonaws-services-ec2-model-RunInstancesRequest-html-withKeyName-java-lang-String-}[withKeyName]:::
** The name of the EC2 key pair. If you launch an instance without specifying a key pair, you can't connect to it. For more information, see xref:create-key-pair[Create a Key Pair,linkend=create-key-pair].


{https---docs-aws-amazon-com-AWSJavaSDK-latest-javadoc-com-amazonaws-services-ec2-model-RunInstancesRequest-html-withSecurityGroups-java-util-Collection-}[withSecurityGroups]:::
** One or more security groups. For more information, see xref:create-security-group[Create an {EC2} Security Group,linkend=create-security-group].
. Launch the instances by passing the request object to the {https---docs-aws-amazon-com-AWSJavaSDK-latest-javadoc-com-amazonaws-services-ec2-AmazonEC2Client-html-runInstances-com-amazonaws-services-ec2-model-RunInstancesRequest-}[runInstances] method. The method returns a link:sdk-for-java/v1/reference/com/amazonaws/services/ec2/model/RunInstancesResult.html["RunInstancesResult", type="documentation"] object, as follows:
+
[source,java]
----
RunInstancesResult result = amazonEC2Client.runInstances(
                              runInstancesRequest);
----

After your instance is running, you can connect to it using your key pair. For more information, see  {url-ec2-user}AccessingInstances.html[Connect to Your Linux Instance]. in the {guide-ec2-user}.