//!!NODE_ROOT <section>
include::../../includes.txt[]

[."topic"]
[[sdk-metrics,sdk-metrics.title]]
= [[enabling-sdkmlong, Enabling SDK Metrics for Enterprise Support]]Enabling {AWS} SDK Metrics for Enterprise Support
:info_doctype: section
:info_title: Enabling {AWS} SDK Metrics for Enterprise Support

{AWS} SDK Metrics for Enterprise Support (SDK Metrics) enables Enterprise customers to collect metrics from {AWS} SDKs on their hosts and clients shared with {AWS} Enterprise Support. SDK Metrics provides information that helps speed up detection and diagnosis of issues occurring in connections to {AWS-services} for {AWS} Enterprise Support customers.

As telemetry is collected on each host, it is relayed via UDP to 127.0.0.1 (aka localhost), where the CloudWatch agent aggregates the data and sends it to the SDK Metrics service. Therefore, to receive metrics, the CloudWatch agent is required to be added to your instance.

The following steps to set up SDK Metrics pertain to an {EC2} instance running Amazon Linux for a client application that is using the {sdk-java}. SDK Metrics is also available for your production environments if you enable it while configuring the {sdk-java}.

To utilize SDK Metrics, run the latest version of the CloudWatch agent. Learn how to link:AmazonCloudWatch/latest/monitoring/Configure-CloudWatch-Agent-SDK-Metrics.html["Configure the CloudWatch Agent for SDK Metrics", type="documentation"] in the {guide-cw-user}.

To set up SDK Metrics with the {sdk-java}, follow these instructions:

. Create an application with an {sdk-java} client to use an {AWS-service}.
. Host your project on an {EC2} instance or in your local environment.
. Install and use the latest 1.x version of the {sdk-java}.
. Install and configure an CloudWatch agent on an EC2 instance or in your local environment.
. Authorize SDK Metrics to collect and send metrics.
. xref:csm-enable-agent[Enable SDK Metrics for the {sdk-java},linkend=csm-enable-agent].

For more information, see the following:



* xref:csm-update-agent[Update a CloudWatch Agent,linkend=csm-update-agent]
* xref:csm-disable-agent[Disable SDK Metrics,linkend=csm-disable-agent]


[[csm-enable-agent,csm-enable-agent.title]]
== Enable SDK Metrics for the SDK for Java

By default, SDK Metrics is turned off, and the port is set to 31000. The following are the default parameters.

[source,ini]
----
//default values
 [
     'enabled' => false,
     'port' => 31000,
 ]
----

Enabling SDK Metrics is independent of configuring your credentials to use an {AWS-service}.

You can enable SDK Metrics using one of 4 options.



* xref:csm-enable-agent-environ[Option 1: Set Environment Variables,linkend=csm-enable-agent-environ]
* xref:csm-enable-agent-code[Option 2: Set SDK Metrics in Code,linkend=csm-enable-agent-code]
* xref:csm-enable-agent-java-prop[Option 3: Set Java System Property,linkend=csm-enable-agent-java-prop]
* xref:csm-enable-agent-shared-config[Option 4: {AWS} Shared Config File,linkend=csm-enable-agent-shared-config]


[[csm-enable-agent-environ,csm-enable-agent-environ.title]]
=== Option 1: Set Environment Variables

If  `AWS_CSM_ENABLED` is not set, the SDK first checks the profile specified in the environment variable under `AWS_PROFILE` to determine if SDK Metrics is enabled. By default this is set to ``false``.

To turn on SDK Metrics, add the following to your environmental variables.

[source,ini]
----
export AWS_CSM_ENABLED=true
----

xref:csm-update-agent[Other configuration settings,linkend=csm-update-agent] are available.

Note: Enabling SDK Metrics does not configure your credentials to use an {AWS-service}.

[[csm-enable-agent-code,csm-enable-agent-code.title]]
=== Option 2: Set SDK Metrics in Code

The Java implementation allows you to set SDK Metrics configurations within code when building a service client. The values set in code override any configurations set in the other options described below.

[source,java]
----
CsmConfiguration csmConfig = new CsmConfiguration(true, MY_PORT, MY_CLIENT_ID);
AmazonDynamoDB dynamodb = AmazonDynamoDBClientBuilder.standard()
   .withClientSideMonitoringConfigurationProvider(new StaticCsmConfigurationProvider(csmConfig))
   .build();
----


[[csm-enable-agent-java-prop,csm-enable-agent-java-prop.title]]
=== Option 3: Set Java System Property

If no SDK Metrics configuration is found in the environment variables, the SDK looks at certain Java system properties.

To turn on SDK Metrics, pass the following system property flag when you execute your application.

[source,ini]
----
-Dcom.amazonaws.sdk.csm.enabled="true"
----

You can also set the value programmatically using the Properties object.

[source,java]
----
 Properties props = System.getProperties();
props.setProperty("com.amazonaws.sdk.csm.enabled", "true");
----

xref:csm-update-agent[Other configuration settings,linkend=csm-update-agent] are available.

Note: Enabling SDK Metrics does not configure your credentials to use an {AWS-service}.

[[csm-enable-agent-shared-config,csm-enable-agent-shared-config.title]]
=== Option 4: Shared Config File

If no SDK Metrics configuration is found in the environment variables or the Java system properties, the SDK looks for your default {AWS} profile field. If  `AWS_DEFAULT_PROFILE` is set to something other than default, update that profile. To enable SDK Metrics, add `csm_enabled` to the shared config file located at [path]``~/.aws/config``.

[source,ini]
----
[default]
csm_enabled = true

[profile aws_csm]
csm_enabled = true
----

xref:csm-update-agent[Other configuration settings,linkend=csm-update-agent] are available.

Note: Enabling SDK Metrics is independent from configuring your credentials to use an {AWS-service}. You can use a different profile to authenticate.

[[csm-update-agent,csm-update-agent.title]]
== Update a CloudWatch Agent

To make changes to the port, you need to set the values and then restart any {AWS} jobs that are currently active.

[[id1metrics,id1metrics.title]]
=== Option 1: Set Environment Variables

Most services use the default port. But if your service requires a unique port ID, add  __AWS_CSM_PORT=[port_number]__, to the host's environment variables.

[source,shell]
----
export AWS_CSM_ENABLED=true
export AWS_CSM_PORT=1234
----


[[option-2-set-java-system-property,option-2-set-java-system-property.title]]
=== Option 2: Set Java System Property

Most services use the default port. But if your service requires a unique port ID, specify the  _-Dcom.amazonaws.sdk.csm.port=[port_number]_ system properties flag when executing your application.

[source,ini]
----
com.amazonaws.sdk.csm.enabled=true
com.amazonaws.sdk.csm.port=1234
----


[[option-3-aws-shared-config-file,option-3-aws-shared-config-file.title]]
=== Option 3: Shared Config File

Most services use the default port. But if your service requires a unique port ID, add  _csm_port = [port_number]_ to __~/.aws/config__.

[source,ini]
----
[default]
csm_enabled = false
csm_port = 1234

[profile aws_csm]
csm_enabled = false
csm_port = 1234
----


[[restart-sdkm,restart-sdkm.title]]
=== Restart SDK Metrics

To restart a job, run the following commands.

[source,shell]
----
amazon-cloudwatch-agent-ctl -a stop;
amazon-cloudwatch-agent-ctl -a start;
----


[[csm-disable-agent,csm-disable-agent.title]]
== Disable SDK Metrics

To turn off SDK Metrics, set  _csm_enabled_ to _false_ in your environment variables, or in your {AWS} Shared config file located at [path]``~/.aws/config``. Then restart your CloudWatch agent so that the changes can take effect.

*Environment Variables*

[source,shell]
----
export AWS_CSM_ENABLED=false
----

*{AWS} Shared Config File*

Remove _csm_enabled_ from the profiles in your {AWS} Shared config file located at [path]``~/.aws/config``.

[NOTE]
====

Environment variables override the {AWS} Shared config file. If SDK Metrics is enabled in the environment variables, the SDK Metrics remain enabled.

====

[source,ini]
----
[default]
csm_enabled = false

[profile aws_csm]
csm_enabled = false
----

To disable SDK Metrics, use the following command to stop CloudWatch agent.

[source,shell]
----
sudo /opt/aws/amazon-cloudwatch-agent/bin/amazon-cloudwatch-agent-ctl -a stop &&
echo "Done"
----

If you are using other CloudWatch features, restart the CloudWatch agent with the following command.

[source,shell]
----
amazon-cloudwatch-agent-ctl -a start;
----


[[id2,id2.title]]
=== Restart SDK Metrics

To restart a SDK Metrics, run the following commands.

[source,shell]
----
amazon-cloudwatch-agent-ctl -a stop;
amazon-cloudwatch-agent-ctl -a start;
----


[[definitions-for-sdkm,definitions-for-sdkm.title]]
== Definitions for SDK Metrics

You can use the following descriptions of SDK Metrics to interpret your results. In general, these metrics are available for review with your Technical Account Manager during regular business reviews. {AWS} Support resources and your Technical Account Manager should have access to SDK Metrics data to help you resolve cases, but if you discover data that is confusing or unexpected, but doesn't seem to be negatively impacting your applications' performance, it is best to review that data during scheduled business reviews.

.{zwsp}
[cols="1,1", options="header"]
|===
| Metric:
| CallCount

|

Definition
|

Total number of successful or failed API calls from your code to {AWS-services}

|

How to use it
|

Use it as a baseline to correlate with other metrics like errors or throttling.
|===

.{zwsp}
[cols="1,1", options="header"]
|===
| Metric:
| ClientErrorCount

|

Definition
|

Number of API calls that fail with client errors (4xx HTTP response codes). _Examples: Throttling, Access denied, S3 bucket does not exist, and Invalid parameter value._

|

How to use it
|

Except in certain cases related to throttling (ex. when throttling occurs due to a limit that needs to be increased) this metric can indicate something in your application that needs to be fixed.
|===

.{zwsp}
[cols="1,1", options="header"]
|===
| Metric:
| ConnectionErrorCount

|

Definition
|

Number of API calls that fail because of errors connecting to the service. These can be caused by network issues between the customer application and {AWS-services} including load balancers, DNS failures, transit providers. In some cases, {AWS} issues may result in this error.

|

How to use it
|

Use this metric to determine whether issues are specific to your application or are caused by your infrastructure and/or network. High ConnectionErrorCount could also indicate short timeout values for API calls.
|===

.{zwsp}
[cols="1,1", options="header"]
|===
| Metric:
| ThrottleCount

|

Definition
|

Number of API calls that fail due to throttling by {AWS-services}.

|

How to use it
|

Use this metric to assess if your application has reached throttle limits, as well as to determine the cause of retries and application latency. Consider distributing calls over a window instead of batching your calls.
|===

.{zwsp}
[cols="1,1", options="header"]
|===
| Metric:
| ServerErrorCount

|

Definition
|

Number of API calls that fail due to server errors (5xx HTTP response codes) from {AWS-services}. These are typically caused by {AWS-services}.

|

How to use it
|

Determine cause of SDK retries or latency. This metric will not always indicate that {AWS-services} are at fault, as some {AWS} teams classify latency as an HTTP 503 response.
|===

.{zwsp}
[cols="1,1", options="header"]
|===
| Metric:
| EndToEndLatency

|

Definition
|

Total time for your application to make a call using the {AWS} SDK, inclusive of retries. In other words, regardless of whether it is successful after several attempts, or as soon as a call fails due to an unretriable error.

|

How to use it
|

Determine how {AWS} API calls contribute to your application's overall latency. Higher than expected latency may be caused by issues with network, firewall, or other configuration settings, or by latency that occurs as a result of SDK retries.
|===