//!!NODE_ROOT <section>
include::../../includes.txt[]
:https---docs-aws-amazon-com-AWSJavaSDK-latest-javadoc-com-amazonaws-ClientConfiguration-html-setLocalAddress-java-net-InetAddress-: {v1javadocs}com/amazonaws/ClientConfiguration.html#setLocalAddress-java.net.InetAddress-
:https---docs-aws-amazon-com-AWSJavaSDK-latest-javadoc-com-amazonaws-ClientConfiguration-html-setMaxErrorRetry-int-: {v1javadocs}com/amazonaws/ClientConfiguration.html#setMaxErrorRetry-int-
:https---docs-aws-amazon-com-AWSJavaSDK-latest-javadoc-com-amazonaws-ClientConfiguration-html-setConnectionTTL-long-: {v1javadocs}com/amazonaws/ClientConfiguration.html#setConnectionTTL-long-
:https---docs-aws-amazon-com-AWSJavaSDK-latest-javadoc-com-amazonaws-ClientConfiguration-html-setConnectionTimeout-int-: {v1javadocs}com/amazonaws/ClientConfiguration.html#setConnectionTimeout-int-
:https---docs-aws-amazon-com-AWSJavaSDK-latest-javadoc-com-amazonaws-ClientConfiguration-html-setMaxConnections-int-: {v1javadocs}com/amazonaws/ClientConfiguration.html#setMaxConnections-int-

[."topic"]
[[section-client-configuration,section-client-configuration.title]]
= [[client-configuration, Client Configuration]]Client Configuration
:info_doctype: section
:info_title: Client Configuration
:info_abstract: How to change proxy configuration, HTTP transport configuration, and TCP socket buffer size hints by using the {sdk-java}.

[abstract]
--
How to change proxy configuration, HTTP transport configuration, and TCP socket buffer size hints by using the {sdk-java}.
--

The {sdk-java} enables you to change the default client configuration, which is helpful when you want to:



* Connect to the Internet through proxy
* Change HTTP transport settings, such as connection timeout and request retries
* Specify TCP socket buffer size hints


[[proxy-configuration,proxy-configuration.title]]
== Proxy Configuration

When constructing a client object, you can pass in an optional  link:sdk-for-java/v1/reference/com/amazonaws/ClientConfiguration.html["ClientConfiguration", type="documentation"] object to customize the client's configuration.

If you connect to the Internet through a proxy server, you'll need to configure your proxy server settings (proxy host, port, and username/password) through the `ClientConfiguration` object.

[[http-transport-configuration,http-transport-configuration.title]]
== HTTP Transport Configuration

You can configure several HTTP transport options by using the  link:sdk-for-java/v1/reference/com/amazonaws/ClientConfiguration.html["ClientConfiguration", type="documentation"] object. New options are occasionally added; to see the full list of options you can retrieve or set, see the {sdk-java} API Reference.

[NOTE]
====

Each of the configurable values has a default value defined by a constant. For a list of the constant values for ``ClientConfiguration``, see link:constant-values.html["Constant Field Values", type="documentation"] in the {sdk-java} API Reference.

====

[[maximum-connections,maximum-connections.title]]
=== Maximum Connections

You can set the maximum allowed number of open HTTP connections by using the  {https---docs-aws-amazon-com-AWSJavaSDK-latest-javadoc-com-amazonaws-ClientConfiguration-html-setMaxConnections-int-}[ClientConfiguration.setMaxConnections] method.

[IMPORTANT]
====

Set the maximum connections to the number of concurrent transactions to avoid connection contentions and poor performance. For the default maximum connections value, see link:constant-values.html["Constant Field Values", type="documentation"] in the {sdk-java} API Reference.

====

[[timeouts-and-error-handling,timeouts-and-error-handling.title]]
=== Timeouts and Error Handling

You can set options related to timeouts and handling errors with HTTP connections.



* *Connection Timeout*
+

The connection timeout is the amount of time (in milliseconds) that the HTTP connection will wait to establish a connection before giving up. The default is 10,000 ms.
+

To set this value yourself, use the {https---docs-aws-amazon-com-AWSJavaSDK-latest-javadoc-com-amazonaws-ClientConfiguration-html-setConnectionTimeout-int-}[ClientConfiguration.setConnectionTimeout] method.
* *Connection Time to Live (TTL)*
+

By default, the SDK will attempt to reuse HTTP connections as long as possible. In failure situations where a connection is established to a server that has been brought out of service, having a finite TTL can help with application recovery. For example, setting a 15 minute TTL will ensure that even if you have a connection established to a server that is experiencing issues, you'll reestablish a connection to a new server within 15 minutes.
+

To set the HTTP connection TTL, use the {https---docs-aws-amazon-com-AWSJavaSDK-latest-javadoc-com-amazonaws-ClientConfiguration-html-setConnectionTTL-long-}[ClientConfiguration.setConnectionTTL] method.
* *Maximum Error Retries*
+

The default maximum retry count for retriable errors is 3. You can set a different value by using the {https---docs-aws-amazon-com-AWSJavaSDK-latest-javadoc-com-amazonaws-ClientConfiguration-html-setMaxErrorRetry-int-}[ClientConfiguration.setMaxErrorRetry] method.


[[local-address,local-address.title]]
=== Local Address

To set the local address that the HTTP client will bind to, use  {https---docs-aws-amazon-com-AWSJavaSDK-latest-javadoc-com-amazonaws-ClientConfiguration-html-setLocalAddress-java-net-InetAddress-}[ClientConfiguration.setLocalAddress].

[[tcp-socket-buffer-size-hints,tcp-socket-buffer-size-hints.title]]
== TCP Socket Buffer Size Hints

Advanced users who want to tune low-level TCP parameters can additionally set TCP buffer size hints through the  link:sdk-for-java/v1/reference/com/amazonaws/ClientConfiguration.html["ClientConfiguration", type="documentation"] object. The majority of users will never need to tweak these values, but they are provided for advanced users.

Optimal TCP buffer sizes for an application are highly dependent on network and operating system configuration and capabilities. For example, most modern operating systems provide auto-tuning logic for TCP buffer sizes.This can have a big impact on performance for TCP connections that are held open long enough for the auto-tuning to optimize buffer sizes.

Large buffer sizes (e.g., 2 MB) allow the operating system to buffer more data in memory without requiring the remote server to acknowledge receipt of that information, and so can be particularly useful when the network has high latency.

This is only a __hint__, and the operating system might not honor it. When using this option, users should always check the operating system's configured limits and defaults. Most operating systems have a maximum TCP buffer size limit configured, and won't let you go beyond that limit unless you explicitly raise the maximum TCP buffer size limit.

Many resources are available to help with configuring TCP buffer sizes and operating system-specific TCP settings, including the following:



* http://fasterdata.es.net/host-tuning/[Host Tuning]
