//!!NODE_ROOT <section>
include::../../includes.txt[]
:java-aws-securitydocs: {url-doc-domain}security/?id=docs_gateway#aws-security
[."topic"]
[[security-iam,security-iam.title]]
= [[identity-and-access-management-for-this-aws-product-or-service, Identity and Access Management for this Product or Service]]Identity and Access Management for this {AWS} Product or Service
:info_doctype: section
:info_title: Identity and Access Management for this {AWS} Product or Service
:info_titleabbrev: Identity and Access Management

{IAMlong} ({IAM}) is an {AWSlong} ({AWS}) service that helps
an administrator securely control access to {AWS} resources. {IAM} administrators control who can
be _authenticated_ (signed in) and _authorized_ (have permissions) to use resources in {AWS}
services. {IAM} is an {AWS-service} that you can use with no additional charge.

To use this {AWS} product or service to access {AWS}, you need an {AWS-account} and {AWS}
credentials. To increase the security of your {AWS-account}, we recommend that you use an _{IAM} user_
to provide access credentials instead of using your {AWS-account} credentials.

For details about working with {IAM}, see link:iam/["pass:q[[.shared\]`IAMlong`]", type="marketing"].

For an overview of {IAM} users and why they are important for the security of your account, see
link:general/latest/gr/aws-security-credentials.html["pass:q[[.shared\]`AWS`] Security Credentials", type="documentation"]
in the {link-aws-gen}.

This {AWS} product or service follows the
link:compliance/shared-responsibility-model/["shared responsibility model", type="marketing"] through the
specific {AWSlong} ({AWS}) services it supports. For {AWS-service} security
information, see the {java-aws-securitydocs}[{AWS-service} security documentation page]
and link:compliance/services-in-scope/["pass:q[[.shared\]`AWS`] services that are in scope of
pass:q[[.shared\]`AWS`] compliance efforts by compliance program", type="marketing"].
