//!!NODE_ROOT <section>
include::../../includes.txt[]

[."topic"]
[[security-java-tls,security-java-tls.title]]
= [[aws-sdk-for-java-support-for-tls, SDK for Java support for TLS]]{sdk-java} support for TLS
:info_doctype: section
:info_title: {sdk-java} support for TLS
:info_titleabbrev: Enforcing a minimum TLS Version
:info_abstract: Applies to Java SSL implementation (default SSL implementation in the SDK). Learn how the {AWS} shared responsibility model applies to data protection in this {AWS} product or service.

[abstract]
--
Applies to Java SSL implementation (default SSL implementation in the SDK). Learn how the {AWS} shared responsibility model applies to data protection in this {AWS} product or service.
--

The following information applies only to Java SSL implementation (the default SSL implementation in the {sdk-java}). If you're using a different SSL implementation, see your specific SSL implementation to learn how to enforce TLS versions.

[[how-to-check-the-tls-version,how-to-check-the-tls-version.title]]
== How to check the TLS version

Consult your Java virtual machine (JVM) provider's documentation to determine which TLS versions are supported on your platform. For some JVMs, the following code will print which SSL versions are supported.

[source,java]
----
System.out.println(Arrays.toString(SSLContext.getDefault().getSupportedSSLParameters().getProtocols()));
----

To see the SSL handshake in action and what version of TLS is used, you can use the system property **javax.net.debug**.

[source,java]
----
java app.jar -Djavax.net.debug=ssl
----


[[how-to-set-the-tls-version,how-to-set-the-tls-version.title]]
== Enforcing a minimum TLS Version

The SDK always prefers the latest TLS version supported by the platform and service. If you wish to enforce a specific minimum TLS version, consult your JVM's documentation.

For OpenJDK-based JVMs, you can use the system property **jdk.tls.client.protocols**.

[source,java]
----
java app.jar -Djdk.tls.client.protocols=PROTOCOLS
----

Consolt your JVM's documentation for the supported values of **PROTOCOLS**.