//!!NODE_ROOT <section>
include::../../includes.txt[]
:java-gradle46-link: https://docs.gradle.org/4.6/release-notes.html#bom-import
[."topic"]
[[setup-project-gradle,setup-project-gradle.title]]
= [[using-the-sdk-with-gradle, Using the SDK with Gradle]]Using the SDK with Gradle
:info_doctype: section
:info_title: Using the SDK with Gradle
:info_abstract: How to use Gradle to set up your {sdk-java} project
:info_keywordset: sdk-javaGradle BOM install download setup

[abstract]
--
How to use Gradle to set up your {sdk-java} project
--

To manage SDK dependencies for your https://gradle.com/[Gradle] project, import the Maven BOM for
the {sdk-java} into the [path]``build.gradle`` file.

[NOTE]
====

In the following examples, replace _{v1build}_ in the build file with a valid version of the
{sdk-java}. Find the latest version in the link:AWSJavaSDK/latest/javadoc/["pass:q[[.shared\]`Javalong`] 1.x Reference", type="documentation"].

====

[[project-setup-for-gradle-4-6-or-higher,project-setup-for-gradle-4-6-or-higher.title]]
== Project setup for Gradle 4.6 or higher

{java-gradle46-link}[Since Gradle 4.6], you can use Gradle's improved POM support feature for
importing bill of materials (BOM) files by declaring a dependency on a BOM.

. If you're using Gradle 5.0 or later, skip to step 2. Otherwise, enable the
_IMPROVED_POM_SUPPORT_ feature in the [path]``settings.gradle`` file.
+
[source,groovy]
----
enableFeaturePreview('IMPROVED_POM_SUPPORT')
----
. Add the BOM to the _dependencies_ section of the [path]``build.gradle`` file.
+
[source,groovy]
----
...
dependencies {
    implementation platform('com.amazonaws:aws-java-sdk-bom:1.11.1000')

    // Declare individual SDK dependencies without version
    ...
}
----
. Specify the SDK modules to use in the _dependencies_ section. For example, the following includes a dependency for {S3long} ({S3}).
+
[source,groovy]
----
...
dependencies {
    implementation 'com.amazonaws:aws-java-sdk-s3'
    ...
}
----

Gradle automatically resolves the correct version of your SDK dependencies by using the
information from the BOM.

The following is an example of a complete [path]``build.gradle`` file that includes a dependency
for {S3}.

[source,groovy]
----
group 'aws.test'
version '1.0-SNAPSHOT'

apply plugin: 'java'

sourceCompatibility = 1.8

repositories {
  mavenCentral()
}

dependencies {
  implementation platform('com.amazonaws:aws-java-sdk-bom:1.11.1000')
  implementation 'com.amazonaws:aws-java-sdk-s3'
  testCompile group: 'junit', name: 'junit', version: '4.11'
}
----

[NOTE]
====

In the previous example, replace the dependency for {S3} with the dependencies of the {AWS}
services you will use in your project. The modules (dependencies) that are managed by the
{sdk-java} BOM are listed on Maven central repository
(https://mvnrepository.com/artifact/com.amazonaws/aws-java-sdk-bom/latest[]).

====

[[project-setup-for-gradle-versions-earlier-than-4-6,project-setup-for-gradle-versions-earlier-than-4-6.title]]
== Project setup for Gradle versions earlier than 4.6

Gradle versions earlier than 4.6 lack native BOM support. To manage {sdk-java} dependencies for
your project, use Spring's
https://github.com/spring-gradle-plugins/dependency-management-plugin[dependency management plugin]
for Gradle to import the Maven BOM for the SDK.

. Add the dependency management plugin to your [path]``build.gradle`` file.
+
[source,groovy]
----
buildscript {
    repositories {
        mavenCentral()
    }
    dependencies {
        classpath "io.spring.gradle:dependency-management-plugin:1.0.9.RELEASE"
    }
}

apply plugin: "io.spring.dependency-management"
----
. Add the BOM to the _dependencyManagement_ section of the file.
+
[source,groovy]
----
dependencyManagement {
    imports {
        mavenBom 'com.amazonaws:aws-java-sdk-bom:1.11.1000'
    }
}
----
. Specify the SDK modules that you'll use in the _dependencies_ section. For example, the following includes a dependency for {S3}.
+
[source,groovy]
----
dependencies {
    compile 'com.amazonaws:aws-java-sdk-s3'
}
----

Gradle automatically resolves the correct version of your SDK dependencies by using the
information from the BOM.

The following is an example of a complete [path]``build.gradle`` file that includes a dependency
for {S3}.

[source,groovy]
----
group 'aws.test'
version '1.0'

apply plugin: 'java'

sourceCompatibility = 1.8

repositories {
  mavenCentral()
}

buildscript {
  repositories {
    mavenCentral()
  }
  dependencies {
    classpath "io.spring.gradle:dependency-management-plugin:1.0.9.RELEASE"
  }
}

apply plugin: "io.spring.dependency-management"

dependencyManagement {
  imports {
    mavenBom 'com.amazonaws:aws-java-sdk-bom:1.11.1000'
  }
}

dependencies {
  compile 'com.amazonaws:aws-java-sdk-s3'
  testCompile group: 'junit', name: 'junit', version: '4.11'
}
----

[NOTE]
====

In the previous example, replace the dependency for {S3} with the dependencies of the {AWS}
service you will use in your project. The modules (dependencies) that are managed by the
{sdk-java} BOM are listed on Maven central repository
(https://mvnrepository.com/artifact/com.amazonaws/aws-java-sdk-bom/latest).

====

For more information about specifying SDK dependencies by using the BOM, see
xref:setup-project-maven[Using the SDK with Apache Maven,linkend=setup-project-maven].
