//!!NODE_ROOT <section>
include::../../includes.txt[]

[."topic"]
[[setup-credentials,setup-credentials.title]]
= [[set-up-aws-credentials-and-region-for-development, Set up Credentials and Region for Development]]Set up {AWS} Credentials and Region for Development
:info_doctype: section
:info_title: Set up {AWS} Credentials and Region for Development
:info_abstract: Set up default {AWS} credentials and region for development with the {sdk-java}.
:info_keywordset: AWSregionAWS credentialssetupshared credentials fileshared config fileenvironment variable

[abstract]
--
Set up default {AWS} credentials and region for development with the {sdk-java}.
--

To connect to any of the supported services with the {sdk-java}, you must provide {AWS} credentials. The {AWS} SDKs and CLIs use  _provider chains_ to look for {AWS} credentials in a number of different places, including system/user environment variables and local {AWS} configuration files.

This topic provides basic information about setting up your {AWS} credentials for local application development using the {sdk-java}. If you need to set up credentials for use within an EC2 instance or if you're using the Eclipse IDE for development, refer to the following topics instead:



* When using an EC2 instance, create an IAM role and then give your EC2 instance access to that role as shown in xref:java-dg-roles[Using IAM Roles to Grant Access to {AWS} Resources on {EC2},linkend=java-dg-roles].
* Set up {AWS} credentials within Eclipse using the link:eclipse/["pass:q[[.shared\]`TElong`]", type="marketing"]. See link:toolkit-for-eclipse/v1/user-guide/setup-credentials.html["Set up pass:q[[.shared\]`AWS`] Credentials", type="documentation"] in the link:toolkit-for-eclipse/v1/user-guide/["pass:q[[.shared\]`TElong`] User Guide", type="documentation"] for more information.


[[setup-credentials-setting,setup-credentials-setting.title]]
== Setting Credentials

Setting your credentials for use by the {sdk-java} can be done in a number of ways, but here are the recommended approaches:



* Set credentials in the {AWS} credentials profile file on your local system, located at:
+
** [path]``~/.aws/credentials`` on Linux, macOS, or Unix
** [path]``C:\Users\USERNAME\.aws\credentials`` on Windows

+

This file should contain lines in the following format:
+
[source,cfg]
----
[default]
aws_access_key_id = your_access_key_id
aws_secret_access_key = your_secret_access_key
----
+

Substitute your own {AWS} credentials values for the values  _your_access_key_id_ and __your_secret_access_key__.
* Set the `AWS_ACCESS_KEY_ID` and `AWS_SECRET_ACCESS_KEY` environment variables.
+

To set these variables on Linux, macOS, or Unix, use **``**export**``**:
+
[source,sh]
----
export AWS_ACCESS_KEY_ID=your_access_key_id
export AWS_SECRET_ACCESS_KEY=your_secret_access_key
----
+

To set these variables on Windows, use  **``**set**``**:
+
[source,bat]
----
set AWS_ACCESS_KEY_ID=your_access_key_id
set AWS_SECRET_ACCESS_KEY=your_secret_access_key
----
* For an EC2 instance, specify an IAM role and then give your EC2 instance access to that role. See {url-ec2-user}iam-roles-for-amazon-ec2.html[IAM Roles for {EC2}] in the {guide-ec2-user} for a detailed discussion about how this works.

Once you have set your {AWS} credentials using one of these methods, they will be loaded automatically by the {sdk-java} by using the default credential provider chain. For further information about working with {AWS} credentials in your Java applications, see  xref:credentials[Working with {AWS} Credentials,linkend=credentials].

[[refresh-credentials,refresh-credentials.title]]
== Refreshing IMDS credentials

The {sdk-java} supports opt-in refreshing IMDS credentials in the background every 1 minute, regardless of the credential expiration time. This allows you to refresh credentials more frequently and reduces the chance that not reaching IMDS impacts the perceived {AWS} availability.

[source,java,linenums]
----
 1. // Refresh credentials using a background thread, automatically every minute. This will log an error if IMDS is down during
 2. // a refresh, but your service calls will continue using the cached credentials until the credentials are refreshed
 3. // again one minute later.
 4.
 5. InstanceProfileCredentialsProvider credentials =
 6.     InstanceProfileCredentialsProvider.createAsyncRefreshingProvider(true);
 7.
 8. AmazonS3Client.builder()
 9.              .withCredentials(credentials)
 10.              .build();
 11.
 12. // This is new: When you are done with the credentials provider, you must close it to release the background thread.
 13. credentials.close();
----


[[setup-credentials-setting-region,setup-credentials-setting-region.title]]
== Setting the Region

You should set a default {AWS-Region} that will be used for accessing {AWS-services} with the {sdk-java}. For the best network performance, choose a region that's geographically close to you (or to your customers). For a list of regions for each service, see  link:general/latest/gr/rande.html["Regions and Endpoints", type="documentation"] in the {AWS-GEN-REF-long}.

[NOTE]
====

If you _don't_ select a region, then us-east-1 will be used by default.

====

You can use similar techniques to setting credentials to set your default {AWS} region:



* Set the {AWS-Region} in the {AWS} config file on your local system, located at:
+
** ~/.aws/config on Linux, macOS, or Unix
** C:\Users\USERNAME\.aws\config on Windows

+

This file should contain lines in the following format:
+
[source,cfg]
----
[default]
region = your_aws_region
----
+

Substitute your desired {AWS-Region} (for example, "`{region_api_default}`") for  __your_aws_region__.
* Set the `AWS_REGION` environment variable.
+

On Linux, macOS, or Unix, use **``**export**``**:
+
[source,sh]
----
export AWS_REGION=your_aws_region
----
+

On Windows, use  **``**set**``**:
+
[source,bat]
----
set AWS_REGION=your_aws_region
----
+

Where  _your_aws_region_ is the desired {AWS-Region} name.


[.topiclist-abbrev]
[[Topic List]]

include::prog-services-sts.adoc[leveloffset=+1]
