//!!NODE_ROOT <section>
include::../../includes.txt[]

[."topic"]
[[setup-install,setup-install.title]]
= [[set-up-the-sdk-java, Set up the SDK for Java]]Set up the {sdk-java}
:info_doctype: section
:info_title: Set up the {sdk-java}

Describes how to use the {sdk-java} in your project.

[[prerequisitesinstall,prerequisitesinstall.title]]
== Prerequisites

To use the {sdk-java}, you must have:



* a suitable xref:java-dg-java-env[Java Development Environment,linkend=java-dg-java-env].
* An {AWS-account} and access keys. For instructions, see xref:signup-create-iam-user[Sign Up for {AWS} and Create an IAM User,linkend=signup-create-iam-user].
* {AWS} credentials (access keys) set in your environment or using the shared (by the {CLI} and other SDKs) credentials file. For more information, see xref:setup-credentials[Set up {AWS} Credentials and Region for Development,linkend=setup-credentials].


[[include-sdk,include-sdk.title]]
== Including the SDK in your project

To include the SDK your project, use one of the following methods depending on your build system or IDE:



* **Apache Maven**- If you use https://maven.apache.org/[Apache Maven], you can specify the entire SDK (or specific SDK components) as dependencies in your project. See xref:setup-project-maven[Using the SDK with Apache Maven,linkend=setup-project-maven] for details about how to set up the SDK when using Maven.
* **Gradle**- If you use https://gradle.com/[Gradle], you can import the Maven Bill of Materials (BOM) in your Gradle project to automatically manage SDK dependencies. See xref:setup-project-gradle[Using the SDK with Gradle,linkend=setup-project-gradle] for more infomation.
* **Eclipse IDE**- If you use the Eclipse IDE, you may want to install and use the link:eclipse/["pass:q[[.shared\]`TElong`]", type="marketing"], which will automatically download, install and update the Java SDK for you. For more information and setup instructions, see the link:toolkit-for-eclipse/v1/user-guide/["pass:q[[.shared\]`TElong`] User Guide", type="documentation"].

If you are using one the above methods (for example, you are using Maven), then you do not need to download and install the {AWS} JAR files (you can skip the following section). If you intend to build your projects using a different IDE, with Apache Ant or by any other means, then download and extract the SDK as shown in the next section.

[[download-and-extract-sdk,download-and-extract-sdk.title]]
== Downloading and extracting the SDK

We recommend that you use the most recent pre-built version of the SDK for new projects, which provides you with the latest support for all {AWS-services}.

[NOTE]
====

For information about how to download and build previous versions of the SDK, see xref:install-prev-sdk[Installing previous versions of the SDK,linkend=install-prev-sdk].

====
. Download the SDK from https://sdk-for-java.amazonwebservices.com/latest/aws-java-sdk.zip.
. After downloading the SDK, extract the contents into a local directory.

The SDK contains the following directories:



* [path]``documentation``- contains the API documentation (also available on the web:  link:AWSJavaSDK/latest/javadoc/["pass:q[[.shared\]`Javalong`] API Reference", type="documentation"]).
* [path]``lib``- contains the SDK  [path]``.jar`` files.
* [path]``samples``- contains working sample code that demonstrates how to use the SDK.
* [path]``third-party/lib``- contains third-party libraries that are used by the SDK, such as Apache commons logging, AspectJ and the Spring framework.

To use the SDK, add the full path to the  `lib` and `third-party` directories to the dependencies in your build file, and add them to your java `CLASSPATH` to run your code.

[[install-prev-sdk,install-prev-sdk.title]]
== Installing previous versions of the SDK

Only the latest version of the SDK is provided in pre-built form. However, you can build a previous version of the SDK using Apache Maven (open source). Maven will download all necessary dependencies, build and install the SDK in one step. Visit  http://maven.apache.org/ for installation instructions and more information.

. Go to the SDK's GitHub page at: {url-aws-github}aws-sdk-java[{sdk-java} (GitHub)].
. Choose the tag corresponding to the version number of the SDK that you want. For example, ``1.6.10``.
. Click the *Download ZIP* button to download the version of the SDK you selected.
. Unzip the file to a directory on your development system. On many systems, you can use your graphical file manager to do this, or use the `unzip` utility in a terminal window.
. In a terminal window, navigate to the directory where you unzipped the SDK source.
. Build and install the SDK with the following command (https://maven.apache.org/[Maven] required):
+
[source,java]
----
mvn clean install
----
+

The resulting  [path]``.jar`` file is built into the  [path]``target`` directory.
. (Optional) Build the API Reference documentation using the following command:
+
[source,java]
----
mvn javadoc:javadoc
----
+

The documentation is built into the  [path]``target/site/apidocs/`` directory.


[[java-dg-java-env,java-dg-java-env.title]]
== Installing a Java Development Environment

The {sdk-java} requires J2SE Development Kit  __6.0 or later__. You can download the latest Java software from http://www.oracle.com/technetwork/java/javase/downloads/.

[IMPORTANT]
====

Java version 1.6 (JS2E 6.0) did not have built-in support for SHA256-signed SSL certificates, which are required for all HTTPS connections with {AWS} after September 30, 2015.

Java versions 1.7 or newer are packaged with updated certificates and are unaffected by this issue.

====

[[choosing-a-jvm,choosing-a-jvm.title]]
=== Choosing a JVM

For the best performance of your server-based applications with the {sdk-java}, we recommend that you use the  _64-bit version_ of the Java Virtual Machine (JVM). This JVM runs only in server mode, even if you specify the `-Client` option at run time.

Using the 32-bit version of the JVM with the `-Server` option at run time should provide comparable performance to the 64-bit JVM.