//!!NODE_ROOT <section>
include::../../includes.txt[]
:https---docs-aws-amazon-com-IAM-latest-UserGuide-introduction-identity-management-html: {url-doc-domain}IAM/latest/UserGuide/introduction_identity-management.html

[."topic"]
[[signup-create-iam-user,signup-create-iam-user.title]]
= [[sign-up-for-aws-and-create-an-iam-user, Sign Up and Create an IAM User]]Sign Up for {AWS} and Create an IAM User
:info_doctype: section
:info_title: Sign Up for {AWS} and Create an IAM User

To use the {sdk-java} to access {AWSlong} ({AWS}), you will need an {AWS-account} and {AWS} credentials. To increase the security of your {AWS-account}, we recommend that you use an  _IAM user_ to provide access credentials instead of using your root account credentials.

[NOTE]
====

For an overview of IAM users and why they are important for the security of your account, see {https---docs-aws-amazon-com-IAM-latest-UserGuide-introduction-identity-management-html}[Overview of Identity Management: Users] in the {guide-iam-user}.

====
. Open link:["the pass:q[[.shared\]`AWS`] website", type="marketing"] and click **Sign Up**.
. Follow the on-screen instructions. Part of the sign-up procedure involves receiving a phone call and entering a PIN using your phone keypad.

Next, create an IAM user and download (or copy) its secret access key.

. Go to the link:iam/home["IAM console", type="console"] (you may need to sign in to {AWS} first).
. Click *Users* in the sidebar to view your IAM users.
. If you don't have any IAM users set up, click *Create New Users* to create one.
. Select the IAM user in the list that you'll use to access {AWS}.
. Open the *Security Credentials* tab, and click  **Create Access Key**.
+
NOTE: You can have a maximum of two active access keys for any given IAM user. If your IAM user has two access keys already, then you'll need to delete one of them before creating a new key.
. On the resulting dialog box, click the *Download Credentials* button to download the credential file to your computer, or click  *Show User Security Credentials* to view the IAM user's access key ID and secret access key (which you can copy and paste).
+
IMPORTANT: There is no way to obtain the secret access key once you close the dialog box. You can, however, delete its associated access key ID and create a new one.

Next, you should  xref:setup-credentials[set your credentials,linkend=setup-credentials] in the {AWS} shared credentials file or in the environment.

[NOTE]
====

If you use the Eclipse IDE, you should consider installing the link:eclipse/["pass:q[[.shared\]`TElong`]", type="marketing"] and providing your credentials as described in link:toolkit-for-eclipse/v1/user-guide/setup-credentials.html["Set up pass:q[[.shared\]`AWS`] Credentials", type="documentation"] in the {TElong} User Guide.

====
