//!!NODE_ROOT <section>
include::../../includes.txt[]
:https---github-com-awsdocs-aws-doc-sdk-examples-tree-master-java-example-code-swf: {url-awsdocs-github}aws-doc-sdk-examples/tree/master/java/example_code/swf
[."topic"]
[[swf-hello,swf-hello.title]]
= [[building-a-simple-swf-application, Building a Simple SWF Application]]Building a Simple {SWF} Application
:info_doctype: section
:info_title: Building a Simple {SWF} Application

This topic will introduce you to programming  link:swf/["pass:q[[.shared\]`SWF`]", type="marketing"] applications with the {sdk-java}, while presenting a few important concepts along the way.

[[about-the-example,about-the-example.title]]
== About the example

The example project will create a workflow with a single activity that accepts workflow data passed through the {AWS} cloud (In the tradition of HelloWorld, it'll be the name of someone to greet) and then prints a greeting in response.

While this seems very simple on the surface, {SWF} applications consist of a number of parts working together:



* A **domain**, used as a logical container for your workflow execution data.
* One or more *workflows* which represent code components that define logical order of execution of your workflow's activities and child workflows.
* A **workflow worker**, also known as a __decider__, that polls for decision tasks and schedules activities or child workflows in response.
* One or more **activities**, each of which represents a unit of work in the workflow.
* An *activity worker* that polls for activity tasks and runs activity methods in response.
* One or more **task lists**, which are queues maintained by {SWF} used to issue requests to the workflow and activity workers. Tasks on a task list meant for workflow workers are called __decision tasks__. Those meant for activity workers are called __activity tasks__.
* A *workflow starter* that begins your workflow execution.

Behind the scenes, {SWF} orchestrates the operation of these components, coordinating their flow from the {AWS} cloud, passing data between them, handling timeouts and heartbeat notifications, and logging workflow execution history.

[[prerequisitesswf,prerequisitesswf.title]]
== Prerequisites

[[development-environment,development-environment.title]]
=== Development environment

The development environment used in this tutorial consists of:



* The link:sdk-for-java/["pass:q[[.shared\]`Javalong`]", type="marketing"].
* http://maven.apache.org/[Apache Maven] (3.3.1).
* JDK 1.7 or later. This tutorial was developed and tested using JDK 1.8.0.
* A good Java text editor (your choice).


[NOTE]
====

If you use a different build system than Maven, you can still create a project using the appropriate steps for your environment and use the the concepts provided here to follow along. More information about configuring and using the {sdk-java} with various build systems is provided in  xref:getting-started[Getting Started,linkend=getting-started].

Likewise, but with more effort, the steps shown here can be implemented using any of the {AWS} SDKs with support for {SWF}.

====

All of the necessary external dependencies are included with the {sdk-java}, so there's nothing additional to download.

[[aws-access,aws-access.title]]
=== Access

To access {AWSlong} ({AWS}), you must have an active {AWS-account}. For information about signing up for {AWS} and creating an IAM user (recommended over using root account credentials), see  xref:signup-create-iam-user[Sign Up for {AWS} and Create an IAM User,linkend=signup-create-iam-user].

This tutorial uses the terminal (command-line) to run the example code, and expects that you have your {AWS} credentials and configuration accessible to the SDK. The easiest way to do this is to use the environment variables `AWS_ACCESS_KEY_ID` and ``AWS_SECRET_ACCESS_KEY``. You should also set the `AWS_REGION` to the region you want to use.

For example, on Linux, macOS, or Unix, set the variables this way:

[source,sh]
----
export AWS_ACCESS_KEY_ID=your_access_key_id
export AWS_SECRET_ACCESS_KEY=your_secret_access_key
export AWS_REGION=us-east-1
----

To set these variables on Windows, use these commands:

[source,bat]
----
set AWS_ACCESS_KEY_ID=your_access_key_id
set AWS_SECRET_ACCESS_KEY=your_secret_access_key
set AWS_REGION=us-east-1
----

[IMPORTANT]
====

Substitute your own access key, secret access key and region information for the example values shown here.

For more information about configuring your credentials for the SDK, see xref:setup-credentials[Set up {AWS} Credentials and Region for Development,linkend=setup-credentials].

====

[[create-a-swf-project,create-a-swf-project.title]]
== Create a SWF project
. Start a new project with Maven:
+
[source,sh]
----
mvn archetype:generate -DartifactId=helloswf \
-DgroupId=aws.example.helloswf -DinteractiveMode=false
----
+

This will create a new project with a standard maven project structure:
+
[source,none]
----
helloswf
├── pom.xml
└── src
    ├── main
    │   └── java
    │       └── aws
    │           └── example
    │               └── helloswf
    │                   └── App.java
    └── test
        └── ...
----
+

You can ignore or delete the  [path]``test`` directory and all it contains, we won't be using it for this tutorial. You can also delete  [path]``App.java``, since we'll be replacing it with new classes.
. Edit the project's [path]``pom.xml`` file and add the  *aws-java-sdk-simpleworkflow* module by adding a dependency for it within the `<dependencies>` block.
+
[source,xml]
----
<dependencies>
  <dependency>
    <groupId>com.amazonaws</groupId>
    <artifactId>aws-java-sdk-simpleworkflow</artifactId>
    <version>1.11.1000</version>
  </dependency>
</dependencies>
----
. __Make sure that Maven builds your project with JDK 1.7+ support__. Add the following to your project (either before or after the `<dependencies>` block) in [path]``pom.xml``:
+
[source,xml]
----
<build>
  <plugins>
    <plugin>
      <artifactId>maven-compiler-plugin</artifactId>
      <version>3.6.1</version>
      <configuration>
          <source>1.8</source>
          <target>1.8</target>
      </configuration>
    </plugin>
  </plugins>
</build>
----


[[code-the-project,code-the-project.title]]
== Code the project

The example project will consist of four separate applications, which we'll visit one by one:



* **HelloTypes.java**--contains the project's domain, activity and workflow type data, shared with the other components. It also handles registering these types with SWF.
* **ActivityWorker.java**--contains the activity worker, which polls for activity tasks and runs activities in response.
* **WorkflowWorker.java**--contains the workflow worker (decider), which polls for decision tasks and schedules new activities.
* **WorkflowStarter.java**--contains the workflow starter, which starts a new workflow execution, which will cause SWF to start generating decision and workflow tasks for your workers to consume.


[[swf-hello-common,swf-hello-common.title]]
=== Common steps for all source files

All of the files that you create to house your Java classes will have a few things in common. In the interest of time, these steps  __will be implied every time you add a new file to the project__:

. Create the file in the in the project's [path]``src/main/java/example/swf/hello/`` directory.
. Add a `package` declaration to the beginning of each file to declare its namespace. The example project uses:
+
[source,java]
----
package aws.example.helloswf;
----
. Add `import` declarations for the link:sdk-for-java/v1/reference/com/amazonaws/services/simpleworkflow/AmazonSimpleWorkflowClient.html["AmazonSimpleWorkflowClient", type="documentation"] class and for multiple classes in the `com.amazonaws.services.simpleworkflow.model` namespace. To simplify things, we'll use:
+
[source,java]
----
import com.amazonaws.regions.Regions;
import com.amazonaws.services.simpleworkflow.AmazonSimpleWorkflow;
import com.amazonaws.services.simpleworkflow.AmazonSimpleWorkflowClientBuilder;
import com.amazonaws.services.simpleworkflow.model.*;
----


[[swf-hello-hellotypes,swf-hello-hellotypes.title]]
=== Register a domain, workflow and activity types

We'll begin by creating a new executable class,  [path]``HelloTypes.java``. This file will contain shared data that different parts of your workflow will need to know about, such as the name and version of your activity and workflow types, the domain name and the task list name.

. Open your text editor and create the file [path]``HelloTypes.java``, adding a package declaration and imports according to the  xref:swf-hello-common[common steps,linkend=swf-hello-common].
. Declare the `HelloTypes` class and provide it with values to use for your registered activity and workflow types:
+
[source,java]
----
    public static final String DOMAIN = "HelloDomain";
    public static final String TASKLIST = "HelloTasklist";
    public static final String WORKFLOW = "HelloWorkflow";
    public static final String WORKFLOW_VERSION = "1.0";
    public static final String ACTIVITY = "HelloActivity";
    public static final String ACTIVITY_VERSION = "1.0";
----
+

These values will be used throughout the code.
. After the String declarations, create an instance of the link:sdk-for-java/v1/reference/com/amazonaws/services/simpleworkflow/AmazonSimpleWorkflowClient.html["AmazonSimpleWorkflowClient", type="documentation"] class. This is the basic interface to the {SWF} methods provided by the {sdk-java}.
+
[source,java]
----
private static final AmazonSimpleWorkflow swf =
    AmazonSimpleWorkflowClientBuilder.standard().withRegion(Regions.DEFAULT_REGION).build();
----
. Add a new function to register a SWF domain. A _domain_ is a logical container for a number of related SWF activity and workflow types. SWF components can only communicate with each other if they exist within the same domain.
+
[source,java]
----
    try {
        System.out.println("** Registering the domain '" + DOMAIN + "'.");
        swf.registerDomain(new RegisterDomainRequest()
            .withName(DOMAIN)
            .withWorkflowExecutionRetentionPeriodInDays("1"));
    } catch (DomainAlreadyExistsException e) {
        System.out.println("** Domain already exists!");
    }
----
+

When you register a domain, you provide it with a  _name_ (any set of 1 - 256 characters excluding ``:``, ``/``, ``|``, control characters or the literal string '`arn') and a __retention period__, which is the number of days that {SWF} will keep your workflow's execution history data after a workflow execution has completed. The maximum workflow execution retention period is 90 days. See link:sdk-for-java/v1/reference/com/amazonaws/services/simpleworkflow/model/RegisterDomainRequest.html["RegisterDomainRequest", type="documentation"] for more information.
+

If a domain with that name already exists, a link:sdk-for-java/v1/reference/com/amazonaws/services/simpleworkflow/model/DomainAlreadyExistsException.html["DomainAlreadyExistsException", type="documentation"] is raised. Because we're unconcerned if the domain has already been created, we can ignore the exception.
+
NOTE: This code demonstrates a common pattern when working with {sdk-java} methods, data for the method is supplied by a class in the `simpleworkflow.model` namespace, which you instantiate and populate using the chainable `$$.$$with*` methods.
. Add a function to register a new activity type. An _activity_ represents a unit of work in your workflow.
+
[source,java]
----
    try {
        System.out.println("** Registering the activity type '" + ACTIVITY +
            "-" + ACTIVITY_VERSION + "'.");
        swf.registerActivityType(new RegisterActivityTypeRequest()
            .withDomain(DOMAIN)
            .withName(ACTIVITY)
            .withVersion(ACTIVITY_VERSION)
            .withDefaultTaskList(new TaskList().withName(TASKLIST))
            .withDefaultTaskScheduleToStartTimeout("30")
            .withDefaultTaskStartToCloseTimeout("600")
            .withDefaultTaskScheduleToCloseTimeout("630")
            .withDefaultTaskHeartbeatTimeout("10"));
    } catch (TypeAlreadyExistsException e) {
        System.out.println("** Activity type already exists!");
    }
----
+

An activity type is identified by a  _name_ and a __version__, which are used to uniquely identify the activity from any others in the domain that it's registered in. Activities also contain a number of optional parameters, such as the default task-list used to receive tasks and data from SWF and a number of different timeouts that you can use to place constraints upon how long different parts of the activity execution can take. See link:sdk-for-java/v1/reference/com/amazonaws/services/simpleworkflow/model/RegisterActivityTypeRequest.html["RegisterActivityTypeRequest", type="documentation"] for more information.
+
NOTE: All timeout values are specified in __seconds__. See link:amazonswf/latest/developerguide/swf-timeout-types.html["pass:q[[.shared\]`SWF`] Timeout Types", type="documentation"] for a full description of how timeouts affect your workflow executions.
+
+

If the activity type that you're trying to register already exists, an  link:sdk-for-java/v1/reference/com/amazonaws/services/simpleworkflow/model/TypeAlreadyExistsException.html["TypeAlreadyExistsException", type="documentation"] is raised.
. Add a function to register a new workflow type. A __workflow__, also known as a _decider_ represents the logic of your workflow's execution.
+
[source,java]
----
    try {
        System.out.println("** Registering the workflow type '" + WORKFLOW +
            "-" + WORKFLOW_VERSION + "'.");
        swf.registerWorkflowType(new RegisterWorkflowTypeRequest()
            .withDomain(DOMAIN)
            .withName(WORKFLOW)
            .withVersion(WORKFLOW_VERSION)
            .withDefaultChildPolicy(ChildPolicy.TERMINATE)
            .withDefaultTaskList(new TaskList().withName(TASKLIST))
            .withDefaultTaskStartToCloseTimeout("30"));
    } catch (TypeAlreadyExistsException e) {
        System.out.println("** Workflow type already exists!");
    }
----
+

Similar to activity types, workflow types are identified by a  _name_ and a _version_ and also have configurable timeouts. See link:sdk-for-java/v1/reference/com/amazonaws/services/simpleworkflow/model/RegisterWorkflowTypeRequest.html["RegisterWorkflowTypeRequest", type="documentation"] for more information.
+

If the workflow type that you're trying to register already exists, an link:sdk-for-java/v1/reference/com/amazonaws/services/simpleworkflow/model/TypeAlreadyExistsException.html["TypeAlreadyExistsException", type="documentation"] is raised.
. Finally, make the class executable by providing it a `main` method, which will register the domain, the activity type, and the workflow type in turn:
+
[source,java]
----
    registerDomain();
    registerWorkflowType();
    registerActivityType();
----

You can  xref:swf-hello-build[build,linkend=swf-hello-build] and xref:swf-hello-run-register[run,linkend=swf-hello-run-register] the application now to run the registration script, or continue with coding the activity and workflow workers. Once the domain, workflow and activity have been registered, you won't need to run this again--these types persist until you deprecate them yourself.

[[implement-the-activity-worker,implement-the-activity-worker.title]]
=== Implement the activity worker

An  _activity_ is the basic unit of work in a workflow. A workflow provides the logic, scheduling activities to be run (or other actions to be taken) in response to decision tasks. A typical workflow usually consists of a number of activities that can run synchronously, asynchronously, or a combination of both.

The _activity worker_ is the bit of code that polls for activity tasks that are generated by {SWF} in response to workflow decisions. When it receives an activity task, it runs the corresponding activity and returns a success/failure response back to the workflow.

We'll implement a simple activity worker that drives a single activity.

. Open your text editor and create the file [path]``ActivityWorker.java``, adding a package declaration and imports according to the  xref:swf-hello-common[common steps,linkend=swf-hello-common].
+
[source,java]
----
import com.amazonaws.regions.Regions;
import com.amazonaws.services.simpleworkflow.AmazonSimpleWorkflow;
import com.amazonaws.services.simpleworkflow.AmazonSimpleWorkflowClientBuilder;
import com.amazonaws.services.simpleworkflow.model.*;
----
. Add the `ActivityWorker` class to the file, and give it a data member to hold a SWF client that we'll use to interact with {SWF}:
+
[source,java]
----
    private static final AmazonSimpleWorkflow swf =
            AmazonSimpleWorkflowClientBuilder.standard().withRegion(Regions.DEFAULT_REGION).build();
----
. Add the method that we'll use as an activity:
+
[source,java]
----
private static String sayHello(String input) throws Throwable {
    return "Hello, " + input + "!";
}
----
+

The activity simply takes a string, combines it into a greeting and returns the result. Although there is little chance that this activity will raise an exception, it's a good idea to design activities that can raise an error if something goes wrong.
. Add a `main` method that we'll use as the activity task polling method. We'll start it by adding some code to poll the task list for activity tasks:
+
[source,java]
----
        System.out.println("Polling for an activity task from the tasklist '"
                + HelloTypes.TASKLIST + "' in the domain '" +
                HelloTypes.DOMAIN + "'.");

        ActivityTask task = swf.pollForActivityTask(
            new PollForActivityTaskRequest()
                .withDomain(HelloTypes.DOMAIN)
                .withTaskList(
                    new TaskList().withName(HelloTypes.TASKLIST)));

        String task_token = task.getTaskToken();
----
+

The activity receives tasks from {SWF} by calling the SWF client's  `pollForActivityTask` method, specifying the domain and task list to use in the passed-in link:sdk-for-java/v1/reference/com/amazonaws/services/simpleworkflow/model/PollForActivityTaskRequest.html["PollForActivityTaskRequest", type="documentation"].
+

Once a task is received, we retrieve a unique identifier for it by calling the task's `getTaskToken` method.
. Next, write some code to process the tasks that come in. Add the following to your `main` method, right after the code that polls for the task and retrieves its task token.
+
[source,java]
----
    if (task_token != null) {
        String result = null;
        Throwable error = null;

        try {
            System.out.println("Executing the activity task with input '" +
                    task.getInput() + "'.");
            result = sayHello(task.getInput());
        } catch (Throwable th) {
            error = th;
        }

        if (error == null) {
            System.out.println("The activity task succeeded with result '"
                    + result + "'.");
            swf.respondActivityTaskCompleted(
                new RespondActivityTaskCompletedRequest()
                    .withTaskToken(task_token)
                    .withResult(result));
        } else {
            System.out.println("The activity task failed with the error '"
                    + error.getClass().getSimpleName() + "'.");
            swf.respondActivityTaskFailed(
                new RespondActivityTaskFailedRequest()
                    .withTaskToken(task_token)
                    .withReason(error.getClass().getSimpleName())
                    .withDetails(error.getMessage()));
        }
    }
----
+

If the task token is not  ``null``, then we can start running the activity method (``sayHello``), providing it with the input data that was sent with the task.
+

If the task _succeeded_ (no error was generated), then the worker responds to SWF by calling the SWF client's `respondActivityTaskCompleted` method with a link:sdk-for-java/v1/reference/com/amazonaws/services/simpleworkflow/model/RespondActivityTaskCompletedRequest.html["RespondActivityTaskCompletedRequest", type="documentation"] object containing the task token and the activity's result data.
+

On the other hand, if the task __failed__, then we respond by calling the `respondActivityTaskFailed` method with a link:sdk-for-java/v1/reference/com/amazonaws/services/simpleworkflow/model/RespondActivityTaskFailedRequest.html["RespondActivityTaskFailedRequest", type="documentation"] object, passing it the task token and information about the error.


[NOTE]
====

This activity will not shut down gracefully if killed. Although it is beyond the scope of this tutorial, an alternative implementation of this activity worker is provided in the accompanying topic,  xref:swf-graceful-shutdown[Shutting Down Activity and Workflow Workers Gracefully,linkend=swf-graceful-shutdown].

====

[[implement-the-workflow-worker,implement-the-workflow-worker.title]]
=== Implement the workflow worker

Your workflow logic resides in a piece of code known as a  **workflow worker**. The workflow worker polls for decision tasks that are sent by {SWF} in the domain, and on the default tasklist, that the workflow type was registered with.

When the workflow worker receives a task, it makes some sort of decision (usually whether to schedule a new activity or not) and takes an appropriate action (such as scheduling the activity).

. Open your text editor and create the file [path]``WorkflowWorker.java``, adding a package declaration and imports according to the  xref:swf-hello-common[common steps,linkend=swf-hello-common].
. Add a few additional imports to the file:
+
[source,java]
----
import com.amazonaws.regions.Regions;
import com.amazonaws.services.simpleworkflow.AmazonSimpleWorkflow;
import com.amazonaws.services.simpleworkflow.AmazonSimpleWorkflowClientBuilder;
import com.amazonaws.services.simpleworkflow.model.*;
import java.util.ArrayList;
import java.util.List;
import java.util.UUID;
----
. Declare the `WorkflowWorker` class, and create an instance of the link:sdk-for-java/v1/reference/com/amazonaws/services/simpleworkflow/AmazonSimpleWorkflowClient.html["AmazonSimpleWorkflowClient", type="documentation"] class used to access SWF methods.
+
[source,java]
----
    private static final AmazonSimpleWorkflow swf =
            AmazonSimpleWorkflowClientBuilder.standard().withRegion(Regions.DEFAULT_REGION).build();
----
. Add the `main` method. The method loops continuously, polling for decision tasks using the SWF client's `pollForDecisionTask` method. The link:sdk-for-java/v1/reference/com/amazonaws/services/simpleworkflow/model/PollForDecisionTaskRequest.html["PollForDecisionTaskRequest", type="documentation"] provides the details.
+
[source,java]
----
    PollForDecisionTaskRequest task_request =
        new PollForDecisionTaskRequest()
            .withDomain(HelloTypes.DOMAIN)
            .withTaskList(new TaskList().withName(HelloTypes.TASKLIST));

    while (true) {
        System.out.println(
                "Polling for a decision task from the tasklist '" +
                HelloTypes.TASKLIST + "' in the domain '" +
                HelloTypes.DOMAIN + "'.");

        DecisionTask task = swf.pollForDecisionTask(task_request);

        String taskToken = task.getTaskToken();
        if (taskToken != null) {
            try {
                executeDecisionTask(taskToken, task.getEvents());
            } catch (Throwable th) {
                th.printStackTrace();
            }
        }
    }
----
+

Once a task is received, we call its  `getTaskToken` method, which returns a string that can be used to identify the task. If the returned token is not ``null``, then we process it further in the `executeDecisionTask` method, passing it the task token and the list of link:sdk-for-java/v1/reference/com/amazonaws/services/simpleworkflow/model/HistoryEvent.html["HistoryEvent", type="documentation"] objects sent with the task.
. Add the `executeDecisionTask` method, taking the task token (a ``String``) and the `HistoryEvent` list.
+
[source,java]
----
    List<Decision> decisions = new ArrayList<Decision>();
    String workflow_input = null;
    int scheduled_activities = 0;
    int open_activities = 0;
    boolean activity_completed = false;
    String result = null;
----
+

We also set up some data members to keep track of things such as:
+
** A list of link:sdk-for-java/v1/reference/com/amazonaws/services/simpleworkflow/model/Decision.html["Decision", type="documentation"] objects used to report the results of processing the task.
** A String to hold workflow input provided by the "`WorkflowExecutionStarted`" event
** a count of the scheduled and open (running) activities to avoid scheduling the same activity when it has already been scheduled or is currently running.
** a boolean to indicate that the activity has completed.
** A String to hold the activity results, for returning it as our workflow result.
. Next, add some code to `executeDecisionTask` to process the `HistoryEvent` objects that were sent with the task, based on the event type reported by the `getEventType` method.
+
[source,java]
----
System.out.println("Executing the decision task for the history events: [");
for (HistoryEvent event : events) {
    System.out.println("  " + event);
    switch(event.getEventType()) {
        case "WorkflowExecutionStarted":
            workflow_input =
                event.getWorkflowExecutionStartedEventAttributes()
                     .getInput();
            break;
        case "ActivityTaskScheduled":
            scheduled_activities++;
            break;
        case "ScheduleActivityTaskFailed":
            scheduled_activities--;
            break;
        case "ActivityTaskStarted":
            scheduled_activities--;
            open_activities++;
            break;
        case "ActivityTaskCompleted":
            open_activities--;
            activity_completed = true;
            result = event.getActivityTaskCompletedEventAttributes()
                          .getResult();
            break;
        case "ActivityTaskFailed":
            open_activities--;
            break;
        case "ActivityTaskTimedOut":
            open_activities--;
            break;
    }
}
System.out.println("]");
----
+

For the purposes of our workflow, we are most interested in:
+
** the "`WorkflowExecutionStarted`" event, which indicates that the workflow execution has started (typically meaning that you should run the first activity in the workflow), and that provides the initial input provided to the workflow. In this case, it's the name portion of our greeting, so it's saved in a String for use when scheduling the activity to run.
** the "`ActivityTaskCompleted`" event, which is sent once the scheduled activity is complete. The event data also includes the return value of the completed activity. Since we have only one activity, we'll use that value as the result of the entire workflow.

+

The other event types can be used if your workflow requires them. See the  link:sdk-for-java/v1/reference/com/amazonaws/services/simpleworkflow/model/HistoryEvent.html["HistoryEvent", type="documentation"] class description for information about each event type.
+
NOTE: Strings in `switch` statements were introduced in Java 7. If you're using an earlier version of Java, you can make use of the link:sdk-for-java/v1/reference/com/amazonaws/services.simpleworkflow.model.EventType.html["EventType", type="documentation"] class to convert the `String` returned by `history_event.getType()` to an enum value and then back to a `String` if necessary:

[source,java]
----
EventType et = EventType.fromValue(event.getEventType());
----
. After the `switch` statement, add more code to respond with an appropriate _decision_ based on the task that was received.
+
[source,java]
----
if (activity_completed) {
    decisions.add(
        new Decision()
            .withDecisionType(DecisionType.CompleteWorkflowExecution)
            .withCompleteWorkflowExecutionDecisionAttributes(
                new CompleteWorkflowExecutionDecisionAttributes()
                    .withResult(result)));
} else {
    if (open_activities == 0 && scheduled_activities == 0) {

        ScheduleActivityTaskDecisionAttributes attrs =
            new ScheduleActivityTaskDecisionAttributes()
                .withActivityType(new ActivityType()
                    .withName(HelloTypes.ACTIVITY)
                    .withVersion(HelloTypes.ACTIVITY_VERSION))
                .withActivityId(UUID.randomUUID().toString())
                .withInput(workflow_input);

        decisions.add(
                new Decision()
                    .withDecisionType(DecisionType.ScheduleActivityTask)
                    .withScheduleActivityTaskDecisionAttributes(attrs));
    } else {
        // an instance of HelloActivity is already scheduled or running. Do nothing, another
        // task will be scheduled once the activity completes, fails or times out
    }
}

System.out.println("Exiting the decision task with the decisions " + decisions);
----
+
** If the activity hasn't been scheduled yet, we respond with a `ScheduleActivityTask` decision, which provides information in a link:sdk-for-java/v1/reference/com/amazonaws/services/simpleworkflow/model/ScheduleActivityTaskDecisionAttributes.html["ScheduleActivityTaskDecisionAttributes", type="documentation"] structure about the activity that {SWF} should schedule next, also including any data that {SWF} should send to the activity.
** If the activity was completed, then we consider the entire workflow completed and respond with a `CompletedWorkflowExecution` decision, filling in a link:sdk-for-java/v1/reference/com/amazonaws/services/simpleworkflow/model/CompleteWorkflowExecutionDecisionAttributes.html["CompleteWorkflowExecutionDecisionAttributes", type="documentation"] structure to provide details about the completed workflow. In this case, we return the result of the activity.

+

In either case, the decision information is added to the  `Decision` list that was declared at the top of the method.
. Complete the decision task by returning the list of `Decision` objects collected while processing the task. Add this code at the end of the `executeDecisionTask` method that we've been writing:
+
[source,java]
----
swf.respondDecisionTaskCompleted(
    new RespondDecisionTaskCompletedRequest()
        .withTaskToken(taskToken)
        .withDecisions(decisions));
----
+

The SWF client's  `respondDecisionTaskCompleted` method takes the task token that identifies the task as well as the list of `Decision` objects.


[[implement-the-workflow-starter,implement-the-workflow-starter.title]]
=== Implement the workflow starter

Finally, we'll write some code to start the workflow execution.

. Open your text editor and create the file [path]``WorkflowStarter.java``, adding a package declaration and imports according to the  xref:swf-hello-common[common steps,linkend=swf-hello-common].
. Add the `WorkflowStarter` class:
+
[source,java]
----
package aws.example.helloswf;


import com.amazonaws.regions.Regions;
import com.amazonaws.services.simpleworkflow.AmazonSimpleWorkflow;
import com.amazonaws.services.simpleworkflow.AmazonSimpleWorkflowClientBuilder;
import com.amazonaws.services.simpleworkflow.model.*;

public class WorkflowStarter {
    private static final AmazonSimpleWorkflow swf =
            AmazonSimpleWorkflowClientBuilder.standard().withRegion(Regions.DEFAULT_REGION).build();
    public static final String WORKFLOW_EXECUTION = "HelloWorldWorkflowExecution";

    public static void main(String[] args) {
        String workflow_input = "{SWF}";
        if (args.length > 0) {
            workflow_input = args[0];
        }

        System.out.println("Starting the workflow execution '" + WORKFLOW_EXECUTION +
                "' with input '" + workflow_input + "'.");

        WorkflowType wf_type = new WorkflowType()
            .withName(HelloTypes.WORKFLOW)
            .withVersion(HelloTypes.WORKFLOW_VERSION);

        Run run = swf.startWorkflowExecution(new StartWorkflowExecutionRequest()
            .withDomain(HelloTypes.DOMAIN)
            .withWorkflowType(wf_type)
            .withWorkflowId(WORKFLOW_EXECUTION)
            .withInput(workflow_input)
            .withExecutionStartToCloseTimeout("90"));

        System.out.println("Workflow execution started with the run id '" +
                run.getRunId() + "'.");
    }
}
----
+

The  `WorkflowStarter` class consists of a single method, ``main``, which takes an optional argument passed on the command-line as input data for the workflow.
+

The SWF client method, ``startWorkflowExecution``, takes a link:sdk-for-java/v1/reference/com/amazonaws/services/simpleworkflow/model/StartWorkflowExecutionRequest.html["StartWorkflowExecutionRequest", type="documentation"] object as input. Here, in addition to specifying the domain and workflow type to run, we provide it with:
+
** a human-readable workflow execution name
** workflow input data (provided on the command-line in our example)
** a timeout value that represents how long, in seconds, that the entire workflow should take to run.

+

The  link:sdk-for-java/v1/reference/com/amazonaws/services/simpleworkflow/model/Run.html["Run", type="documentation"] object that `startWorkflowExecution` returns provides a __run ID__, a value that can be used to identify this particular workflow execution in {SWF}'s history of your workflow executions.
+
NOTE: The run ID is generated by {SWF}, and is _not_ the same as the workflow execution name that you pass in when starting the workflow execution.


[[swf-hello-build,swf-hello-build.title]]
== Build the example

To build the example project with Maven, go to the  [path]``helloswf`` directory and type:

[source,sh]
----
mvn package
----

The resulting  [path]``helloswf-1.0.jar`` will be generated in the  [path]``target`` directory.

[[run-the-example,run-the-example.title]]
== Run the example

The example consists of four separate executable classes, which are run independently of each other.

[NOTE]
====

If you are using a Linux, macOS, or Unix system, you can run all of them, one after another, in a single terminal window. If you are running Windows, you should open two additional command-line instances and navigate to the [path]``helloswf`` directory in each.

====

[[swf-hello-set-classpath,swf-hello-set-classpath.title]]
=== Setting the Java classpath

Although Maven has handled the dependencies for you, to run the example, you'll need to provide the {AWS} SDK library and its dependencies on your Java classpath. You can either set the  `CLASSPATH` environment variable to the location of your {AWS} SDK libraries and the [path]``third-party/lib`` directory in the SDK, which includes necessary dependencies:

[source,sh]
----
export CLASSPATH='target/helloswf-1.0.jar:/path/to/sdk/lib/*:/path/to/sdk/third-party/lib/*'
java example.swf.hello.HelloTypes
----

or use the  *``**java**``* command's `-cp` option to set the classpath while running each applications.

[source,sh]
----
java -cp target/helloswf-1.0.jar:/path/to/sdk/lib/*:/path/to/sdk/third-party/lib/* \
  example.swf.hello.HelloTypes
----

The style that you use is up to you. If you had no trouble building the code, both then try to run the examples and get a series of "`NoClassDefFound`" errors, it is likely because the classpath is set incorrectly.

[[swf-hello-run-register,swf-hello-run-register.title]]
=== Register the domain, workflow and activity types

Before running your workers and the workflow starter, you'll need to register the domain and your workflow and activity types. The code to do this was implemented in  xref:swf-hello-hellotypes[Register a domain workflow and activity types,linkend=swf-hello-hellotypes].

After building, and if you've xref:swf-hello-set-classpath[set the CLASSPATH,linkend=swf-hello-set-classpath], you can run the registration code by executing the command:

[source,sh]
----
    echo 'Supply the name of one of the example classes as an argument.'
----


[[swf-hello-run-workers,swf-hello-run-workers.title]]
=== Start the activity and workflow workers

Now that the types have been registered, you can start the activity and workflow workers. These will continue to run and poll for tasks until they are killed, so you should either run them in separate terminal windows, or, if you're running on Linux, macOS, or Unix you can use the  `&` operator to cause each of them to spawn a separate process when run.

[source,sh]
----
    echo 'If there are arguments to the class, put them in quotes after the class name.'
    exit 1
----

If you're running these commands in separate windows, omit the final  `&` operator from each line.

[[swf-hello-start-execution,swf-hello-start-execution.title]]
=== Start the workflow execution

Now that your activity and workflow workers are polling, you can start the workflow execution. This process will run until the workflow returns a completed status. You should run it in a new terminal window (unless you ran your workers as new spawned processes by using the  `&` operator).

[source,sh]
----
fi
----

[NOTE]
====

If you want to provide your own input data, which will be passed first to the workflow and then to the activity, add it to the command-line. For example:

[source,sh]
----
echo "## Running $className..."
----

====

Once you begin the workflow execution, you should start seeing output delivered by both workers and by the workflow execution itself. When the workflow finally completes, its output will be printed to the screen.

[[complete-source-for-this-example,complete-source-for-this-example.title]]
== Complete source for this example

You can browse the  {https---github-com-awsdocs-aws-doc-sdk-examples-tree-master-java-example-code-swf}[complete source] for this example on Github in the _aws-java-developer-guide_ repository.

[[for-more-information,for-more-information.title]]
== For more information

* The workers presented here can result in lost tasks if they are shutdown while a workflow poll is still going on. To find out how to shut down workers gracefully, see xref:swf-graceful-shutdown[Shutting Down Activity and Workflow Workers Gracefully,linkend=swf-graceful-shutdown].
* To learn more about {SWF}, visit the link:swf/["pass:q[[.shared\]`SWF`]", type="marketing"] home page or view the link:amazonswf/latest/developerguide/["pass:q[[.shared\]`SWF`] Developer Guide", type="documentation"].
* You can use the {FFlong} for Java to write more complex workflows in an elegant Java style using annotations. To learn more, see the link:amazonswf/latest/awsflowguide/["pass:q[[.shared\]`FFlong`] for Java Developer Guide", type="documentation"].
