//!!NODE_ROOT <section>
include::../../includes.txt[]

[."topic"]
[[swf-lambda-task,swf-lambda-task.title]]
= [[lambda-tasks, Lambda Tasks]]Lambda Tasks
:info_doctype: section
:info_title: {LAM} Tasks

As an alternative to, or in conjunction with, {SWF} activities, you can use  link:lambda/["Lambda", type="marketing"] functions to represent units of work in your workflows, and schedule them similarly to activities.

This topic focuses on how to implement {SWF} {LAM} tasks using the {sdk-java}. For more information about {LAM} tasks in general, see link:amazonswf/latest/developerguide/lambda-task.html["pass:q[[.shared\]`LAMlong`] Tasks", type="documentation"] in the {SWF} Developer Guide.

[[set-up-a-cross-service-iam-role-to-run-your-lambda-function,set-up-a-cross-service-iam-role-to-run-your-lambda-function.title]]
== Set up a cross-service IAM role to run your Lambda function

Before {SWF} can run your {LAM} function, you need to set up an IAM role to give {SWF} permission to run {LAM} functions on your behalf. For complete information about how to do this, see  link:amazonswf/latest/developerguide/lambda-task.html["pass:q[[.shared\]`LAMlong`] Tasks", type="documentation"].

You will need the Amazon Resource Name (ARN) of this IAM role when you register a workflow that will use {LAM} tasks.

[[create-a-lambda-function,create-a-lambda-function.title]]
== Create a {LAM} function

You can write {LAM} functions in a number of different languages, including Java. For complete information about how to author, deploy and use {LAM} functions, see the  link:lambda/latest/dg/["pass:q[[.shared\]`LAMlong`] Developer Guide", type="documentation"].

[NOTE]
====

It doesn't matter what language you use to write your {LAM} function, it can be scheduled and run by __any__{SWF} workflow, regardless of the language that your workflow code is written in. {SWF} handles the details of running the function and passing data to and from it.

====

Here's a simple {LAM} function that could be used in place of the activity in  xref:swf-hello[Building a Simple {SWF} Application,linkend=swf-hello].



* This version is written in JavaScript, which can be entered directly using the https://console.aws.amazon.com/console/home[{console}]:
+
[source,javascript]
----
exports.handler = function(event, context) {
    context.succeed("Hello, " + event.who + "!");
};
----
* Here is the same function written in Java, which you could also deploy and run on Lambda:
+
[source,java]
----
package example.swf.hellolambda;

import com.amazonaws.services.lambda.runtime.Context;
import com.amazonaws.services.lambda.runtime.RequestHandler;
import com.amazonaws.util.json.JSONException;
import com.amazonaws.util.json.JSONObject;

public class SwfHelloLambdaFunction implements RequestHandler<Object, Object> {
    @Override
    public Object handleRequest(Object input, Context context) {
        String who = "{SWF}";
        if (input != null) {
            JSONObject jso = null;
            try {
                jso = new JSONObject(input.toString());
                who = jso.getString("who");
            } catch (JSONException e) {
                e.printStackTrace();
            }
        }
        return ("Hello, " + who + "!");
    }
}
----
+
NOTE: To learn more about deploying Java functions to Lambda, see link:lambda/latest/dg/lambda-java-how-to-create-deployment-package.html["Creating a Deployment Package (Java)", type="documentation"] in the pass:q[[.shared\]`LAMlong`] Developer Guide. You will also want to look at the section titled link:lambda/latest/dg/java-programming-model.html["Programming Model for Authoring pass:q[[.shared\]`LAM`] Functions in Java", type="documentation"].

{LAM} functions take an  _event_ or _input_ object as the first parameter, and a _context_ object as the second, which provides information about the request to run the {LAM} function. This particular function expects input to be in JSON, with a `who` field set to the name used to create the greeting.

[[register-a-workflow-for-use-with-lam,register-a-workflow-for-use-with-lam.title]]
== Register a workflow for use with Lambda

For a workflow to schedule a {LAM} function, you must provide the name of the IAM role that provides {SWF} with permission to invoke {LAM} functions. You can set this during workflow registration by using the  `withDefaultLambdaRole` or `setDefaultLambdaRole` methods of link:sdk-for-java/v1/reference/com/amazonaws/services/simpleworkflow/model/RegisterWorkflowTypeRequest.html["RegisterWorkflowTypeRequest", type="documentation"].

[source,java]
----
System.out.println("** Registering the workflow type '" + WORKFLOW + "-" + WORKFLOW_VERSION
        + "'.");
try {
    swf.registerWorkflowType(new RegisterWorkflowTypeRequest()
        .withDomain(DOMAIN)
        .withName(WORKFLOW)
        .withDefaultLambdaRole(lambda_role_arn)
        .withVersion(WORKFLOW_VERSION)
        .withDefaultChildPolicy(ChildPolicy.TERMINATE)
        .withDefaultTaskList(new TaskList().withName(TASKLIST))
        .withDefaultTaskStartToCloseTimeout("30"));
}
catch (TypeAlreadyExistsException e) {
----


[[schedule-a-lam-task,schedule-a-lam-task.title]]
== Schedule a {LAM} task

Schedule a {LAM} task is similar to scheduling an activity. You provide a  link:sdk-for-java/v1/reference/com/amazonaws/services/simpleworkflow/model/Decision.html["Decision", type="documentation"] with a `ScheduleLambdaFunction`link:sdk-for-java/v1/reference/com/amazonaws/services/simpleworkflow/model/DecisionType.html["DecisionType", type="documentation"] and with link:sdk-for-java/v1/reference/com/amazonaws/services/simpleworkflow/model/ScheduleLambdaFunctionDecisionAttributes.html["ScheduleLambdaFunctionDecisionAttributes", type="documentation"].

[source,java]
----


running_functions == 0 && scheduled_functions == 0) {
AWSLambda lam = AWSLambdaClientBuilder.defaultClient();
GetFunctionConfigurationResult function_config =
    lam.getFunctionConfiguration(
            new GetFunctionConfigurationRequest()
                .withFunctionName("HelloFunction"));
String function_arn = function_config.getFunctionArn();

ScheduleLambdaFunctionDecisionAttributes attrs =
    new ScheduleLambdaFunctionDecisionAttributes()
        .withId("HelloFunction (Lambda task example)")
        .withName(function_arn)
        .withInput(workflow_input);

decisions.add(
----

In the  ``ScheduleLambdaFuntionDecisionAttributes``, you must supply a __name__, which is the ARN of the {LAM} function to call, and an __id__, which is the name that {SWF} will use to identify the {LAM} function in history logs.

You can also provide optional _input_ for the {LAM} function and set its _start to close timeout_ value, which is the number of seconds that the {LAM} function is allowed to run before generating a `LambdaFunctionTimedOut` event.

[NOTE]
====

This code uses the link:sdk-for-java/v1/reference/com/amazonaws/services/lambda/AWSLambdaClient.html["AWSLambdaClient", type="documentation"] to retrieve the ARN of the {LAM} function, given the function name. You can use this technique to avoid hard-coding the full ARN (which includes your {AWS-account} ID) in your code.

====

[[handle-lam-function-events-in-your-decider,handle-lam-function-events-in-your-decider.title]]
== Handle Lambda function events in your decider

{LAM} tasks will generate a number of events that you can take action on when polling for decision tasks in your workflow worker, corresponding to the lifecycle of your {LAM} task, with  link:sdk-for-java/v1/reference/com/amazonaws/services/simpleworkflow/model/EventType.html["EventType", type="documentation"] values such as ``LambdaFunctionScheduled``, ``LambdaFunctionStarted``, and ``LambdaFunctionCompleted``. If the {LAM} function fails, or takes longer to run than its set timeout value, you will receive either a `LambdaFunctionFailed` or `LambdaFunctionTimedOut` event type, respectively.

[source,java]
----
boolean function_completed = false;
String result = null;

System.out.println("Executing the decision task for the history events: [");
for (HistoryEvent event : events) {
    System.out.println("  " + event);
    EventType event_type = EventType.fromValue(event.getEventType());
    switch(event_type) {
    case WorkflowExecutionStarted:
        workflow_input =
            event.getWorkflowExecutionStartedEventAttributes()
                 .getInput();
        break;
    case LambdaFunctionScheduled:
        scheduled_functions++;
        break;
    case ScheduleLambdaFunctionFailed:
        scheduled_functions--;
        break;
    case LambdaFunctionStarted:
        scheduled_functions--;
        running_functions++;
        break;
    case LambdaFunctionCompleted:
        running_functions--;
        function_completed = true;
        result = event.getLambdaFunctionCompletedEventAttributes()
                      .getResult();
        break;
    case LambdaFunctionFailed:
        running_functions--;
        break;
    case LambdaFunctionTimedOut:
        running_functions--;
        break;
----


[[receive-output-from-your-lam-function,receive-output-from-your-lam-function.title]]
== Receive output from your {LAM} function

When you receive a  `LambdaFunctionCompleted`link:sdk-for-java/v1/reference/com/amazonaws/services/simpleworkflow/model/EventType.html["EventType", type="documentation"], you can retrieve your pass:q[[.shared\]`LAM`] function's return value by first calling `getLambdaFunctionCompletedEventAttributes` on the link:sdk-for-java/v1/reference/com/amazonaws/services/simpleworkflow/model/HistoryEvent.html["HistoryEvent", type="documentation"] to get a link:sdk-for-java/v1/reference/com/amazonaws/services/simpleworkflow/model/LambdaFunctionCompletedEventAttributes.html["LambdaFunctionCompletedEventAttributes", type="documentation"] object, and then calling its `getResult` method to retrieve the output of the {LAM} function:

[source,java]
----
 LambdaFunctionCompleted:
running_functions--;
----


[[complete-source-for-this-example,complete-source-for-this-example.title]]
== Complete source for this example

You can browse the  _complete source :github:`<awsdocs/aws-java-developer-guide/tree/master/doc_source/snippets/helloswf_lambda/>_ for this example on Github in the _aws-java-developer-guide_ repository.